# Generated by GitHub Copilot
"""
DSP & SSA E2E Testing Tracker — Single-Sheet Advanced Excel Generator
Produces a fully formatted .xlsx workbook with ONE combined tracking sheet:
  - E2E_Tracker  : DSP Manual (PT+UAT) → DSP Auto (PT+UAT) → SSA/GenAI,
                   all in one sheet with clear section banners
  - Summary      : Live KPI table with COUNTIFS + data-bars
  - Team_Data    : Full roster
  - How_To_Use   : Instructions

Release month : May 2026
Deal IDs used :
  PT  Manual  → 0012518935
  PT  Auto    → 0012518952
  UAT Manual  → 0012511117
  UAT Auto    → 0012511127

Requirements: pip install openpyxl
Run:          python generate_tracker.py
Output:       DSP_SSA_Tracker_2026-05.xlsx
"""

import datetime
import os

try:
    from openpyxl import Workbook
    from openpyxl.styles import (
        PatternFill, Font, Alignment, Border, Side,
    )
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation
    from openpyxl.formatting.rule import (
        DataBarRule, Rule,
    )
    from openpyxl.styles.differential import DifferentialStyle
except ImportError:
    raise SystemExit(
        "\n[ERROR] openpyxl not found.\n"
        "Install it with:  pip install openpyxl\n"
    )

# ─────────────────────────────────────────────
#  PALETTE
# ─────────────────────────────────────────────
C = {
    # Header backgrounds
    "hdr_dark":   "0D0F18",
    "hdr_manual": "1A3A5C",
    "hdr_auto":   "1A3C1E",
    "hdr_ssa":    "2D1A4A",
    "hdr_team":   "2A2A0D",
    "hdr_summary":"1A2A3A",

    # Section bands
    "pt_band":    "E6F7FF",  # light blue  — PT rows
    "uat_band":   "FFF7E6",  # light amber — UAT rows

    # Status fills
    "passed":     "D9F7BE",
    "completed":  "B7EB8F",
    "in_progress":"FFE58F",
    "failed":     "FFCCC7",
    "blocked":    "FFA39E",
    "conn_fail":  "FFD6E7",
    "not_started":"F0F0F0",

    # Misc
    "accent":     "22C55E",
    "white":      "FFFFFF",
    "light_gray": "F5F5F5",
    "border":     "D9D9D9",
    "subhdr":     "E8EEF4",
    "tag_blue":   "D6E4FF",
    "tag_purple": "EFDBFF",
}

STATUS_OPTIONS = [
    "Not Started", "In Progress", "Completed",
    "Passed", "Failed", "Blocked", "Connectivity Failing",
]
SG_OPTIONS    = ["SI", "AMS", "BPMS", "IMS"]
ENV_OPTIONS   = ["PT", "UAT"]

# ── Fixed to May 2026 release ──────────────────────────
MODULE_MONTH  = "May 2026"
FILE_MONTH    = "2026-05"
FILE_NAME     = f"DSP_SSA_Tracker_{FILE_MONTH}.xlsx"

# Deal IDs for May release (stored as strings to preserve leading zeros)
DEAL_PT_MANUAL  = "0012518935"
DEAL_PT_AUTO    = "0012518952"
DEAL_UAT_MANUAL = "0012511117"
DEAL_UAT_AUTO   = "0012511127"

# ─────────────────────────────────────────────────────────────────────────────
#  TEAM / ALLOCATION DATA
#
#  INIT_TEAM  — one row per person, with explicit fields:
#    (name, track, sg, ssa_module, env)
#
#  sg         : SG for DSP work  → SI | AMS | BPMS | IMS | ""
#  ssa_module : SSA module name  → S2C | HSP | ODI | RFP | DLC | CDAT |
#                                   Document Management | ""
#  env        : PT | UAT | ""   (blank = not tied to a specific env)
#
#  To change any allocation, just edit this table.
#  DSP Manual rows, DSP Automation rows, and SSA rows in E2E_Tracker are
#  ALL derived directly from here — no re-parsing, no guessing.
# ─────────────────────────────────────────────────────────────────────────────
#                name          track                    sg      ssa_module           env
INIT_TEAM = [
    # ── DSP Manual ─────────────────────────────────────────────────────────
    ("Kalpana",   "DSP Manual",           "SI",   "",                    "PT"),
    ("Swati",     "DSP Manual",           "SI",   "",                    "UAT"),
    ("Harshitha", "DSP Manual",           "AMS",  "",                    "PT"),
    ("Nayak",     "DSP Manual",           "AMS",  "",                    "UAT"),
    ("Reshma",    "DSP Manual",           "BPMS", "",                    "PT"),
    ("Sushmetha", "DSP Manual",           "BPMS", "",                    "UAT"),
    ("Sai kumar", "DSP Manual",           "IMS",  "",                    "PT"),
    ("Naveen A",  "DSP Manual / SSA",     "IMS",  "RFP",                 "UAT"),
    # ── DSP Automation ─────────────────────────────────────────────────────
    ("Haritha",   "DSP Automation",       "SI",   "",                    "PT"),
    ("Prasanna",  "DSP Automation / SSA", "SI",   "HSP",                 "UAT"),
    ("Pratik",    "DSP Automation",       "AMS",  "",                    "PT"),
    ("HariPriya", "DSP Automation",       "AMS",  "",                    "UAT"),
    ("Varadha",   "DSP Automation / SSA", "BPMS", "S2C",                 "PT"),
    ("Narmatha",  "DSP Automation",       "BPMS", "",                    "UAT"),
    ("Saikumar",  "DSP Automation / SSA", "IMS",  "CDAT",                "PT"),
    # ── SSA only ───────────────────────────────────────────────────────────
    ("Veena",     "SSA",                  "",     "S2C",                 ""),
    ("Shyam",     "SSA",                  "",     "ODI",                 ""),
    ("Vignesh",   "SSA",                  "",     "DLC",                 ""),
    ("Gayathri",  "SSA",                  "",     "Document Management", ""),
    # ── Upload ─────────────────────────────────────────────────────────────
    ("Jabben",    "Upload",               "SI",   "",                    "PT"),
    ("NAVYA",     "Upload",               "SI",   "",                    "UAT"),
    ("Komal",     "Upload",               "IMS",  "",                    "PT"),
    ("Aruna",     "Upload",               "IMS",  "",                    "UAT"),
]

# ─────────────────────────────────────────────────────────────────────────────
#  BUILD DSP / SSA TRACKER ROWS FROM TEAM DATA  (no parsing — read directly)
# ─────────────────────────────────────────────────────────────────────────────

def build_dsp_from_team(track_keyword, deal_pt, deal_uat):
    """Return DSP tracker rows for the given track keyword using explicit sg/env."""
    rows = []
    for name, track, sg, ssa_module, env in INIT_TEAM:
        if track_keyword not in track:
            continue
        if not sg or not env:          # skip SSA-only or env-less members
            continue
        deal = deal_pt if env == "PT" else deal_uat
        rows.append((name, "DSP", env, sg, deal, ""))
    return rows

def build_ssa_from_team():
    """Return SSA tracker rows for all members with an ssa_module assignment."""
    rows = []
    for name, track, sg, ssa_module, env in INIT_TEAM:
        if not ssa_module:
            continue
        module = ssa_module if ssa_module == "Document Management" else f"SSA/{ssa_module}"
        rows.append((name, module, "", "", "", "", ""))
    return rows

# These three lists are the single source of truth for E2E_Tracker
INIT_DSP_MANUAL = build_dsp_from_team("DSP Manual",     DEAL_PT_MANUAL,  DEAL_UAT_MANUAL)
INIT_DSP_AUTO   = build_dsp_from_team("DSP Automation", DEAL_PT_AUTO,    DEAL_UAT_AUTO)
INIT_SSA        = build_ssa_from_team()

# ─────────────────────────────────────────────
#  STYLE HELPERS
# ─────────────────────────────────────────────

def fill(hex_color):
    return PatternFill(fill_type="solid", fgColor=hex_color)

def font(bold=False, color="000000", size=10, italic=False):
    return Font(bold=bold, color=color, size=size, italic=italic,
                name="Segoe UI")

def align(h="left", v="center", wrap=False):
    return Alignment(horizontal=h, vertical=v, wrap_text=wrap)

def thin_border():
    s = Side(style="thin", color=C["border"])
    return Border(left=s, right=s, top=s, bottom=s)

def medium_border():
    s = Side(style="medium", color="A0A0A0")
    return Border(left=s, right=s, top=s, bottom=s)

def apply_header_row(ws, row_num, headers, widths, bg_hex, font_color="FFFFFF"):
    """Write a styled header row."""
    for col_idx, (header, width) in enumerate(zip(headers, widths), start=1):
        cell = ws.cell(row=row_num, column=col_idx, value=header)
        cell.fill    = fill(bg_hex)
        cell.font    = font(bold=True, color=font_color, size=10)
        cell.alignment = align(h="center")
        cell.border  = thin_border()
        ws.column_dimensions[get_column_letter(col_idx)].width = width

def apply_data_row(ws, row_num, values, env_val=None, status_col=None):
    """Write a data row with optional env-based banding + status colouring."""
    row_bg = C["pt_band"] if env_val == "PT" else (
             C["uat_band"] if env_val == "UAT" else C["white"])
    for col_idx, val in enumerate(values, start=1):
        cell = ws.cell(row=row_num, column=col_idx, value=val)
        cell.fill      = fill(row_bg)
        cell.font      = font(size=10)
        cell.alignment = align()
        cell.border    = thin_border()

def add_status_validation(ws, col_letter, first_row, last_row):
    """Add dropdown data-validation for the Status column."""
    dv = DataValidation(
        type="list",
        formula1=f'"{",".join(STATUS_OPTIONS)}"',
        showDropDown=False,          # False = show the arrow
        showErrorMessage=True,
        errorTitle="Invalid Status",
        error="Please choose a value from the list.",
    )
    dv.sqref = f"{col_letter}{first_row}:{col_letter}{last_row}"
    ws.add_data_validation(dv)

def add_list_validation(ws, col_letter, first_row, last_row, options):
    dv = DataValidation(
        type="list",
        formula1=f'"{",".join(options)}"',
        showDropDown=False,
        showErrorMessage=True,
        errorTitle="Invalid Value",
        error="Please choose from the dropdown list.",
    )
    dv.sqref = f"{col_letter}{first_row}:{col_letter}{last_row}"
    ws.add_data_validation(dv)

def add_status_conditional_formatting(ws, col_letter, first_row, last_row):
    """Colour-code cells based on status text."""
    rules = [
        ("Passed",               C["passed"],     "276221"),
        ("Completed",            C["completed"],  "276221"),
        ("In Progress",          C["in_progress"],"7D5A00"),
        ("Failed",               C["failed"],     "820014"),
        ("Blocked",              C["blocked"],    "820014"),
        ("Connectivity Failing", C["conn_fail"],  "9E006B"),
        ("Not Started",          C["not_started"],"595959"),
    ]
    cell_range = f"{col_letter}{first_row}:{col_letter}{last_row}"
    for text, bg, fg in rules:
        ds = DifferentialStyle(
            fill=PatternFill(fill_type="solid", fgColor=bg),
            font=Font(bold=True, color=fg, name="Segoe UI"),
        )
        rule = Rule(type="containsText", operator="containsText",
                    text=text, dxf=ds)
        rule.formula = [f'NOT(ISERROR(SEARCH("{text}",{col_letter}{first_row})))']
        ws.conditional_formatting.add(cell_range, rule)

def add_sheet_title(ws, title, subtitle, n_cols):
    """Merge first two rows as a title banner."""
    ws.insert_rows(1, 2)
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=n_cols)
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=n_cols)

    title_cell = ws["A1"]
    title_cell.value     = title
    title_cell.fill      = fill(C["hdr_dark"])
    title_cell.font      = font(bold=True, color="22C55E", size=14)
    title_cell.alignment = align(h="center")

    sub_cell = ws["A2"]
    sub_cell.value     = subtitle
    sub_cell.fill      = fill("1A1F2E")
    sub_cell.font      = font(italic=True, color="8892A4", size=10)
    sub_cell.alignment = align(h="center")

    ws.row_dimensions[1].height = 28
    ws.row_dimensions[2].height = 18

# ─────────────────────────────────────────────────────────────────────────────
#  SINGLE COMBINED TRACKER SHEET
#  Layout (all in "E2E_Tracker"):
#    Row 1-2  : Workbook title banner
#    ── SECTION 1: DSP MANUAL TESTING ──────────────────────────────────────
#    Row 3    : Section banner (dark blue)
#    Row 4    : PT sub-banner + PT deal ID callout
#    Row 5    : Column headers
#    Row 6…   : PT Manual data rows
#    gap row  : UAT sub-banner + UAT deal ID callout
#    next row : Column headers (repeat for UAT)
#    …        : UAT Manual data rows  + 10 empty buffer rows
#    ── SECTION 2: DSP AUTOMATION TESTING ──────────────────────────────────
#    (same pattern, different deal IDs)
#    ── SECTION 3: SSA / GenAI TESTING ─────────────────────────────────────
#    (SSA-specific columns)
# ─────────────────────────────────────────────────────────────────────────────

# Shared column layout for DSP sections
DSP_HEADERS = ["#", "Tester", "Module", "ENV", "SG", "Deal ID",
               "Status", "Comments", "Last Edited By", "Last Edited At", "Notes"]
DSP_WIDTHS  = [4, 28, 10, 7, 9, 14, 22, 28, 22, 18, 28]
N_DSP = len(DSP_HEADERS)

# SSA columns
SSA_HEADERS = ["#", "Tester", "Module / Feature",
               "Deal ID 1", "Deal ID 2", "Deal ID 3", "Deal ID 4",
               "Status", "Last Edited By", "Last Edited At", "Notes"]
SSA_WIDTHS  = [4, 28, 24, 14, 14, 14, 14, 22, 22, 18, 28]
N_SSA = len(SSA_HEADERS)

# Widest column count for merges across all sections
N_COLS = max(N_DSP, N_SSA)  # 11


def _section_banner(ws, row, text, bg_hex):
    """Full-width section title bar."""
    ws.merge_cells(start_row=row, start_column=1,
                   end_row=row, end_column=N_COLS)
    c = ws.cell(row=row, column=1, value=text)
    c.fill      = fill(bg_hex)
    c.font      = font(bold=True, size=12, color="FFFFFF")
    c.alignment = align(h="left")
    ws.row_dimensions[row].height = 24
    return row + 1


def _env_subbanner(ws, row, env_label, deal_id, tag_color):
    """ENV sub-banner with deal ID callout."""
    ws.merge_cells(start_row=row, start_column=1,
                   end_row=row, end_column=N_COLS)
    text = f"  ▶  {env_label}     Deal ID: {deal_id}"
    c = ws.cell(row=row, column=1, value=text)
    c.fill      = fill(tag_color)
    c.font      = font(bold=True, size=11, color="000000")
    c.alignment = align(h="left")
    ws.row_dimensions[row].height = 22
    return row + 1


def _dsp_col_header(ws, row, hdr_bg):
    apply_header_row(ws, row, DSP_HEADERS, DSP_WIDTHS, hdr_bg)
    ws.row_dimensions[row].height = 20
    return row + 1


def _ssa_col_header(ws, row):
    apply_header_row(ws, row, SSA_HEADERS, SSA_WIDTHS, C["hdr_ssa"])
    ws.row_dimensions[row].height = 20
    return row + 1


def _write_dsp_rows(ws, data, row, env_filter, hdr_bg):
    """Write DSP data rows for a given env. Returns (first_data_row, last_data_row, next_free_row)."""
    rows = [(i, r) for i, r in enumerate(data, 1) if r[2] == env_filter]
    first = row
    for local_i, (orig_idx, row_tuple) in enumerate(rows):
        tester, module, env, sg, deal, status = row_tuple
        values = [orig_idx, tester, module, env, sg, deal,
                  status or "", "", "", "", ""]
        apply_data_row(ws, row + local_i, values, env_val=env)
        ws.row_dimensions[row + local_i].height = 18
    last = row + len(rows) - 1
    # Buffer rows
    for buf in range(10):
        r_buf = last + 1 + buf
        apply_data_row(ws, r_buf, [""] * N_DSP, env_val=env_filter)
        ws.row_dimensions[r_buf].height = 16
    return first, last, last + 11


def _write_ssa_rows(ws, row):
    """Write SSA data rows. Returns (first, last, next_free)."""
    first = row
    for i, tup in enumerate(INIT_SSA):
        tester, module, d1, d2, d3, d4, status = tup
        values = [i + 1, tester, module, d1, d2, d3, d4,
                  status or "", "", "", ""]
        apply_data_row(ws, row + i, values)
        ws.row_dimensions[row + i].height = 18
    last = row + len(INIT_SSA) - 1
    for buf in range(10):
        r_buf = last + 1 + buf
        apply_data_row(ws, r_buf, [""] * N_SSA)
        ws.row_dimensions[r_buf].height = 16
    return first, last, last + 11


def build_single_tracker_sheet(wb):
    """Build the single combined E2E_Tracker sheet."""
    ws = wb.create_sheet("E2E_Tracker")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = "22C55E"

    # ── Workbook title (rows 1-2) ──────────────────────────────────────────
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=N_COLS)
    t = ws["A1"]
    t.value     = f"DSP & SSA  —  E2E Testing Tracker  |  {MODULE_MONTH}"
    t.fill      = fill(C["hdr_dark"])
    t.font      = font(bold=True, color="22C55E", size=14)
    t.alignment = align(h="center")
    ws.row_dimensions[1].height = 30

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=N_COLS)
    s = ws["A2"]
    s.value = (
        f"PT Manual: {DEAL_PT_MANUAL}   |   PT Auto: {DEAL_PT_AUTO}   |   "
        f"UAT Manual: {DEAL_UAT_MANUAL}   |   UAT Auto: {DEAL_UAT_AUTO}"
    )
    s.fill      = fill("1A1F2E")
    s.font      = font(italic=True, color="8892A4", size=10)
    s.alignment = align(h="center")
    ws.row_dimensions[2].height = 18

    # Freeze title rows + first col-header row
    ws.freeze_panes = "A6"

    cur = 3  # current write row

    # ════════════════════════════════════════════════════════════════════════
    # SECTION 1 — DSP MANUAL TESTING
    # ════════════════════════════════════════════════════════════════════════
    cur = _section_banner(ws, cur,
                          "  ◈  SECTION 1 — DSP MANUAL TESTING OPPORTUNITIES",
                          C["hdr_manual"])

    # PT Manual
    cur = _env_subbanner(ws, cur,
                         "PT  (Pre-Testing)", DEAL_PT_MANUAL, "C5E8FF")
    manual_pt_col_hdr = cur
    cur = _dsp_col_header(ws, cur, C["hdr_manual"])
    manual_pt_first, manual_pt_last, cur = _write_dsp_rows(
        ws, INIT_DSP_MANUAL, cur, "PT", C["hdr_manual"])

    cur += 1  # gap row

    # UAT Manual
    cur = _env_subbanner(ws, cur,
                         "UAT  (User Acceptance Testing)", DEAL_UAT_MANUAL, "FFE8B2")
    manual_uat_col_hdr = cur
    cur = _dsp_col_header(ws, cur, C["hdr_manual"])
    manual_uat_first, manual_uat_last, cur = _write_dsp_rows(
        ws, INIT_DSP_MANUAL, cur, "UAT", C["hdr_manual"])

    cur += 2  # gap between sections

    # Add dropdowns + CF for both Manual env blocks
    status_col_dsp = get_column_letter(DSP_HEADERS.index("Status") + 1)  # G
    env_col_dsp    = get_column_letter(DSP_HEADERS.index("ENV")    + 1)  # D
    sg_col_dsp     = get_column_letter(DSP_HEADERS.index("SG")     + 1)  # E

    for first, last in [(manual_pt_first, manual_pt_last + 10),
                        (manual_uat_first, manual_uat_last + 10)]:
        add_list_validation(  ws, env_col_dsp,    first, last, ENV_OPTIONS)
        add_list_validation(  ws, sg_col_dsp,     first, last, SG_OPTIONS)
        add_status_validation(ws, status_col_dsp, first, last)
        add_status_conditional_formatting(ws, status_col_dsp, first, last)

    # ════════════════════════════════════════════════════════════════════════
    # SECTION 2 — DSP AUTOMATION TESTING
    # ════════════════════════════════════════════════════════════════════════
    cur = _section_banner(ws, cur,
                          "  ◈  SECTION 2 — DSP AUTOMATION TESTING OPPORTUNITIES",
                          C["hdr_auto"])

    # PT Auto
    cur = _env_subbanner(ws, cur,
                         "PT  (Pre-Testing)", DEAL_PT_AUTO, "C5E8FF")
    cur = _dsp_col_header(ws, cur, C["hdr_auto"])
    auto_pt_first, auto_pt_last, cur = _write_dsp_rows(
        ws, INIT_DSP_AUTO, cur, "PT", C["hdr_auto"])

    cur += 1

    # UAT Auto
    cur = _env_subbanner(ws, cur,
                         "UAT  (User Acceptance Testing)", DEAL_UAT_AUTO, "FFE8B2")
    cur = _dsp_col_header(ws, cur, C["hdr_auto"])
    auto_uat_first, auto_uat_last, cur = _write_dsp_rows(
        ws, INIT_DSP_AUTO, cur, "UAT", C["hdr_auto"])

    cur += 2

    for first, last in [(auto_pt_first, auto_pt_last + 10),
                        (auto_uat_first, auto_uat_last + 10)]:
        add_list_validation(  ws, env_col_dsp,    first, last, ENV_OPTIONS)
        add_list_validation(  ws, sg_col_dsp,     first, last, SG_OPTIONS)
        add_status_validation(ws, status_col_dsp, first, last)
        add_status_conditional_formatting(ws, status_col_dsp, first, last)

    # ════════════════════════════════════════════════════════════════════════
    # SECTION 3 — SSA / GenAI TESTING
    # ════════════════════════════════════════════════════════════════════════
    cur = _section_banner(ws, cur,
                          "  ◈  SECTION 3 — SSA / GenAI MODULE TESTING",
                          C["hdr_ssa"])

    # Note banner
    ws.merge_cells(start_row=cur, start_column=1,
                   end_row=cur, end_column=N_COLS)
    nb = ws.cell(row=cur, column=1,
                 value="  ⚠  Ensure configuration is applied to ALL deals before marking Passed/Completed.")
    nb.fill      = fill("FFFBE6")
    nb.font      = font(size=10, color="7D5A00", italic=True)
    nb.alignment = align(h="left")
    ws.row_dimensions[cur].height = 20
    cur += 1

    cur = _ssa_col_header(ws, cur)
    ssa_first, ssa_last, cur = _write_ssa_rows(ws, cur)

    status_col_ssa = get_column_letter(SSA_HEADERS.index("Status") + 1)  # H
    add_status_validation(ws, status_col_ssa, ssa_first, ssa_last + 10)
    add_status_conditional_formatting(ws, status_col_ssa, ssa_first, ssa_last + 10)

    # ── Store row anchors on ws for Summary to reference ──────────────────
    ws._tracker_anchors = {
        "manual_pt_first":  manual_pt_first,
        "manual_pt_last":   manual_pt_last + 10,
        "manual_uat_first": manual_uat_first,
        "manual_uat_last":  manual_uat_last + 10,
        "auto_pt_first":    auto_pt_first,
        "auto_pt_last":     auto_pt_last + 10,
        "auto_uat_first":   auto_uat_first,
        "auto_uat_last":    auto_uat_last + 10,
        "ssa_first":        ssa_first,
        "ssa_last":         ssa_last + 10,
        "status_col_dsp":   status_col_dsp,   # G
        "status_col_ssa":   status_col_ssa,   # H
        "env_col":          env_col_dsp,      # D
    }

    return ws

# ─────────────────────────────────────────────
#  TEAM SHEET
# ─────────────────────────────────────────────

def build_team_sheet(wb):
    ws = wb.create_sheet("Team_Data")
    ws.sheet_view.showGridLines = False

    headers = ["#", "Name", "Track", "Modules / Assignment", "ENV"]
    widths  = [  5,    20,      30,              40,             8]
    n_cols  = len(headers)

    track_colors = {
        "DSP Manual":     "D6E4FF",
        "DSP Automation": "D9F7BE",
        "SSA":            "EFDBFF",
        "Upload":         "FFF7E6",
    }

    # ── Title banner ──────────────────────────────────────────────────────
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=n_cols)
    t = ws["A1"]
    t.value     = f"Team Roster  |  {MODULE_MONTH}"
    t.fill      = fill(C["hdr_dark"])
    t.font      = font(bold=True, color="22C55E", size=14)
    t.alignment = align(h="center")
    ws.row_dimensions[1].height = 28

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=n_cols)
    s = ws["A2"]
    s.value     = "Full team assignments for DSP Manual, DSP Automation, SSA, and Upload tracks."
    s.fill      = fill("1A1F2E")
    s.font      = font(italic=True, color="8892A4", size=10)
    s.alignment = align(h="center")
    ws.row_dimensions[2].height = 16

    ws.freeze_panes = "A4"

    def _env_banner(row, label, tag_color):
        ws.merge_cells(start_row=row, start_column=1,
                       end_row=row, end_column=n_cols)
        c = ws.cell(row=row, column=1, value=f"  ▶  {label}")
        c.fill      = fill(tag_color)
        c.font      = font(bold=True, size=11, color="000000")
        c.alignment = align(h="left")
        ws.row_dimensions[row].height = 22
        return row + 1

    def _col_header(row):
        apply_header_row(ws, row, headers, widths, C["hdr_team"])
        ws.row_dimensions[row].height = 20
        return row + 1

    def _write_members(members, start_row, seq_offset=0):
        for i, (name, track, sg, ssa_module, env) in enumerate(members):
            r = start_row + i
            band = next((v for k, v in track_colors.items() if k in track), C["white"])
            # Build a readable assignment string
            if sg and ssa_module:
                assignment = f"{sg} ({env})  /  {ssa_module}"
            elif sg:
                assignment = f"{sg} ({env})" if env else sg
            elif ssa_module:
                assignment = ssa_module
            else:
                assignment = ""
            for col_idx, val in enumerate([seq_offset + i + 1, name, track, assignment, env], start=1):
                cell = ws.cell(row=r, column=col_idx, value=val)
                cell.fill      = fill(band)
                cell.font      = font(size=10)
                cell.alignment = align()
                cell.border    = thin_border()
            ws.row_dimensions[r].height = 18
        return start_row + len(members)

    # ── Split by ENV ───────────────────────────────────────────────────────
    pt_members    = [(n, t, sg, m, e) for n, t, sg, m, e in INIT_TEAM if e == "PT"]
    uat_members   = [(n, t, sg, m, e) for n, t, sg, m, e in INIT_TEAM if e == "UAT"]
    other_members = [(n, t, sg, m, e) for n, t, sg, m, e in INIT_TEAM if e not in ("PT", "UAT")]

    cur = 3

    # PT section
    cur = _env_banner(cur, "PT  —  Pre-Testing", "C5E8FF")
    cur = _col_header(cur)
    cur = _write_members(pt_members, cur, seq_offset=0)

    cur += 1  # gap row

    # UAT section
    cur = _env_banner(cur, "UAT  —  User Acceptance Testing", "FFE8B2")
    cur = _col_header(cur)
    cur = _write_members(uat_members, cur, seq_offset=len(pt_members))

    # Other section (SSA/Upload with no env)
    if other_members:
        cur += 1
        cur = _env_banner(cur, "SSA / No Specific ENV", "EFDBFF")
        cur = _col_header(cur)
        cur = _write_members(other_members, cur, seq_offset=len(pt_members) + len(uat_members))

    ws.sheet_properties.tabColor = "B7860B"
    return ws

# ─────────────────────────────────────────────
#  SUMMARY / DASHBOARD SHEET
#  References the single E2E_Tracker sheet
# ─────────────────────────────────────────────

def build_summary_sheet(wb, tracker_ws):
    """Build Summary_Dashboard using row anchors stored on tracker_ws."""
    a = tracker_ws._tracker_anchors
    s_dsp = a["status_col_dsp"]    # G
    s_ssa = a["status_col_ssa"]    # H
    e_col = a["env_col"]           # D
    sheet = "E2E_Tracker"

    ws = wb.create_sheet("Summary_Dashboard")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = "22C55E"

    # ── Title ──────────────────────────────────────────
    ws.merge_cells("A1:H1")
    t = ws["A1"]
    t.value     = f"DSP & SSA — E2E Testing Summary Dashboard  |  {MODULE_MONTH}"
    t.fill      = fill(C["hdr_dark"])
    t.font      = font(bold=True, color="22C55E", size=15)
    t.alignment = align(h="center")
    ws.row_dimensions[1].height = 32

    ws.merge_cells("A2:H2")
    s = ws["A2"]
    s.value = (
        f"PT Manual: {DEAL_PT_MANUAL}  |  PT Auto: {DEAL_PT_AUTO}  |  "
        f"UAT Manual: {DEAL_UAT_MANUAL}  |  UAT Auto: {DEAL_UAT_AUTO}"
    )
    s.fill      = fill("1A1F2E")
    s.font      = font(italic=True, color="8892A4", size=10)
    s.alignment = align(h="center")
    ws.row_dimensions[2].height = 18

    # ── KPI header ────────────────────────────────────
    kpi_headers = ["Section", "Total", "Passed", "Completed",
                   "In Progress", "Failed/Blocked", "Not Started", "% Done"]
    kpi_widths  = [30, 10, 10, 12, 13, 16, 13, 14]

    KPI_HDR_ROW = 4
    for col_i, (hdr, w) in enumerate(zip(kpi_headers, kpi_widths), start=1):
        cell = ws.cell(row=KPI_HDR_ROW, column=col_i, value=hdr)
        cell.fill      = fill(C["hdr_summary"])
        cell.font      = font(bold=True, color="FFFFFF", size=10)
        cell.alignment = align(h="center")
        cell.border    = thin_border()
        ws.column_dimensions[get_column_letter(col_i)].width = w
    ws.row_dimensions[KPI_HDR_ROW].height = 22

    # ── KPI rows — COUNTIFS into E2E_Tracker ──────────
    # Each entry: (label, s_col, e_col_or_None, env_filter_or_None, first_row, last_row)
    kpi_defs = [
        ("DSP Manual — PT",  s_dsp, e_col, "PT",  a["manual_pt_first"],  a["manual_pt_last"]),
        ("DSP Manual — UAT", s_dsp, e_col, "UAT", a["manual_uat_first"], a["manual_uat_last"]),
        ("DSP Auto — PT",    s_dsp, e_col, "PT",  a["auto_pt_first"],    a["auto_pt_last"]),
        ("DSP Auto — UAT",   s_dsp, e_col, "UAT", a["auto_uat_first"],   a["auto_uat_last"]),
        ("SSA / GenAI",      s_ssa, None,  None,  a["ssa_first"],        a["ssa_last"]),
    ]

    def cif(sc, f, l, status_val, ec=None, env_val=None):
        """Build a COUNTIFS formula string."""
        sc_range = f"'{sheet}'!{sc}{f}:{sc}{l}"
        if ec and env_val:
            ec_range = f"'{sheet}'!{ec}{f}:{ec}{l}"
            if status_val:
                return (f"=COUNTIFS({ec_range},\"{env_val}\","
                        f"{sc_range},\"{status_val}\")")
            else:
                # total: count non-blank env rows
                return f"=COUNTIFS({ec_range},\"{env_val}\")"
        else:
            if status_val:
                return f"=COUNTIF({sc_range},\"{status_val}\")"
            else:
                return f"=COUNTA({sc_range})"

    for offset, (label, sc, ec, env_val, first, last) in enumerate(kpi_defs):
        r = KPI_HDR_ROW + 1 + offset
        ws.row_dimensions[r].height = 20
        row_bg = C["light_gray"] if offset % 2 == 0 else C["white"]

        # Label
        lc = ws.cell(row=r, column=1, value=label)
        lc.fill = fill(row_bg); lc.font = font(bold=True, size=10)
        lc.border = thin_border(); lc.alignment = align()

        total_f     = cif(sc, first, last, None,             ec, env_val)
        passed_f    = cif(sc, first, last, "Passed",         ec, env_val)
        completed_f = cif(sc, first, last, "Completed",      ec, env_val)
        inp_f       = cif(sc, first, last, "In Progress",    ec, env_val)
        # Failed/Blocked requires two COUNTIFS summed
        if ec and env_val:
            ec_r = f"'{sheet}'!{ec}{first}:{ec}{last}"
            sc_r = f"'{sheet}'!{sc}{first}:{sc}{last}"
            failed_f = (
                f"=COUNTIFS({ec_r},\"{env_val}\",{sc_r},\"Failed\")"
                f"+COUNTIFS({ec_r},\"{env_val}\",{sc_r},\"Blocked\")"
                f"+COUNTIFS({ec_r},\"{env_val}\",{sc_r},\"Connectivity Failing\")"
            )
            notst_f = (
                f"=COUNTIFS({ec_r},\"{env_val}\",{sc_r},\"\")"
                f"+COUNTIFS({ec_r},\"{env_val}\",{sc_r},\"Not Started\")"
            )
        else:
            sc_r = f"'{sheet}'!{sc}{first}:{sc}{last}"
            failed_f = (
                f"=COUNTIF({sc_r},\"Failed\")"
                f"+COUNTIF({sc_r},\"Blocked\")"
                f"+COUNTIF({sc_r},\"Connectivity Failing\")"
            )
            notst_f = (
                f"=COUNTIF({sc_r},\"\")"
                f"+COUNTIF({sc_r},\"Not Started\")"
            )

        total_ref = f"B{r}"
        pct_f = f"=IF({total_ref}=0,0,ROUND((C{r}+D{r})/{total_ref}*100,1))"

        col_data = [
            (total_f,     None),
            (passed_f,    C["passed"]),
            (completed_f, C["completed"]),
            (inp_f,       C["in_progress"]),
            (failed_f,    C["failed"]),
            (notst_f,     C["not_started"]),
            (pct_f,       "E9F5E9"),
        ]
        for col_i, (formula, bg) in enumerate(col_data, start=2):
            c = ws.cell(row=r, column=col_i, value=formula)
            c.fill      = fill(bg if bg else row_bg)
            c.font      = font(size=10, bold=(col_i == 8), color=("276221" if col_i == 8 else "000000"))
            c.alignment = align(h="center")
            c.border    = thin_border()
        ws.cell(row=r, column=8).number_format = '0.0"%"'

    # Data-bar on % Done (col H)
    pct_range = f"H{KPI_HDR_ROW + 1}:H{KPI_HDR_ROW + len(kpi_defs)}"
    ws.conditional_formatting.add(
        pct_range,
        DataBarRule(start_type="num", start_value=0,
                    end_type="num", end_value=100,
                    color="22C55E"),
    )

    # ── Legend ────────────────────────────────────────
    leg_row = KPI_HDR_ROW + len(kpi_defs) + 3
    ws.merge_cells(f"A{leg_row}:H{leg_row}")
    lh = ws[f"A{leg_row}"]
    lh.value = "Status Colour Legend"
    lh.fill  = fill(C["hdr_dark"]); lh.font = font(bold=True, color="FFFFFF", size=11)
    lh.alignment = align(h="center")
    ws.row_dimensions[leg_row].height = 22

    legend_items = [
        ("Passed",               C["passed"],     "276221"),
        ("Completed",            C["completed"],  "276221"),
        ("In Progress",          C["in_progress"],"7D5A00"),
        ("Failed",               C["failed"],     "820014"),
        ("Blocked",              C["blocked"],    "820014"),
        ("Connectivity Failing", C["conn_fail"],  "9E006B"),
        ("Not Started",          C["not_started"],"595959"),
    ]
    for i, (lbl, bg, fg) in enumerate(legend_items):
        col = (i % 4) * 2 + 1
        row = leg_row + 1 + (i // 4)
        c = ws.cell(row=row, column=col, value=lbl)
        c.fill = fill(bg); c.font = font(bold=True, color=fg, size=10)
        c.alignment = align(h="center"); c.border = thin_border()
        ws.merge_cells(start_row=row, start_column=col,
                       end_row=row, end_column=col + 1)
        ws.row_dimensions[row].height = 20

    ws.freeze_panes = "A4"
    return ws

# ─────────────────────────────────────────────
#  INSTRUCTIONS SHEET
# ─────────────────────────────────────────────

def build_instructions_sheet(wb):
    ws = wb.create_sheet("How_To_Use")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = "F59E0B"
    ws.column_dimensions["A"].width = 80

    lines = [
        ("DSP & SSA E2E Tracker — How To Use", "title"),
        ("", "blank"),
        ("SHEET OVERVIEW", "section"),
        ("• E2E_Tracker       — Single combined sheet: DSP Manual (PT+UAT), DSP Auto (PT+UAT), SSA/GenAI.", "body"),
        ("• Summary_Dashboard — Live KPI table with COUNTIFS formulas + % Done progress bars.", "body"),
        ("• Team_Data         — Reference roster of all team members and their assignments.", "body"),
        ("", "blank"),
        ("DEAL IDs — MAY 2026 RELEASE", "section"),
        (f"  PT  Manual  → {DEAL_PT_MANUAL}", "body"),
        (f"  PT  Auto    → {DEAL_PT_AUTO}", "body"),
        (f"  UAT Manual  → {DEAL_UAT_MANUAL}", "body"),
        (f"  UAT Auto    → {DEAL_UAT_AUTO}", "body"),
        ("", "blank"),
        ("EDITING DATA", "section"),
        ("• Scroll down the E2E_Tracker sheet — sections are clearly labelled with dark banners.", "body"),
        ("• Status, ENV, and SG columns have dropdown lists — click the cell to see the arrow.", "body"),
        ("• Statuses: Not Started / In Progress / Completed / Passed / Failed / Blocked / Connectivity Failing", "body"),
        ("• ENV dropdown: PT (Pre-Testing), UAT (User Acceptance Testing).", "body"),
        ("• SG dropdown: SI, AMS, BPMS, IMS.", "body"),
        ("• 10 empty buffer rows are pre-styled at the bottom of each env block for new entries.", "body"),
        ("", "blank"),
        ("COLOUR CODING", "section"),
        ("• PT rows  — Light blue background.", "body"),
        ("• UAT rows — Light amber background.", "body"),
        ("• Status cells are automatically colour-coded via conditional formatting.", "body"),
        ("", "blank"),
        ("SUMMARY DASHBOARD", "section"),
        ("• Uses COUNTIFS formulas pointing at exact row ranges in E2E_Tracker.", "body"),
        ("• % Done = (Passed + Completed) / Total × 100, shown with a green data-bar.", "body"),
        ("• Summary refreshes automatically — no manual update needed.", "body"),
        ("", "blank"),
        ("TIPS", "section"),
        ("• Use Ctrl+F to search within the E2E_Tracker sheet.", "body"),
        ("• Don't rename the E2E_Tracker sheet — the Summary formulas reference it by name.", "body"),
        ("• Save as .xlsx to preserve all formatting, dropdowns, and conditional formatting.", "body"),
    ]

    style_map = {
        "title":   (C["hdr_dark"], True, "22C55E", 16),
        "section": (C["hdr_summary"], True, "FFFFFF", 11),
        "body":    (C["white"], False, "000000", 10),
        "blank":   (C["white"], False, "000000", 10),
    }

    for row_i, (text, style) in enumerate(lines, start=1):
        cell = ws.cell(row=row_i, column=1, value=text)
        bg, bold, fg, size = style_map[style]
        cell.fill      = fill(bg)
        cell.font      = font(bold=bold, color=fg, size=size)
        cell.alignment = align(h="left" if style != "title" else "center", wrap=True)
        ws.row_dimensions[row_i].height = 22 if style == "title" else 18

    return ws

# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────

def main():
    wb = Workbook()
    wb.remove(wb.active)   # remove default blank sheet

    print(f"Building workbook: {FILE_NAME}")

    # 1. Build tracker first (populates _tracker_anchors)
    tracker_ws = build_single_tracker_sheet(wb)

    # 2. Summary references tracker anchors
    build_summary_sheet(wb, tracker_ws)

    # 3. Supporting sheets
    build_team_sheet(wb)
    build_instructions_sheet(wb)

    # Open on Summary by default
    wb.active = wb["Summary_Dashboard"]

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), FILE_NAME)
    wb.save(out_path)
    print(f"✓  Saved → {out_path}")
    print()
    print("  Sheets created:")
    for s in wb.sheetnames:
        print(f"    • {s}")

if __name__ == "__main__":
    main()
