import { createClient } from '@supabase/supabase-js';

const supabaseUrl  = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey  = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.warn(
    '[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY is not set. ' +
    'Create a .env file at the project root with these values.'
  );
}

// Generated by GitHub Copilot
// flowType: 'implicit' is required so invite/signup confirmation emails embed
// the token in the URL hash (#access_token=...&type=signup), which useAuth.js
// detects to show the SetPasswordScreen. The default PKCE flow uses a ?code=
// query param that the existing hash-based detection cannot read.
export const supabase = createClient(supabaseUrl ?? '', supabaseKey ?? '', {
  auth: {
    flowType: 'implicit',
    detectSessionInUrl: true,
  },
});
