import { Space, Typography } from 'antd';
import { AlertTriangle, CheckCircle } from 'lucide-react';
import { fmtDate } from '../../utils/helpers.jsx';

const { Text } = Typography;

// Generated by GitHub Copilot
export default function ModuleSaveBar({ moduleName, isDirty, lastSaved }) {
  return (
    <div
      className={isDirty ? 'module-save-bar-dirty' : 'module-save-bar-clean'}
      style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 16px', borderRadius: 8, marginBottom: 12 }}
    >
      <span aria-live="polite" aria-atomic="true" style={{ display: 'contents' }}>
        {isDirty ? (
          <>
            <AlertTriangle size={14} color="var(--warning)" aria-hidden="true" />
            <Text style={{ fontSize: 12, color: 'var(--warning)' }}>
              Unsaved changes in <strong>{moduleName}</strong>
            </Text>
          </>
        ) : (
          <>
            <CheckCircle size={14} color="var(--accent)" aria-hidden="true" />
            <Text style={{ fontSize: 12, color: 'var(--accent)' }}>
              <strong>{moduleName}</strong> — all changes saved
            </Text>
          </>
        )}
      </span>
      {lastSaved && (
        <Text type="secondary" style={{ fontSize: 11 }}>
          Last saved: {fmtDate(lastSaved)}
        </Text>
      )}
    </div>
  );
}
