// Generated by GitHub Copilot
/**
 * AppLogo
 * CSS/SVG recreation of the MyISP Insight StatusPlatform logo.
 * 4-square grid: orange+chart, dark+bar, orange+person, green+dot.
 * Fully theme-safe — no white background, renders on any dark or light theme.
 *
 * @param {number}  size        - overall icon size in px (default 34)
 * @param {boolean} showName    - show "MyISP Insight" wordmark next to icon
 * @param {string}  nameColor   - CSS color for the "Insight StatusPlatform" text
 */
export default function AppLogo({ size = 34, showName = false, nameColor = 'var(--text-primary)' }) {
  const gap  = Math.round(size * 0.06);
  const tile = Math.round((size - gap) / 2);
  const r    = Math.round(tile * 0.28);

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: Math.round(size * 0.32), flexShrink: 0 }}>
      {/* Icon grid */}
      <svg
        width={size}
        height={size}
        viewBox={`0 0 ${size} ${size}`}
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-label="MyISP Insight Status Platform logo"
        role="img"
      >
        {/* Top-left: orange + trend line */}
        <rect x={0} y={0} width={tile} height={tile} rx={r} fill="url(#tl-grad)" />
        <polyline
          points={`${tile*0.15},${tile*0.65} ${tile*0.38},${tile*0.42} ${tile*0.6},${tile*0.55} ${tile*0.85},${tile*0.28}`}
          stroke="white" strokeWidth={tile*0.1} strokeLinecap="round" strokeLinejoin="round"
        />

        {/* Top-right: charcoal + bar chart */}
        <rect x={tile + gap} y={0} width={tile} height={tile} rx={r} fill="url(#tr-grad)" />
        <rect x={tile+gap + tile*0.2}  y={tile*0.52} width={tile*0.18} height={tile*0.34} rx={1} fill="white" opacity="0.9" />
        <rect x={tile+gap + tile*0.44} y={tile*0.35} width={tile*0.18} height={tile*0.51} rx={1} fill="white" opacity="0.9" />
        <rect x={tile+gap + tile*0.68} y={tile*0.18} width={tile*0.18} height={tile*0.68} rx={1} fill="white" opacity="0.9" />

        {/* Bottom-left: orange + person */}
        <rect x={0} y={tile + gap} width={tile} height={tile} rx={r} fill="url(#bl-grad)" />
        <circle cx={tile*0.5} cy={tile+gap + tile*0.34} r={tile*0.18} fill="white" opacity="0.95" />
        <path
          d={`M ${tile*0.18},${tile+gap + tile*0.82} Q ${tile*0.18},${tile+gap + tile*0.56} ${tile*0.5},${tile+gap + tile*0.56} Q ${tile*0.82},${tile+gap + tile*0.56} ${tile*0.82},${tile+gap + tile*0.82}`}
          stroke="white" strokeWidth={tile*0.11} strokeLinecap="round" fill="none" opacity="0.95"
        />

        {/* Bottom-right: dark green + status dot */}
        <rect x={tile + gap} y={tile + gap} width={tile} height={tile} rx={r} fill="url(#br-grad)" />
        <circle cx={tile+gap + tile*0.5} cy={tile+gap + tile*0.5} r={tile*0.22} fill="#a3e635" />
        <circle cx={tile+gap + tile*0.5} cy={tile+gap + tile*0.5} r={tile*0.22} fill="url(#dot-shine)" />

        {/* Spark lines top-right of grid */}
        <line x1={size*0.72} y1={size*0.04} x2={size*0.78} y2={size*0.0} stroke="#f97316" strokeWidth="1.5" strokeLinecap="round" />
        <line x1={size*0.81} y1={size*0.02} x2={size*0.87} y2={size*0.08} stroke="#f97316" strokeWidth="1.5" strokeLinecap="round" />

        <defs>
          <linearGradient id="tl-grad" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#ffb347" />
            <stop offset="100%" stopColor="#f97316" />
          </linearGradient>
          <linearGradient id="tr-grad" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#555" />
            <stop offset="100%" stopColor="#333" />
          </linearGradient>
          <linearGradient id="bl-grad" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#fb923c" />
            <stop offset="100%" stopColor="#ea580c" />
          </linearGradient>
          <linearGradient id="br-grad" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#2d6a35" />
            <stop offset="100%" stopColor="#14532d" />
          </linearGradient>
          <radialGradient id="dot-shine" cx="35%" cy="30%" r="60%">
            <stop offset="0%" stopColor="white" stopOpacity="0.4" />
            <stop offset="100%" stopColor="white" stopOpacity="0" />
          </radialGradient>
        </defs>
      </svg>

      {/* Optional wordmark */}
      {showName && (
        <div style={{ display: 'flex', flexDirection: 'column', lineHeight: 1.15 }}>
          <span style={{ fontSize: size * 0.47, fontWeight: 800, letterSpacing: -0.3, color: nameColor }}>
            <span style={{ color: '#f97316' }}>MyISP</span>Insight
          </span>
          <span style={{ fontSize: size * 0.32, fontWeight: 500, color: 'var(--text-muted)', letterSpacing: 0.2 }}>
            StatusPlatform
          </span>
        </div>
      )}
    </div>
  );
}
