// Generated by GitHub Copilot
import React, { useState } from 'react';
import { Popover } from 'antd';
import { Palette, LogOut } from 'lucide-react';

/**
 * ProfileDropdown
 * Card-style profile popover inspired by the tett.html design.
 * Shows a monogram avatar, user name, role badge, role pills, role-switcher
 * list, theme picker trigger, and sign-out — all theme-aware via CSS variables.
 *
 * @param {string}      displayName
 * @param {string}      role         – effective role key (may be viewAsRole)
 * @param {string}      actualRole   – real (un-previewed) role key
 * @param {string[]}    allowedRoles – all role keys the user has been granted
 * @param {string|null} viewAsRole   – active preview role, or null
 * @param {object}      ROLES        – flat role config map from constants
 * @param {Function}    onRoleSwitch(key) – called when a role row is clicked
 * @param {Function}    onTheme      – opens theme picker modal
 * @param {Function}    onSignOut    – signs the user out
 */
export default function ProfileDropdown({
  displayName,
  role,
  actualRole,
  allowedRoles,
  viewAsRole,
  ROLES,
  onRoleSwitch,
  onTheme,
  onSignOut,
}) {
  const [open, setOpen] = useState(false);

  const rc      = ROLES[role] || ROLES.viewer;
  const initial = (displayName || '?')[0].toUpperCase();

  /* ─── hover helper ─── */
  const hoverOn  = (e) => { e.currentTarget.style.background = 'var(--bg-card-hover, rgba(255,255,255,0.05))'; };
  const hoverOff = (e) => { e.currentTarget.style.background = 'transparent'; };

  /* ─── Panel content ─── */
  const panel = (
    <div style={{ width: 276, fontFamily: 'inherit' }}>

      {/* ── Header: avatar + name + badge ── */}
      <div style={{ textAlign: 'center', padding: '22px 20px 16px' }}>
        {/* Monogram circle */}
        <div style={{
          width: 64, height: 64,
          background: 'linear-gradient(135deg, var(--accent) 0%, var(--accent-dim) 100%)',
          borderRadius: '50%',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          margin: '0 auto 12px',
          color: 'var(--bg-base)',
          fontSize: 26, fontWeight: 800,
          boxShadow: '0 4px 18px var(--accent-glow)',
          userSelect: 'none',
        }}>
          {initial}
        </div>

        {/* Display name */}
        <div style={{
          fontSize: 15, fontWeight: 700,
          color: 'var(--text-primary)',
          marginBottom: 6,
          wordBreak: 'break-word',
        }}>
          {displayName || 'User'}
        </div>

        {/* Role badge */}
        <span style={{
          display: 'inline-block',
          background: `${rc.color}18`,
          color: rc.color,
          border: `1px solid ${rc.color}40`,
          borderRadius: 20,
          padding: '3px 14px',
          fontSize: 11, fontWeight: 700,
          textTransform: 'uppercase', letterSpacing: 0.6,
        }}>
          {rc.label}{viewAsRole ? ' (preview)' : ''}
        </span>
      </div>

      {/* ── Your Role pills ── */}
      {allowedRoles && allowedRoles.length > 0 && (
        <div style={{ padding: '0 16px 14px' }}>
          <div style={{
            fontSize: 10, fontWeight: 800, color: 'var(--text-muted)',
            textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8,
          }}>
            Your Role
          </div>
          <div style={{ display: 'flex', gap: 6 }}>
            {allowedRoles.map((r) => {
              const rrc = ROLES[r] ?? ROLES.viewer;
              const isActive = role === r;
              return (
                <div key={r} style={{
                  flex: 1, padding: '7px 4px', borderRadius: 8,
                  textAlign: 'center', fontSize: 11,
                  fontWeight: isActive ? 700 : 500,
                  background: isActive ? `${rrc.color}15` : 'var(--bg-surface)',
                  border: `1px solid ${isActive ? rrc.color : 'var(--border)'}`,
                  color: isActive ? rrc.color : 'var(--text-secondary)',
                  cursor: 'default',
                  transition: 'all 0.15s',
                }}>
                  {rrc.label}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Divider ── */}
      <div style={{ borderTop: '1px solid var(--border-subtle)' }} />

      {/* ── Switch Role View ── */}
      {allowedRoles && allowedRoles.length > 1 && (
        <>
          <div style={{
            padding: '10px 16px 4px',
            fontSize: 10, fontWeight: 800, color: 'var(--text-muted)',
            textTransform: 'uppercase', letterSpacing: 1,
          }}>
            {actualRole === 'admin' ? 'Switch Role View' : 'Switch Role'}
          </div>

          {(actualRole === 'admin'
            ? ['admin', 'tl', 'tester', 'viewer']
            : allowedRoles
          ).map((r) => {
            const rrc = ROLES[r] ?? ROLES.viewer;
            const RIcon = rrc.icon;
            const isCurrentActual = r === actualRole && !viewAsRole;
            const isActive = viewAsRole === r || isCurrentActual;
            return (
              <div
                key={r}
                role="button"
                tabIndex={0}
                aria-pressed={isActive}
                onClick={() => { if (!isCurrentActual) onRoleSwitch(r); setOpen(false); }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    if (!isCurrentActual) onRoleSwitch(r);
                    setOpen(false);
                  }
                }}
                style={{
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                  padding: '9px 16px',
                  cursor: isCurrentActual ? 'default' : 'pointer',
                  transition: 'background 0.15s',
                }}
                onMouseEnter={isCurrentActual ? undefined : hoverOn}
                onMouseLeave={isCurrentActual ? undefined : hoverOff}
              >
                <span style={{
                  display: 'flex', alignItems: 'center', gap: 10,
                  color: isActive ? rrc.color : 'var(--text-secondary)',
                  fontWeight: isActive ? 700 : 400,
                  fontSize: 13,
                }}>
                  <RIcon size={14} />
                  {rrc.label}
                </span>
                {isCurrentActual && (
                  <span style={{
                    background: 'rgba(56,161,105,0.12)', color: '#38a169',
                    fontSize: 10, padding: '2px 8px', borderRadius: 6, fontWeight: 700,
                  }}>
                    Current
                  </span>
                )}
                {isActive && !isCurrentActual && (
                  <span style={{
                    background: 'rgba(237,137,54,0.12)', color: '#ed8936',
                    fontSize: 10, padding: '2px 8px', borderRadius: 6, fontWeight: 700,
                  }}>
                    Active
                  </span>
                )}
              </div>
            );
          })}

          <div style={{ borderTop: '1px solid var(--border-subtle)', margin: '6px 0 0' }} />
        </>
      )}

      {/* ── Theme Settings ── */}
      <div
        role="button"
        tabIndex={0}
        aria-label="Open theme settings"
        onClick={() => { onTheme(); setOpen(false); }}
        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onTheme(); setOpen(false); } }}
        style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 16px', cursor: 'pointer', transition: 'background 0.15s' }}
        onMouseEnter={hoverOn}
        onMouseLeave={hoverOff}
      >
        <Palette size={14} color="var(--accent)" />
        <span style={{ fontSize: 13, color: 'var(--text-primary)', fontWeight: 500 }}>Theme Settings</span>
      </div>

      {/* ── Sign out ── */}
      <div
        role="button"
        tabIndex={0}
        aria-label="Sign out"
        onClick={() => { onSignOut(); setOpen(false); }}
        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSignOut(); setOpen(false); } }}
        style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 16px 18px', cursor: 'pointer', transition: 'background 0.15s' }}
        onMouseEnter={hoverOn}
        onMouseLeave={hoverOff}
      >
        <LogOut size={14} color="#f87171" />
        <span style={{ fontSize: 13, color: '#f87171', fontWeight: 500 }}>Sign out</span>
      </div>

    </div>
  );

  /* ─── Trigger button — orbital profile pill ─── */
  const trigger = (
    <div
      role="button"
      tabIndex={0}
      aria-haspopup="dialog"
      aria-expanded={open}
      aria-label="Profile options"
      style={{
        display: 'flex', alignItems: 'center', gap: 8,
        padding: '3px 12px 3px 3px', borderRadius: 50, cursor: 'pointer',
        background: 'rgba(255,255,255,0.06)',
        border: `1px solid ${rc.color}40`,
        transition: 'background 0.15s, border-color 0.15s',
        boxShadow: `0 2px 12px ${rc.color}22`,
      }}
      onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.1)'; }}
      onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.06)'; }}
    >
      {/* Orbital spinner + monogram */}
      <div style={{ position: 'relative', width: 30, height: 30, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
        <div style={{
          position: 'absolute', inset: 0,
          borderRadius: '50%',
          border: '2px solid transparent',
          borderTop: `2px solid ${rc.color}`,
          borderRight: `2px solid ${rc.color}`,
          animation: 'ribbon-orb-spin 3s linear infinite',
        }} />
        <div style={{
          width: 22, height: 22, borderRadius: '50%', zIndex: 2,
          background: `linear-gradient(135deg, ${rc.color}cc 0%, ${rc.color} 100%)`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          color: '#fff', fontSize: 11, fontWeight: 800,
          boxShadow: `0 1px 6px ${rc.color}55`,
          userSelect: 'none',
        }}>
          {initial}
        </div>
      </div>

      {/* Name + role label */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
        <div style={{
          color: 'var(--text-primary)', fontSize: 12, fontWeight: 600, lineHeight: 1.3,
          maxWidth: 140, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
        }} title={displayName}>
          {displayName || 'User'}
        </div>
        <span style={{
          display: 'inline-block', fontSize: 9, fontWeight: 700, lineHeight: '15px',
          padding: '0 6px', borderRadius: 20,
          color: rc.color, background: `${rc.color}18`, border: `1px solid ${rc.color}38`,
          letterSpacing: 0.4, textTransform: 'uppercase',
        }}>
          {rc.label}{viewAsRole ? ' (preview)' : ''}
        </span>
      </div>
    </div>
  );

  return (
    <Popover
      open={open}
      onOpenChange={setOpen}
      trigger="click"
      placement="bottomRight"
      content={panel}
      arrow={false}
      overlayInnerStyle={{ padding: 0, borderRadius: 16, overflow: 'hidden', border: '1px solid var(--border)' }}
      overlayStyle={{ zIndex: 1050 }}
    >
      {trigger}
    </Popover>
  );
}
