export const LEAD_NAME_OPTIONS = [
  { value: 'srinivasan.selvam',     label: 'Srinivasan Selvam' },
  { value: 'pramod.kasam',          label: 'Pramod Kasam' },
  { value: 'archana.a.nagarajan',   label: 'Archana Nagarajan' },
  { value: 'aqil.patnam',           label: 'Aqil Patnam' },
  { value: 'd.sampathkumar',        label: 'Dhaarani Sampathkumar' },
  { value: 'devika.kalaivanan',     label: 'Devika Kalaivanan' },
  { value: 'himanshu.m.jain',       label: 'Himanshu Jain' },
  { value: 'hajara.ayyubkhan',      label: 'Hajara Ayyubkhan' },
  { value: 'deepti.prakash',        label: 'Deepti Prakash' },
  { value: 'j.damodaran',           label: 'J. Damodaran' },
  { value: 'leena.a.das',           label: 'Leena Das' },
  { value: 'vishnu.ramalingam',     label: 'Vishnu Ramalingam' },
  { value: 'pirtheebaa.krishnan',   label: 'Pirtheebaa Krishnan' },
  { value: 'r.kalia.moorthy',       label: 'Rajarajeswari Kalia Moorthy' },
  { value: 'k.b.selvamani',         label: 'Kavichandrika Selvamani' },
  { value: 'nandini.baskaran',      label: 'Nandini Baskaran' },
  { value: 'anand.b.gadad',         label: 'Anand B Gadad' },
  { value: 'shini.vv',              label: 'Shini V V' },
];
