import React, { useState, useEffect } from 'react';
import {
  Layout, Menu, Space, Badge, ConfigProvider, FloatButton, Modal, Spin,
  Typography, Tag, Button, Tooltip, Select, Input, theme as antTheme, Dropdown, Form,
} from 'antd';
import {
  Home, Monitor, Shield, Users, FileText, Activity,
  LayoutDashboard, Calendar, Search, Copy, Save, Download,
  AlertTriangle, LogOut, UserCog, Lock,
  ShieldCheck, KeyRound, Sun, Moon, Palette,
} from 'lucide-react';

// Auth + data hooks
import { useAuth }      from './hooks/useAuth.js';
import { useMonthData } from './hooks/useMonthData.js';

// Components
import LoginPage        from './components/auth/LoginPage.jsx';
import ModulePicker     from './components/ModulePicker.jsx';
import KTSessionsPage   from './components/KTSessionsPage.jsx';
import HomePage         from './components/home/HomePage.jsx';
import DSPSheet         from './components/sheets/DSPSheet.jsx';
import SSASheet         from './components/sheets/SSASheet.jsx';
import TeamSheet        from './components/sheets/TeamSheet.jsx';
import ReportSheet      from './components/sheets/ReportSheet.jsx';
import ActivityLogSheet from './components/sheets/ActivityLogSheet.jsx';
import AccessSheet           from './components/sheets/AccessSheet.jsx';

// Utils
import { MONTH_OPTIONS, ROLES, ROLE_HIERARCHY, currentMonthKey } from './utils/constants.js';
import { toTSV, filterData }                     from './utils/helpers.jsx';

import './App.css';

const { Sider, Content, Header } = Layout;
const { Text } = Typography;

const DARK_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#fbbf24',
    colorBgBase:        '#0c0900',
    colorBgContainer:   'rgba(18,13,0,0.6)',
    colorBgElevated:    'rgba(26,18,0,0.85)',
    colorBorder:        'rgba(46,32,0,0.9)',
    colorText:          '#fef9ee',
    colorTextSecondary: '#a38b3a',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

const LIGHT_THEME = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary:       '#d97706',
    colorBgBase:        '#ffffff',
    colorBgContainer:   '#fafaf8',
    colorBgElevated:    '#fefefe',
    colorBorder:        'rgba(210,200,180,0.55)',
    colorText:          '#1a1209',
    colorTextSecondary: '#7a6040',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
const OCEAN_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#06b6d4',
    colorBgBase:        '#060d1a',
    colorBgContainer:   'rgba(7,16,32,0.65)',
    colorBgElevated:    'rgba(12,24,44,0.9)',
    colorBorder:        'rgba(14,32,64,0.9)',
    colorText:          '#e0f2fe',
    colorTextSecondary: '#4d7a9e',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
const VIOLET_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#a855f7',
    colorBgBase:        '#0d0614',
    colorBgContainer:   'rgba(18,8,25,0.65)',
    colorBgElevated:    'rgba(26,12,38,0.9)',
    colorBorder:        'rgba(42,16,64,0.9)',
    colorText:          '#f3e8ff',
    colorTextSecondary: '#9b6dca',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
const CARBON_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#f59e0b',
    colorBgBase:        '#111111',
    colorBgContainer:   'rgba(22,22,22,0.65)',
    colorBgElevated:    'rgba(32,32,32,0.9)',
    colorBorder:        'rgba(40,40,40,0.9)',
    colorText:          '#f5f5f5',
    colorTextSecondary: '#a3a3a3',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
const ROSE_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#f43f5e',
    colorBgBase:        '#100a0a',
    colorBgContainer:   'rgba(24,13,13,0.65)',
    colorBgElevated:    'rgba(34,18,18,0.9)',
    colorBorder:        'rgba(46,21,21,0.9)',
    colorText:          '#ffe4e8',
    colorTextSecondary: '#c4687d',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
const SLATE_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#38bdf8',
    colorBgBase:        '#0c1018',
    colorBgContainer:   'rgba(16,21,32,0.65)',
    colorBgElevated:    'rgba(22,30,46,0.9)',
    colorBorder:        'rgba(30,37,53,0.9)',
    colorText:          '#e0f2fe',
    colorTextSecondary: '#64748b',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
/** Maps data-theme key -> AntD ConfigProvider theme object */
const THEME_MAP = {
  'dark':        DARK_THEME,
  'dark-ocean':  OCEAN_THEME,
  'dark-violet': VIOLET_THEME,
  'dark-carbon': CARBON_THEME,
  'dark-rose':   ROSE_THEME,
  'dark-slate':  SLATE_THEME,
  'light':       LIGHT_THEME,
};

// Generated by GitHub Copilot
function SetPasswordScreen({ updatePassword, signOut, setActiveModule, email }) {
  const [saving, setSaving] = useState(false);
  const [done,   setDone]   = useState(false);
  const [form]              = Form.useForm();

  const handleSave = async ({ password }) => {
    setSaving(true);
    const { error } = await updatePassword(password);
    setSaving(false);
    if (error) {
      Modal.error({ title: 'Failed to set password', content: error.message });
      return;
    }
    setDone(true);
    // Sign out so user logs in fresh with their new password
    setTimeout(async () => {
      await signOut();
      setActiveModule(null);
    }, 2500);
  };

  return (
    <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-base)', backgroundImage: 'var(--mesh)' }}>
      <div style={{ width: 420, background: 'var(--bg-card)', backdropFilter: 'blur(20px)', borderRadius: 20, padding: '32px 28px', border: '1px solid var(--border)' }}>
        {done ? (
          <div style={{ textAlign: 'center', padding: '16px 0' }}>
            <div style={{ width: 56, height: 56, borderRadius: '50%', background: 'rgba(217,119,6,0.15)', border: '2px solid #d97706', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
              <Lock size={24} color="#d97706" />
            </div>
              <Text strong style={{ color: 'var(--text-primary)', fontSize: 18, display: 'block', marginBottom: 8 }}>Password saved!</Text>
            <Text type="secondary" style={{ fontSize: 13 }}>Signing you out… please log in with your new password.</Text>
          </div>
        ) : (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
              <div style={{ width: 36, height: 36, borderRadius: 8, background: 'rgba(217,119,6,0.1)', border: '1px solid rgba(217,119,6,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Lock size={18} color="#d97706" />
              </div>
              <div>
                  <Text strong style={{ color: 'var(--text-primary)', display: 'block', fontSize: 15 }}>Set New Password</Text>
                <Text type="secondary" style={{ fontSize: 12 }}>Choose a password to secure your account</Text>
              </div>
            </div>

            {/* Show which email account is being activated */}
            {email && (
                <div style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '10px 14px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 28, height: 28, borderRadius: '50%', background: '#fbbf24', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: 12, fontWeight: 700, color: '#0c0900' }}>
                  {email[0].toUpperCase()}
                </div>
                <div>
                  <Text type="secondary" style={{ fontSize: 10, display: 'block', lineHeight: 1.3 }}>Setting password for</Text>
                  <Text strong style={{ color: 'var(--text-primary)', fontSize: 12 }}>{email}</Text>
                </div>
              </div>
            )}

            <Form form={form} layout="vertical" requiredMark={false} onFinish={handleSave}>
              <Form.Item
                name="password"
                label={<Text style={{ color: 'var(--text-secondary)', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>New Password</Text>}
                rules={[{ required: true, message: 'Enter a password' }, { min: 8, message: 'At least 8 characters' }]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="var(--text-muted)" style={{ marginRight: 4 }} />} placeholder="Minimum 8 characters" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Form.Item
                name="confirm"
                label={<Text style={{ color: 'var(--text-secondary)', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>Confirm Password</Text>}
                dependencies={['password']}
                rules={[
                  { required: true, message: 'Please confirm your password' },
                  ({ getFieldValue }) => ({
                    validator(_, v) {
                      return !v || getFieldValue('password') === v ? Promise.resolve() : Promise.reject('Passwords do not match');
                    },
                  }),
                ]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="var(--text-muted)" style={{ marginRight: 4 }} />} placeholder="Re-enter password" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Button type="primary" htmlType="submit" size="large" loading={saving}
                style={{ width: '100%', height: 46, borderRadius: 9, background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)', border: 'none', fontWeight: 700, fontSize: 15, color: '#0c0900' }}>
                {saving ? 'Saving…' : 'Save Password & Continue'}
              </Button>
            </Form>
          </>
        )}
      </div>
    </div>
  );
}

function App() {
  const { user, profile, role: authRole, loading: authLoading, signIn, signOut, needsPasswordReset, updatePassword, allowedRoles } = useAuth();

  const [activeModule,  setActiveModule]  = useState(null); // null = picker, 'e2e' = dashboard
  const [activeTab,     setActiveTab]     = useState('home');
  const [searchQuery,   setSearchQuery]   = useState('');
  const [selectedMonth, setSelectedMonth] = useState(currentMonthKey());
  const [collapsed,     setCollapsed]     = useState(false);
  const [viewAsRole,    setViewAsRole]    = useState(null); // admin preview override
  const [currentTheme,  setCurrentTheme]  = useState(() => localStorage.getItem('theme') || 'dark');
  const [themeModalOpen, setThemeModalOpen] = useState(false);

  // ── Theme persistence ──────────────────────────────────────
  useEffect(() => {
    localStorage.setItem('theme', currentTheme);
    // Force light mode on the login / password-reset screens
    const effectiveTheme = !user ? 'light' : currentTheme;
    document.documentElement.setAttribute('data-theme', effectiveTheme);
  }, [currentTheme, user]);

  // ── Hash routing ──────────────────────────────────────────
  useEffect(() => {
    const h = window.location.hash.replace(/^#\//, '');
    if (h.startsWith('e2e/')) { setActiveModule('e2e'); setActiveTab(h.slice(4) || 'home'); }
    else if (h === 'kt')     setActiveModule('kt');
    else if (h === 'roles')  setActiveModule('rolesaccess');
  }, []);

  useEffect(() => {
    if      (activeModule === 'e2e')        window.location.hash = '/e2e/' + activeTab;
    else if (activeModule === 'kt')         window.location.hash = '/kt';
    else if (activeModule === 'rolesaccess') window.location.hash = '/roles';
    else                                    window.location.hash = '/';
  }, [activeModule, activeTab]);

  const {
    dspManual, setDspManual,
    dspAuto,   setDspAuto,
    ssaData,   setSsaData,
    teamData,  setTeamData,
    dirtyModules,
    lastSaved,
    saveModule,
    saveAllModules,
    loading: dataLoading,
  } = useMonthData(selectedMonth, user);

  const handleMonthChange = (newMonth) => {
    if (Object.values(dirtyModules).some(Boolean)) {
      Modal.confirm({
        title:     'Unsaved Changes',
        content:   'You have unsaved changes. Save before switching months?',
        okText:    'Save & Switch',
        cancelText:'Discard & Switch',
        onOk:    async () => { await saveAllModules(); setSelectedMonth(newMonth); setSearchQuery(''); },
        onCancel:() => { setSelectedMonth(newMonth); setSearchQuery(''); },
      });
    } else {
      setSelectedMonth(newMonth);
      setSearchQuery('');
    }
  };

  const handleExportJSON = () => {
    const payload = {
      month: selectedMonth, dspManual, dspAuto, ssaData, teamData,
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = 'e2e-' + selectedMonth + '.json'; a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    const dspCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Env',    dataIndex: 'env'    }, { title: 'SG',     dataIndex: 'sg'     },
      { title: 'Deal',   dataIndex: 'deal'   }, { title: 'Status', dataIndex: 'status' },
    ];
    const ssaCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Deal',   dataIndex: 'dealId' }, { title: 'Status', dataIndex: 'status' },
    ];
    const map = {
      dsp: { columns: dspCols, data: [...dspManual, ...dspAuto] },
      ssa: { columns: ssaCols, data: ssaData },
    };
    const target = map[activeTab] || map.dsp;
    navigator.clipboard.writeText(toTSV(target.columns, filterData(target.data, searchQuery))).catch(() => {});
  };

  if (authLoading) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-base)' }}>
        <Spin size="large" />
      </div>
    );
  }

  // ── Shared vars needed by standalone module headers ──
  const _sharedRole       = viewAsRole ?? authRole ?? 'viewer';
  const _sharedRoleConfig = ROLES[_sharedRole] || ROLES.viewer;
  const _sharedRoleIcon   = _sharedRoleConfig.icon;
  const _sharedName       = profile?.display_name || user?.email || '';
  const _actualRole       = authRole ?? 'viewer';

  // Shared profile dropdown menu items — used by KT, Roles & Access, and main app
  const _buildProfileMenu = (onSignOutCb) => [
    { type: 'group', label: _sharedName },
    {
      key: 'role-info',
      label: React.createElement('div', { style: { padding: '4px 0', pointerEvents: 'none' } },
        allowedRoles && allowedRoles.length > 0 && React.createElement('div', null,
          React.createElement('div', { style: { fontSize: 10, color: 'var(--text-secondary)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 } }, 'Your Role'),
          React.createElement('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 4 } },
            ...allowedRoles.map((r) => {
              const rc = ROLES[r] ?? ROLES.viewer;
              const RIcon = rc.icon;
              const isActive = _sharedRole === r;
              return React.createElement(Tag, {
                key: r,
                style: { background: isActive ? rc.bg : 'transparent', color: rc.color, border: `1px solid ${isActive ? rc.border : 'var(--border)'}`, fontSize: 11, margin: 0, fontWeight: isActive ? 700 : 400 },
              },
                React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
                  React.createElement(RIcon, { size: 10 }),
                  rc.label,
                  isActive && React.createElement('span', { style: { fontSize: 9, marginLeft: 2 } }, '●')
                )
              );
            })
          )
        )
      ),
    },
    { type: 'divider' },
    ...(allowedRoles && allowedRoles.length > 1 ? [
      { type: 'group', label: _actualRole === 'admin' ? 'Switch Role View' : 'Switch Role' },
      ...(_actualRole === 'admin' ? ['admin', 'tl', 'tester', 'viewer'] : allowedRoles).map((r) => {
        const rc = ROLES[r];
        const RIcon = rc.icon;
        const isCurrentActual = r === _actualRole && !viewAsRole;
        const isActive = viewAsRole === r || isCurrentActual;
        return {
          key: 'preview-' + r,
          label: React.createElement('div', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 } },
            React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 6, color: rc.color, fontWeight: isActive ? 700 : 400 } },
              React.createElement(RIcon, { size: 12 }), rc.label
            ),
            isCurrentActual
              ? React.createElement(Tag, { color: 'green', style: { margin: 0, fontSize: 10 } }, 'Current')
              : isActive ? React.createElement(Tag, { color: 'orange', style: { margin: 0, fontSize: 10 } }, 'Active') : null
          ),
          onClick: () => { if (isCurrentActual) return; setViewAsRole(viewAsRole === r ? null : r); },
        };
      }),
      { type: 'divider' },
    ] : []),
    { key: 'theme', label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 8 } },
        React.createElement(Palette, { size: 13, color: 'var(--accent)' }),
        'Theme Settings'
      ), onClick: () => setThemeModalOpen(true) },
    { type: 'divider' },
    { key: 'signout', label: React.createElement('span', { style: { color: '#f87171' } }, 'Sign out'), onClick: onSignOutCb },
  ];

  // Shared profile button avatar element
  const _profileAvatar = React.createElement('div', {
    role: 'button', tabIndex: 0, 'aria-label': 'Profile options',
    style: { display: 'flex', alignItems: 'center', gap: 10, padding: '5px 12px 5px 7px', borderRadius: 12, cursor: 'pointer', background: 'rgba(255,255,255,0.08)', border: `1px solid ${_sharedRoleConfig.color}40` },
  },
    React.createElement('div', { style: { width: 32, height: 32, borderRadius: '50%', flexShrink: 0, background: 'linear-gradient(135deg, #fbbf24, #d97706)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 12px rgba(251,191,36,0.35)' } },
      React.createElement(_sharedRoleIcon, { size: 15, color: '#fff' })
    ),
    React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 1 } },
      React.createElement('div', { style: { color: 'var(--text-primary)', fontSize: 12, fontWeight: 600, maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', lineHeight: 1.3 }, title: _sharedName }, _sharedName),
      React.createElement('span', { style: { display: 'inline-block', fontSize: 10, fontWeight: 700, lineHeight: '16px', padding: '0 7px', borderRadius: 6, color: _sharedRoleConfig.color, background: `${_sharedRoleConfig.color}1a`, border: `1px solid ${_sharedRoleConfig.color}40`, letterSpacing: 0.3 } }, _sharedRoleConfig.label + (viewAsRole ? ' (preview)' : ''))
    )
  );

  if (!user) {
    return (
      <ConfigProvider theme={LIGHT_THEME}>
        <LoginPage onSignIn={signIn} />
      </ConfigProvider>
    );
  }

  // User clicked a password-reset link — show set-password modal before anything else
  if (needsPasswordReset) {
    return (
      <ConfigProvider theme={LIGHT_THEME}>
        <SetPasswordScreen updatePassword={updatePassword} signOut={signOut} setActiveModule={setActiveModule} email={user?.email} />
      </ConfigProvider>
    );
  }

  if (activeModule === null) {
    return (
      <ConfigProvider theme={THEME_MAP[currentTheme] ?? DARK_THEME}>
        <ModulePicker
          user={user}
          profile={profile}
          role={(viewAsRole ?? authRole) ?? 'viewer'}
          actualRole={authRole ?? 'viewer'}
          viewAsRole={viewAsRole}
          onRoleSwitch={(r) => {
            if (r === null) setViewAsRole(null);
            else setViewAsRole(r);
          }}
          onSelect={(mod) => setActiveModule(mod)}
          onSignOut={() => { signOut(); setActiveModule(null); }}
          profileAvatar={_profileAvatar}
          profileMenuItems={_buildProfileMenu(() => { signOut(); setActiveModule(null); })}
        />
      </ConfigProvider>
    );
  }

  if (activeModule === 'kt') {
    return (
      <ConfigProvider theme={THEME_MAP[currentTheme] ?? DARK_THEME}>
        <KTSessionsPage
          onBack={() => setActiveModule(null)}
          profileAvatar={_profileAvatar}
          profileMenuItems={_buildProfileMenu(() => { signOut(); setActiveModule(null); })}
        />
      </ConfigProvider>
    );
  }

  // ── Standalone: Roles & Access + MyISP Module Roles (tabbed) ──
  if (activeModule === 'rolesaccess') {
    const _role = viewAsRole ?? authRole ?? 'viewer';
    if (!(ROLES[_role]?.canViewRolesAccess)) { setActiveModule(null); return null; }
    return (
      <ConfigProvider theme={THEME_MAP[currentTheme] ?? DARK_THEME}>
        <div style={{ minHeight: '100vh', background: 'var(--bg-base)' }}>
          <div style={{
            height: 52, background: 'var(--bg-sidebar)', borderBottom: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', padding: '0 16px', gap: 12,
            position: 'sticky', top: 0, zIndex: 100,
          }}>
            <Button
              size="small" type="text"
              icon={React.createElement(ShieldCheck, { size: 14, color: '#fbbf24' })}
              onClick={() => setActiveModule(null)}
              style={{ color: 'var(--text-secondary)', fontSize: 12 }}
            >
              ← Back to Modules
            </Button>
            <div style={{ marginLeft: 'auto' }}>
              {React.createElement(Dropdown, {
                trigger: ['click'],
                menu: { items: _buildProfileMenu(() => { signOut(); setActiveModule(null); }) },
                children: _profileAvatar,
              })}
            </div>
          </div>
          <AccessSheet currentUser={user.email} currentUserId={user.id} role={_role} />
        </div>
      </ConfigProvider>
    );
  }

  const currentUser = user.email;
  const actualRole  = authRole ?? 'viewer';
  const role        = viewAsRole ?? actualRole;
  const anyDirty    = Object.values(dirtyModules).some(Boolean);
  const roleConfig  = ROLES[role] || ROLES.viewer;
  const RoleIcon    = roleConfig.icon;
  const displayName = profile && profile.display_name ? profile.display_name : user.email;

  const DotDirty = ({ dirty }) => dirty
    ? <span aria-label="Unsaved changes" style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--warning)', display: 'inline-block', marginLeft: 4, verticalAlign: 'middle' }} />
    : null;

  const navItems = [
    { key: 'home',   icon: React.createElement(Home,    { size: 15 }), label: 'Home' },
    {
      key: 'modules-group',
      icon: React.createElement(LayoutDashboard, { size: 15 }),
      title: 'Modules',
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'Modules',
        React.createElement(DotDirty, { dirty: dirtyModules.dsp || dirtyModules.ssa })
      ),
      children: [
        {
          key: 'dsp',
          icon: React.createElement(Monitor, { size: 15 }),
          label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
            'DSP',
            React.createElement(Badge, { count: dspManual.length + dspAuto.length, style: { background: 'rgba(180,100,6,0.12)', color: '#92400e', border: '1px solid rgba(180,100,6,0.3)', fontSize: 9, boxShadow: 'none' } }),
            React.createElement(DotDirty, { dirty: dirtyModules.dsp })
          ),
        },
        {
          key: 'ssa',
          icon: React.createElement(Shield, { size: 15 }),
          label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
            'SSA',
            React.createElement(Badge, { count: ssaData.length, style: { background: 'rgba(139,92,246,0.15)', color: '#8b5cf6', border: '1px solid rgba(139,92,246,0.3)', fontSize: 9, boxShadow: 'none' } }),
            React.createElement(DotDirty, { dirty: dirtyModules.ssa })
          ),
        },
      ],
    },
    {
      key: 'team',
      icon: React.createElement(Users, { size: 15 }),
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'Team',
        React.createElement(Badge, { count: teamData.length, style: { background: 'rgba(6,182,212,0.15)', color: '#06b6d4', border: '1px solid rgba(6,182,212,0.3)', fontSize: 9, boxShadow: 'none' } }),
        React.createElement(DotDirty, { dirty: dirtyModules.team })
      ),
    },
  ]
   .concat(roleConfig.canViewReport  ? [{ key: 'report', icon: React.createElement(FileText, { size: 15 }), label: 'Report' }] : [])
   .concat(roleConfig.canViewLogs    ? [{ key: 'logs',   icon: React.createElement(Activity, { size: 15 }), label: 'Logs'   }] : [])
   ;

  const renderSheet = () => {
    switch (activeTab) {
      case 'home':
        return (
          <HomePage
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} setActiveTab={setActiveTab}
            currentUser={currentUser} role={role} profile={profile}
          />
        );
      case 'dsp': {
        const editMode = roleConfig.canEdit;
        return (
          <DSPSheet
            searchQuery={searchQuery}
            dspManual={dspManual} setDspManual={setDspManual}
            dspAuto={dspAuto}     setDspAuto={setDspAuto}
            editMode={editMode}   currentUser={currentUser} role={role}
            onSave={() => saveModule('dsp')} isDirty={dirtyModules.dsp} lastSaved={lastSaved.dsp}
            loading={dataLoading}
          />
        );
      }
      case 'ssa': {
        const editMode = roleConfig.canEdit;
        return (
          <SSASheet
            searchQuery={searchQuery} ssaData={ssaData} setSsaData={setSsaData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('ssa')} isDirty={dirtyModules.ssa} lastSaved={lastSaved.ssa}
            loading={dataLoading}
          />
        );
      }
      case 'team': {
        const editMode = roleConfig.canEdit;
        return (
          <TeamSheet
            searchQuery={searchQuery} teamData={teamData} setTeamData={setTeamData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('team')} isDirty={dirtyModules.team} lastSaved={lastSaved.team}
            loading={dataLoading}
          />
        );
      }
      case 'report':
        if (!roleConfig.canViewReport) return null;
        return (
          <ReportSheet
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} role={role}
          />
        );
      case 'logs':
        if (!roleConfig.canViewLogs) return null;
        return React.createElement(ActivityLogSheet, { currentUser, role, dspManual, dspAuto, ssaData, selectedMonth });
      default:
        return null;
    }
  };

  // ── Theme picker definitions ─────────────────────────────
  // Generated by GitHub Copilot
  const THEME_DEFS = [
    { key: 'dark',        name: 'Royal Gold',      bg: '#0c0900', accent: '#fbbf24', desc: 'Warm black + amber' },
    { key: 'dark-ocean',  name: 'Deep Ocean',       bg: '#060d1a', accent: '#06b6d4', desc: 'Dark navy + cyan' },
    { key: 'dark-violet', name: 'Imperial Purple',  bg: '#0d0614', accent: '#a855f7', desc: 'Deep indigo + violet' },
    { key: 'dark-carbon', name: 'Carbon Noir',      bg: '#111111', accent: '#f59e0b', desc: 'Pure charcoal + amber' },
    { key: 'dark-rose',   name: 'Rose Night',       bg: '#100a0a', accent: '#f43f5e', desc: 'Dark red + rose' },
    { key: 'dark-slate',  name: 'Slate Frost',      bg: '#0c1018', accent: '#38bdf8', desc: 'Blue-grey + sky blue' },
    { key: 'light',       name: 'Ivory Gold',       bg: '#f5f3ee', accent: '#d97706', desc: 'Light + warm amber' },
  ];

  return (
    <ConfigProvider theme={THEME_MAP[currentTheme] ?? DARK_THEME}>
      <Layout style={{ minHeight: '100vh', background: 'var(--bg-base)' }}>

        <Sider
          collapsible
          collapsed={collapsed}
          onCollapse={setCollapsed}
          breakpoint="lg"
          onBreakpoint={(broken) => { if (broken) setCollapsed(true); }}
          width={210}
          collapsedWidth={60}
          style={{ background: 'var(--bg-sidebar)', borderRight: '1px solid var(--border-subtle)' }}
        >
          <div style={{
            padding: collapsed ? '16px 13px' : '14px 16px',
            borderBottom: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', gap: 10,
            minHeight: 60,
          }}>
            <Tooltip title="Back to Modules">
              <div
                role="button"
                tabIndex={0}
                aria-label="Back to module picker"
                onClick={() => setActiveModule(null)}
                onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setActiveModule(null); } }}
                style={{
                  width: 34, height: 34, borderRadius: 9, flexShrink: 0,
                  background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 14px rgba(251,191,36,0.3)',
                  cursor: 'pointer',
                }}
              >
                <LayoutDashboard size={18} color="#fff" />
              </div>
            </Tooltip>
            {!collapsed && (
              <div style={{ overflow: 'hidden', cursor: 'pointer' }} onClick={() => setActiveModule(null)}>
                <span style={{ color: 'var(--text-primary)', fontSize: 13, fontWeight: 700, display: 'block', lineHeight: 1.3, whiteSpace: 'nowrap' }}>MyISP</span>
                <span style={{ color: 'var(--text-muted)', fontSize: 10 }}>◀ Modules</span>
              </div>
            )}
          </div>

          <Menu
            mode="inline"
            theme="dark"
            selectedKeys={[activeTab]}
            defaultOpenKeys={['modules-group']}
            items={navItems}
            onClick={({ key }) => {
              if (key === 'modules-group') { setActiveModule(null); setSearchQuery(''); }
              else { setActiveTab(key); setSearchQuery(''); }
            }}
            inlineCollapsed={collapsed}
            style={{ background: 'transparent', border: 'none', marginTop: 6 }}
          />

        </Sider>

        <Layout style={{ background: 'var(--bg-base)', minWidth: 0 }}>
          <Header className="app-header" style={{ padding: '0 14px', lineHeight: 'normal' }}>
            <Tooltip title="Back to Modules">
              <Button
                size="small"
                type="text"
                icon={React.createElement(Home, { size: 13 })}
                onClick={() => { setActiveModule(null); setSearchQuery(''); }}
                style={{ color: 'var(--text-secondary)', flexShrink: 0 }}
              >
                Modules
              </Button>
            </Tooltip>
            <Select
              size="small"
              value={selectedMonth}
              onChange={handleMonthChange}
              options={MONTH_OPTIONS}
              className="header-month-select"
              style={{ width: 155, flexShrink: 0 }}
              popupMatchSelectWidth={false}
              suffixIcon={React.createElement(Calendar, { size: 12, color: 'var(--text-muted)' })}
            />

            <Input
              placeholder={'Search ' + (activeTab === 'home' ? 'all' : activeTab) + '…'}
              prefix={React.createElement(Search, { size: 12, color: 'var(--text-muted)' })}
              value={searchQuery}
              onChange={function(e) { setSearchQuery(e.target.value); }}
              allowClear
              size="small"
              className="header-search"
              style={{ flex: 1, maxWidth: 360 }}
            />

            {anyDirty && (
              <Tag icon={React.createElement(AlertTriangle, { size: 10 })} color="warning" style={{ margin: 0, flexShrink: 0 }}>
                Unsaved
              </Tag>
            )}

            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6 }}>

              {/* Save button — always visible for non-viewers */}
              {role !== 'viewer' && (
                <Tooltip title={anyDirty ? 'Save all unsaved changes' : 'No unsaved changes'}>
                  <Button
                    size="small"
                    icon={React.createElement(Save, { size: 12 })}
                    onClick={saveAllModules}
                    disabled={!anyDirty}
                    type={anyDirty ? 'primary' : 'default'}
                style={anyDirty ? { background: '#fbbf24', borderColor: '#d97706', color: '#0c0900', fontWeight: 700 } : {}}
                  >
                    Save
                  </Button>
                </Tooltip>
              )}

              <Tooltip title="Copy current sheet as TSV (Excel-ready)">
                <Button size="small" icon={React.createElement(Copy, { size: 12 })} onClick={handleCopy}>
                  Copy
                </Button>
              </Tooltip>

              {/* Divider */}
              <div style={{ width: 1, height: 20, background: 'var(--border-subtle)', margin: '0 4px' }} />

              {/* Profile dropdown */}
              {React.createElement(Dropdown, {
                trigger: ['click'],
                menu: { items: _buildProfileMenu(() => { signOut(); setActiveModule(null); }) },
                children: _profileAvatar,
              })}



            </div>
          </Header>

            <Content style={{ background: 'var(--bg-base)', overflow: 'auto' }}>
            {viewAsRole && (
              <div style={{ background: 'var(--warning-bg)', color: '#fef3c7', padding: '6px 16px', fontSize: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span>Previewing as <strong>{ROLES[viewAsRole].label}</strong> — changes are disabled in preview mode</span>
                <Button size="small" onClick={() => setViewAsRole(null)} style={{ fontSize: 11 }}>Exit Preview</Button>
              </div>
            )}
            {renderSheet()}
          </Content>
        </Layout>
      </Layout>

      <FloatButton.BackTop style={{ right: 24, bottom: 24 }} />

      {/* ── Theme Picker Modal ─────────────────────────── */}
      {/* Generated by GitHub Copilot */}
      <Modal
        open={themeModalOpen}
        onCancel={() => setThemeModalOpen(false)}
        footer={null}
        title={React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 8 } },
          React.createElement(Palette, { size: 15, color: 'var(--accent)' }),
          React.createElement('span', null, 'Choose Theme')
        )}
        width={560}
        styles={{ body: { paddingTop: 8 } }}
        aria-label="Theme picker"
      >
        <div
          role="radiogroup"
          aria-label="Available themes"
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: 12,
            padding: '4px 0 8px',
          }}
        >
          {THEME_DEFS.map(({ key, name, bg, accent, desc }) => {
            const isActive = currentTheme === key;
            return React.createElement('button', {
              key,
              role: 'radio',
              'aria-checked': isActive,
              onClick: () => { setCurrentTheme(key); setThemeModalOpen(false); },
              style: {
                background: bg,
                border: `2px solid ${isActive ? accent : 'rgba(255,255,255,0.1)'}`,
                borderRadius: 12,
                padding: '12px 14px',
                cursor: 'pointer',
                textAlign: 'left',
                position: 'relative',
                transition: 'border-color 0.2s, box-shadow 0.2s',
                boxShadow: isActive ? `0 0 0 3px ${accent}33` : 'none',
                outline: 'none',
              },
            },
              /* Accent swatch strip */
              React.createElement('div', {
                style: {
                  width: 28, height: 6, borderRadius: 4,
                  background: accent,
                  marginBottom: 8,
                  boxShadow: `0 0 8px ${accent}88`,
                },
              }),
              /* Theme name */
              React.createElement('div', {
                style: {
                  fontSize: 12, fontWeight: 700,
                  color: key === 'light' ? '#1a1209' : '#ffffff',
                  marginBottom: 2,
                },
              }, name),
              /* Description */
              React.createElement('div', {
                style: {
                  fontSize: 10,
                  color: key === 'light' ? '#78530a' : 'rgba(255,255,255,0.45)',
                },
              }, desc),
              /* Active checkmark */
              isActive && React.createElement('div', {
                'aria-hidden': 'true',
                style: {
                  position: 'absolute', top: 8, right: 8,
                  width: 18, height: 18, borderRadius: '50%',
                  background: accent,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 10, color: '#fff', fontWeight: 900, lineHeight: 1,
                },
              }, '✓')
            );
          })}
        </div>
      </Modal>
    </ConfigProvider>
  );
}

export default App;
