import React, { useState, useEffect } from 'react';
import {
  Layout, Menu, Space, Badge, ConfigProvider, FloatButton, Modal, Spin,
  Typography, Tag, Button, Tooltip, Select, Input, theme as antTheme, Dropdown, Form,
} from 'antd';
import {
  Home, Monitor, Shield, Users, FileText, Activity,
  LayoutDashboard, Calendar, Search, Copy, Save, Download,
  AlertTriangle, LogOut, UserCog, Lock,
  ShieldCheck, KeyRound,
} from 'lucide-react';

// Auth + data hooks
import { useAuth }      from './hooks/useAuth.js';
import { useMonthData } from './hooks/useMonthData.js';

// Components
import LoginPage        from './components/auth/LoginPage.jsx';
import ModulePicker     from './components/ModulePicker.jsx';
import KTSessionsPage   from './components/KTSessionsPage.jsx';
import HomePage         from './components/home/HomePage.jsx';
import DSPSheet         from './components/sheets/DSPSheet.jsx';
import SSASheet         from './components/sheets/SSASheet.jsx';
import TeamSheet        from './components/sheets/TeamSheet.jsx';
import ReportSheet      from './components/sheets/ReportSheet.jsx';
import ActivityLogSheet from './components/sheets/ActivityLogSheet.jsx';
import AccessSheet           from './components/sheets/AccessSheet.jsx';

// Utils
import { MONTH_OPTIONS, ROLES, ROLE_HIERARCHY, currentMonthKey } from './utils/constants.js';
import { toTSV, filterData }                     from './utils/helpers.jsx';

import './App.css';

const { Sider, Content, Header } = Layout;
const { Text } = Typography;

const DARK_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#22c55e',
    colorBgBase:        '#06080c',
    colorBgContainer:   'rgba(13,17,28,0.55)',
    colorBgElevated:    'rgba(20,26,42,0.8)',
    colorBorder:        'rgba(255,255,255,0.07)',
    colorText:          '#f1f5f9',
    colorTextSecondary: '#94a3b8',
    borderRadius:       12,
    borderRadiusLG:     20,
    fontFamily:         "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
function SetPasswordScreen({ updatePassword, signOut, setActiveModule, email }) {
  const [saving, setSaving] = useState(false);
  const [done,   setDone]   = useState(false);
  const [form]              = Form.useForm();

  const handleSave = async ({ password }) => {
    setSaving(true);
    const { error } = await updatePassword(password);
    setSaving(false);
    if (error) {
      Modal.error({ title: 'Failed to set password', content: error.message });
      return;
    }
    setDone(true);
    // Sign out so user logs in fresh with their new password
    setTimeout(async () => {
      await signOut();
      setActiveModule(null);
    }, 2500);
  };

  return (
    <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#06080c', backgroundImage: 'radial-gradient(at 0% 0%, rgba(34,197,94,0.08) 0px, transparent 55%), radial-gradient(at 100% 100%, rgba(59,130,246,0.06) 0px, transparent 55%)' }}>
      <div style={{ width: 420, background: 'rgba(13,17,28,0.7)', backdropFilter: 'blur(20px)', borderRadius: 20, padding: '32px 28px', border: '1px solid rgba(255,255,255,0.07)' }}>
        {done ? (
          <div style={{ textAlign: 'center', padding: '16px 0' }}>
            <div style={{ width: 56, height: 56, borderRadius: '50%', background: 'rgba(34,197,94,0.15)', border: '2px solid #22c55e', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
              <Lock size={24} color="#22c55e" />
            </div>
            <Text strong style={{ color: '#e2e8f0', fontSize: 18, display: 'block', marginBottom: 8 }}>Password saved!</Text>
            <Text type="secondary" style={{ fontSize: 13 }}>Signing you out… please log in with your new password.</Text>
          </div>
        ) : (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
              <div style={{ width: 36, height: 36, borderRadius: 8, background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Lock size={18} color="#22c55e" />
              </div>
              <div>
                <Text strong style={{ color: '#e2e8f0', display: 'block', fontSize: 15 }}>Set New Password</Text>
                <Text type="secondary" style={{ fontSize: 12 }}>Choose a password to secure your account</Text>
              </div>
            </div>

            {/* Show which email account is being activated */}
            {email && (
              <div style={{ background: '#0d1526', border: '1px solid #2d3a55', borderRadius: 8, padding: '10px 14px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 28, height: 28, borderRadius: '50%', background: '#22c55e', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: 12, fontWeight: 700, color: '#fff' }}>
                  {email[0].toUpperCase()}
                </div>
                <div>
                  <Text type="secondary" style={{ fontSize: 10, display: 'block', lineHeight: 1.3 }}>Setting password for</Text>
                  <Text strong style={{ color: '#e2e8f0', fontSize: 12 }}>{email}</Text>
                </div>
              </div>
            )}

            <Form form={form} layout="vertical" requiredMark={false} onFinish={handleSave}>
              <Form.Item
                name="password"
                label={<Text style={{ color: '#8892a4', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>New Password</Text>}
                rules={[{ required: true, message: 'Enter a password' }, { min: 8, message: 'At least 8 characters' }]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="#4b5568" style={{ marginRight: 4 }} />} placeholder="Minimum 8 characters" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Form.Item
                name="confirm"
                label={<Text style={{ color: '#8892a4', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>Confirm Password</Text>}
                dependencies={['password']}
                rules={[
                  { required: true, message: 'Please confirm your password' },
                  ({ getFieldValue }) => ({
                    validator(_, v) {
                      return !v || getFieldValue('password') === v ? Promise.resolve() : Promise.reject('Passwords do not match');
                    },
                  }),
                ]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="#4b5568" style={{ marginRight: 4 }} />} placeholder="Re-enter password" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Button type="primary" htmlType="submit" size="large" loading={saving}
                style={{ width: '100%', height: 46, borderRadius: 9, background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)', border: 'none', fontWeight: 700, fontSize: 15 }}>
                {saving ? 'Saving…' : 'Save Password & Continue'}
              </Button>
            </Form>
          </>
        )}
      </div>
    </div>
  );
}

function App() {
  const { user, profile, role: authRole, loading: authLoading, signIn, signOut, needsPasswordReset, updatePassword, allowedRoles } = useAuth();

  const [activeModule,  setActiveModule]  = useState(null); // null = picker, 'e2e' = dashboard
  const [activeTab,     setActiveTab]     = useState('home');
  const [searchQuery,   setSearchQuery]   = useState('');
  const [selectedMonth, setSelectedMonth] = useState(currentMonthKey());
  const [collapsed,     setCollapsed]     = useState(false);
  const [viewAsRole,    setViewAsRole]    = useState(null); // admin preview override

  // ── Hash routing ──────────────────────────────────────────
  useEffect(() => {
    const h = window.location.hash.replace(/^#\//, '');
    if (h.startsWith('e2e/')) { setActiveModule('e2e'); setActiveTab(h.slice(4) || 'home'); }
    else if (h === 'kt')     setActiveModule('kt');
    else if (h === 'roles')  setActiveModule('rolesaccess');
  }, []);

  useEffect(() => {
    if      (activeModule === 'e2e')        window.location.hash = '/e2e/' + activeTab;
    else if (activeModule === 'kt')         window.location.hash = '/kt';
    else if (activeModule === 'rolesaccess') window.location.hash = '/roles';
    else                                    window.location.hash = '/';
  }, [activeModule, activeTab]);

  const {
    dspManual, setDspManual,
    dspAuto,   setDspAuto,
    ssaData,   setSsaData,
    teamData,  setTeamData,
    dirtyModules,
    lastSaved,
    saveModule,
    saveAllModules,
    loading: dataLoading,
  } = useMonthData(selectedMonth, user);

  const handleMonthChange = (newMonth) => {
    if (Object.values(dirtyModules).some(Boolean)) {
      Modal.confirm({
        title:     'Unsaved Changes',
        content:   'You have unsaved changes. Save before switching months?',
        okText:    'Save & Switch',
        cancelText:'Discard & Switch',
        onOk:    async () => { await saveAllModules(); setSelectedMonth(newMonth); setSearchQuery(''); },
        onCancel:() => { setSelectedMonth(newMonth); setSearchQuery(''); },
      });
    } else {
      setSelectedMonth(newMonth);
      setSearchQuery('');
    }
  };

  const handleExportJSON = () => {
    const payload = {
      month: selectedMonth, dspManual, dspAuto, ssaData, teamData,
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = 'e2e-' + selectedMonth + '.json'; a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    const dspCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Env',    dataIndex: 'env'    }, { title: 'SG',     dataIndex: 'sg'     },
      { title: 'Deal',   dataIndex: 'deal'   }, { title: 'Status', dataIndex: 'status' },
    ];
    const ssaCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Deal',   dataIndex: 'dealId' }, { title: 'Status', dataIndex: 'status' },
    ];
    const map = {
      dsp: { columns: dspCols, data: [...dspManual, ...dspAuto] },
      ssa: { columns: ssaCols, data: ssaData },
    };
    const target = map[activeTab] || map.dsp;
    navigator.clipboard.writeText(toTSV(target.columns, filterData(target.data, searchQuery))).catch(() => {});
  };

  if (authLoading) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0d0f18' }}>
        <Spin size="large" />
      </div>
    );
  }
  if (!user) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <LoginPage onSignIn={signIn} />
      </ConfigProvider>
    );
  }

  // User clicked a password-reset link — show set-password modal before anything else
  if (needsPasswordReset) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <SetPasswordScreen updatePassword={updatePassword} signOut={signOut} setActiveModule={setActiveModule} email={user?.email} />
      </ConfigProvider>
    );
  }

  if (activeModule === null) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <ModulePicker
          user={user}
          profile={profile}
          role={(viewAsRole ?? authRole) ?? 'viewer'}
          actualRole={authRole ?? 'viewer'}
          viewAsRole={viewAsRole}
          onRoleSwitch={(r) => {
            if (r === null) setViewAsRole(null);
            else setViewAsRole(r);
          }}
          onSelect={(mod) => setActiveModule(mod)}
          onSignOut={() => { signOut(); setActiveModule(null); }}
        />
      </ConfigProvider>
    );
  }

  if (activeModule === 'kt') {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <KTSessionsPage onBack={() => setActiveModule(null)} />
      </ConfigProvider>
    );
  }

  // ── Standalone: Roles & Access + MyISP Module Roles (tabbed) ──
  if (activeModule === 'rolesaccess') {
    const _role = viewAsRole ?? authRole ?? 'viewer';
    if (!(ROLES[_role]?.canViewRolesAccess)) { setActiveModule(null); return null; }
    return (
      <ConfigProvider theme={DARK_THEME}>
          <div style={{ minHeight: '100vh', background: 'var(--bg-base)' }}>
          <div style={{
            height: 52, background: 'var(--bg-sidebar)', borderBottom: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', padding: '0 16px', gap: 12,
            position: 'sticky', top: 0, zIndex: 100,
          }}>
            <Button
              size="small" type="text"
              icon={React.createElement(ShieldCheck, { size: 14, color: '#22c55e' })}
              onClick={() => setActiveModule(null)}
              style={{ color: '#8892a4', fontSize: 12 }}
            >
              ← Back to Modules
            </Button>
          </div>
          <AccessSheet currentUser={user.email} currentUserId={user.id} role={_role} />
        </div>
      </ConfigProvider>
    );
  }

  const currentUser = user.email;
  const actualRole  = authRole ?? 'viewer';
  const role        = viewAsRole ?? actualRole;
  const anyDirty    = Object.values(dirtyModules).some(Boolean);
  const roleConfig  = ROLES[role] || ROLES.viewer;
  const RoleIcon    = roleConfig.icon;
  const displayName = profile && profile.display_name ? profile.display_name : user.email;

  const DotDirty = ({ dirty }) => dirty
    ? <span aria-label="Unsaved changes" style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--warning)', display: 'inline-block', marginLeft: 4, verticalAlign: 'middle' }} />
    : null;

  const navItems = [
    { key: 'home',   icon: React.createElement(Home,    { size: 15 }), label: 'Home' },
    {
      key: 'modules-group',
      icon: React.createElement(LayoutDashboard, { size: 15 }),
      title: 'Modules',
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'Modules',
        React.createElement(DotDirty, { dirty: dirtyModules.dsp || dirtyModules.ssa })
      ),
      children: [
        {
          key: 'dsp',
          icon: React.createElement(Monitor, { size: 15 }),
          label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
            'DSP',
            React.createElement(Badge, { count: dspManual.length + dspAuto.length, style: { background: 'rgba(34,197,94,0.15)', color: '#22c55e', border: '1px solid rgba(34,197,94,0.3)', fontSize: 9, boxShadow: 'none' } }),
            React.createElement(DotDirty, { dirty: dirtyModules.dsp })
          ),
        },
        {
          key: 'ssa',
          icon: React.createElement(Shield, { size: 15 }),
          label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
            'SSA',
            React.createElement(Badge, { count: ssaData.length, style: { background: 'rgba(139,92,246,0.15)', color: '#8b5cf6', border: '1px solid rgba(139,92,246,0.3)', fontSize: 9, boxShadow: 'none' } }),
            React.createElement(DotDirty, { dirty: dirtyModules.ssa })
          ),
        },
      ],
    },
    {
      key: 'team',
      icon: React.createElement(Users, { size: 15 }),
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'Team',
        React.createElement(Badge, { count: teamData.length, style: { background: 'rgba(6,182,212,0.15)', color: '#06b6d4', border: '1px solid rgba(6,182,212,0.3)', fontSize: 9, boxShadow: 'none' } }),
        React.createElement(DotDirty, { dirty: dirtyModules.team })
      ),
    },
  ]
   .concat(roleConfig.canViewReport  ? [{ key: 'report', icon: React.createElement(FileText, { size: 15 }), label: 'Report' }] : [])
   .concat(roleConfig.canViewLogs    ? [{ key: 'logs',   icon: React.createElement(Activity, { size: 15 }), label: 'Logs'   }] : [])
   ;

  const renderSheet = () => {
    switch (activeTab) {
      case 'home':
        return (
          <HomePage
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} setActiveTab={setActiveTab}
            currentUser={currentUser} role={role} profile={profile}
          />
        );
      case 'dsp': {
        const editMode = roleConfig.canEdit;
        return (
          <DSPSheet
            searchQuery={searchQuery}
            dspManual={dspManual} setDspManual={setDspManual}
            dspAuto={dspAuto}     setDspAuto={setDspAuto}
            editMode={editMode}   currentUser={currentUser} role={role}
            onSave={() => saveModule('dsp')} isDirty={dirtyModules.dsp} lastSaved={lastSaved.dsp}
            loading={dataLoading}
          />
        );
      }
      case 'ssa': {
        const editMode = roleConfig.canEdit;
        return (
          <SSASheet
            searchQuery={searchQuery} ssaData={ssaData} setSsaData={setSsaData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('ssa')} isDirty={dirtyModules.ssa} lastSaved={lastSaved.ssa}
            loading={dataLoading}
          />
        );
      }
      case 'team': {
        const editMode = roleConfig.canEdit;
        return (
          <TeamSheet
            searchQuery={searchQuery} teamData={teamData} setTeamData={setTeamData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('team')} isDirty={dirtyModules.team} lastSaved={lastSaved.team}
            loading={dataLoading}
          />
        );
      }
      case 'report':
        if (!roleConfig.canViewReport) return null;
        return (
          <ReportSheet
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} role={role}
          />
        );
      case 'logs':
        if (!roleConfig.canViewLogs) return null;
        return React.createElement(ActivityLogSheet, { currentUser, role, dspManual, dspAuto, ssaData, selectedMonth });
      default:
        return null;
    }
  };

  return (
    <ConfigProvider theme={DARK_THEME}>
      <Layout style={{ minHeight: '100vh', background: 'var(--bg-base)' }}>

        <Sider
          collapsible
          collapsed={collapsed}
          onCollapse={setCollapsed}
          breakpoint="lg"
          onBreakpoint={(broken) => { if (broken) setCollapsed(true); }}
          width={210}
          collapsedWidth={60}
          style={{ background: 'var(--bg-sidebar)', borderRight: '1px solid var(--border-subtle)' }}
        >
          <div style={{
            padding: collapsed ? '16px 13px' : '14px 16px',
            borderBottom: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', gap: 10,
            minHeight: 60,
          }}>
            <Tooltip title="Back to Modules">
              <div
                role="button"
                tabIndex={0}
                aria-label="Back to module picker"
                onClick={() => setActiveModule(null)}
                onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setActiveModule(null); } }}
                style={{
                  width: 34, height: 34, borderRadius: 9, flexShrink: 0,
                  background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 14px rgba(34,197,94,0.25)',
                  cursor: 'pointer',
                }}
              >
                <LayoutDashboard size={18} color="#fff" />
              </div>
            </Tooltip>
            {!collapsed && (
              <div style={{ overflow: 'hidden', cursor: 'pointer' }} onClick={() => setActiveModule(null)}>
                <span style={{ color: '#e2e8f0', fontSize: 13, fontWeight: 700, display: 'block', lineHeight: 1.3, whiteSpace: 'nowrap' }}>MyISP</span>
                <span style={{ color: '#4b5568', fontSize: 10 }}>◀ Modules</span>
              </div>
            )}
          </div>

          <Menu
            mode="inline"
            theme="dark"
            selectedKeys={[activeTab]}
            defaultOpenKeys={['modules-group']}
            items={navItems}
            onClick={({ key }) => {
              if (key === 'modules-group') { setActiveModule(null); setSearchQuery(''); }
              else { setActiveTab(key); setSearchQuery(''); }
            }}
            inlineCollapsed={collapsed}
            style={{ background: 'transparent', border: 'none', marginTop: 6 }}
          />

        </Sider>

        <Layout style={{ background: 'var(--bg-base)', minWidth: 0 }}>
          <Header className="app-header" style={{ padding: '0 14px', lineHeight: 'normal' }}>
            <Tooltip title="Back to Modules">
              <Button
                size="small"
                type="text"
                icon={React.createElement(Home, { size: 13 })}
                onClick={() => { setActiveModule(null); setSearchQuery(''); }}
                style={{ color: '#8892a4', flexShrink: 0 }}
              >
                Modules
              </Button>
            </Tooltip>
            <Select
              size="small"
              value={selectedMonth}
              onChange={handleMonthChange}
              options={MONTH_OPTIONS}
              className="header-month-select"
              style={{ width: 155, flexShrink: 0 }}
              popupMatchSelectWidth={false}
              suffixIcon={React.createElement(Calendar, { size: 12, color: '#4b5568' })}
            />

            <Input
              placeholder={'Search ' + (activeTab === 'home' ? 'all' : activeTab) + '…'}
              prefix={React.createElement(Search, { size: 12, color: '#4b5568' })}
              value={searchQuery}
              onChange={function(e) { setSearchQuery(e.target.value); }}
              allowClear
              size="small"
              className="header-search"
              style={{ flex: 1, maxWidth: 360 }}
            />

            {anyDirty && (
              <Tag icon={React.createElement(AlertTriangle, { size: 10 })} color="warning" style={{ margin: 0, flexShrink: 0 }}>
                Unsaved
              </Tag>
            )}

            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6 }}>

              {/* Save button — always visible for non-viewers */}
              {role !== 'viewer' && (
                <Tooltip title={anyDirty ? 'Save all unsaved changes' : 'No unsaved changes'}>
                  <Button
                    size="small"
                    icon={React.createElement(Save, { size: 12 })}
                    onClick={saveAllModules}
                    disabled={!anyDirty}
                    type={anyDirty ? 'primary' : 'default'}
                    style={anyDirty ? { background: '#22c55e', borderColor: '#22c55e', color: '#fff', fontWeight: 600 } : {}}
                  >
                    Save
                  </Button>
                </Tooltip>
              )}

              <Tooltip title="Copy current sheet as TSV (Excel-ready)">
                <Button size="small" icon={React.createElement(Copy, { size: 12 })} onClick={handleCopy}>
                  Copy
                </Button>
              </Tooltip>

              {/* Divider */}
              <div style={{ width: 1, height: 20, background: 'var(--border-subtle)', margin: '0 4px' }} />

              {/* Profile dropdown */}
              {React.createElement(Dropdown, {
                trigger: ['click'],
                menu: {
                  items: [
                    { type: 'group', label: displayName },
                    {
                      key: 'role-info',
                      label: React.createElement('div', { style: { padding: '4px 0', pointerEvents: 'none' } },
                        allowedRoles && allowedRoles.length > 0 && React.createElement('div', null,
                          React.createElement('div', { style: { fontSize: 10, color: '#8892a4', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 } }, 'Your Role'),
                          React.createElement('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 4 } },
                            ...allowedRoles.map((r) => {
                              const rc = ROLES[r] ?? ROLES.viewer;
                              const RIcon = rc.icon;
                              const isActive = (viewAsRole ?? actualRole) === r;
                              return React.createElement(Tag, {
                                key: r,
                                style: {
                                  background: isActive ? rc.bg : 'transparent',
                                  color: rc.color,
                                  border: `1px solid ${isActive ? rc.border : '#252d42'}`,
                                  fontSize: 11, margin: 0,
                                  fontWeight: isActive ? 700 : 400,
                                },
                              },
                                React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
                                  React.createElement(RIcon, { size: 10 }),
                                  rc.label,
                                  isActive && React.createElement('span', { style: { fontSize: 9, marginLeft: 2 } }, '●')
                                )
                              );
                            })
                          )
                        )
                      ),
                    },
                    { type: 'divider' },
                    // Switch Role — visible to any user with multiple allowed roles
                    ...(allowedRoles && allowedRoles.length > 1 ? [
                      { type: 'group', label: actualRole === 'admin' ? 'Switch Role View' : 'Switch Role' },
                      // admin can preview all 4 roles; others can only switch to their allowed_roles
                      ...(actualRole === 'admin' ? ['admin','tl','tester','viewer'] : allowedRoles).map((r) => {
                        const rc = ROLES[r];
                        const RIcon = rc.icon;
                        const isCurrentActual = r === actualRole && !viewAsRole;
                        const isActive = viewAsRole === r || isCurrentActual;
                        return {
                          key: 'preview-' + r,
                          label: React.createElement('div', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 } },
                            React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 6, color: rc.color, fontWeight: isActive ? 700 : 400 } },
                              React.createElement(RIcon, { size: 12 }),
                              rc.label
                            ),
                            isCurrentActual
                              ? React.createElement(Tag, { color: 'green', style: { margin: 0, fontSize: 10 } }, 'Current')
                              : isActive
                                ? React.createElement(Tag, { color: 'orange', style: { margin: 0, fontSize: 10 } }, 'Active')
                                : null
                          ),
                          onClick: () => {
                            if (isCurrentActual) return;
                            if (viewAsRole === r) setViewAsRole(null);
                            else setViewAsRole(r);
                            setActiveTab('home');
                          },
                        };
                      }),
                      { type: 'divider' },
                    ] : []),
                    { key: 'signout', label: React.createElement('span', { style: { color: '#f87171' } }, 'Sign out'), onClick: () => { signOut(); setActiveModule(null); } },
                  ],
                },
            children: React.createElement('div', {
                  role: 'button',
                  tabIndex: 0,
                  style: { display: 'flex', alignItems: 'center', gap: 6, padding: '3px 8px', borderRadius: 8, background: '#1a2035', border: '1px solid var(--border-subtle)', cursor: 'pointer' }
                },
                  React.createElement('div', { style: { width: 22, height: 22, borderRadius: '50%', background: 'linear-gradient(135deg, #22c55e, #16a34a)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 } },
                    React.createElement(RoleIcon, { size: 11, color: '#fff' })
                  ),
                  React.createElement('div', { style: { lineHeight: 1.2, maxWidth: 160 } },
                    React.createElement('div', { style: { color: '#e2e8f0', fontSize: 11, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }, title: displayName }, displayName),
                    React.createElement('div', { style: { color: roleConfig.color, fontSize: 10, fontWeight: 700 } }, roleConfig.label)
                  )
                )
              })}



              <Tooltip title="Export month data as JSON">
                <Button size="small" icon={React.createElement(Download, { size: 12 })} onClick={handleExportJSON}>
                  Export
                </Button>
              </Tooltip>
            </div>
          </Header>

            <Content style={{ background: 'var(--bg-base)', overflow: 'auto' }}>
            {viewAsRole && (
              <div style={{ background: 'var(--warning-bg)', color: '#fef3c7', padding: '6px 16px', fontSize: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span>Previewing as <strong>{ROLES[viewAsRole].label}</strong> — changes are disabled in preview mode</span>
                <Button size="small" onClick={() => setViewAsRole(null)} style={{ fontSize: 11 }}>Exit Preview</Button>
              </div>
            )}
            {renderSheet()}
          </Content>
        </Layout>
      </Layout>

      <FloatButton.BackTop style={{ right: 24, bottom: 24 }} />
    </ConfigProvider>
  );
}

export default App;
