import React, { useState, useEffect } from 'react';
import {
  Layout, Menu, Space, Badge, ConfigProvider, FloatButton, Modal, Spin,
  Typography, Tag, Button, Tooltip, Segmented, Select, Input, theme as antTheme, Dropdown, Form,
} from 'antd';
import {
  Home, Monitor, Shield, Users, FileText, Activity,
  LayoutDashboard, Calendar, Search, Copy, Save, Download,
  PenTool, Eye, AlertTriangle, LogOut, UserCog, Lock,
  ShieldCheck, KeyRound,
} from 'lucide-react';

// Auth + data hooks
import { useAuth }      from './hooks/useAuth.js';
import { useMonthData } from './hooks/useMonthData.js';

// Components
import LoginPage        from './components/auth/LoginPage.jsx';
import ModulePicker     from './components/ModulePicker.jsx';
import KTSessionsPage   from './components/KTSessionsPage.jsx';
import HomePage         from './components/home/HomePage.jsx';
import DSPSheet         from './components/sheets/DSPSheet.jsx';
import SSASheet         from './components/sheets/SSASheet.jsx';
import TeamSheet        from './components/sheets/TeamSheet.jsx';
import ReportSheet      from './components/sheets/ReportSheet.jsx';
import ActivityLogSheet from './components/sheets/ActivityLogSheet.jsx';
import UsersSheet             from './components/sheets/UsersSheet.jsx';
import AccessSheet           from './components/sheets/AccessSheet.jsx';

// Utils
import { MONTH_OPTIONS, ROLES, ROLE_HIERARCHY, currentMonthKey } from './utils/constants.js';
import { toTSV, filterData }                     from './utils/helpers.jsx';

import './App.css';

const { Sider, Content, Header } = Layout;
const { Text } = Typography;

const DARK_THEME = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary:       '#22c55e',
    colorBgBase:        '#0d0f18',
    colorBgContainer:   '#1a1f2e',
    colorBgElevated:    '#1e2438',
    colorBorder:        '#252d42',
    colorText:          '#e2e8f0',
    colorTextSecondary: '#8892a4',
    borderRadius:       8,
    borderRadiusLG:     10,
    fontFamily:         "'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:           13,
  },
};

// Generated by GitHub Copilot
function SetPasswordScreen({ updatePassword, signOut, setActiveModule, email }) {
  const [saving, setSaving] = useState(false);
  const [done,   setDone]   = useState(false);
  const [form]              = Form.useForm();

  const handleSave = async ({ password }) => {
    setSaving(true);
    const { error } = await updatePassword(password);
    setSaving(false);
    if (error) {
      Modal.error({ title: 'Failed to set password', content: error.message });
      return;
    }
    setDone(true);
    // Sign out so user logs in fresh with their new password
    setTimeout(async () => {
      await signOut();
      setActiveModule(null);
    }, 2500);
  };

  return (
    <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0d0f18' }}>
      <div style={{ width: 420, background: '#1a1f2e', borderRadius: 12, padding: '32px 28px', border: '1px solid #252d42' }}>
        {done ? (
          <div style={{ textAlign: 'center', padding: '16px 0' }}>
            <div style={{ width: 56, height: 56, borderRadius: '50%', background: 'rgba(34,197,94,0.15)', border: '2px solid #22c55e', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
              <Lock size={24} color="#22c55e" />
            </div>
            <Text strong style={{ color: '#e2e8f0', fontSize: 18, display: 'block', marginBottom: 8 }}>Password saved!</Text>
            <Text type="secondary" style={{ fontSize: 13 }}>Signing you out… please log in with your new password.</Text>
          </div>
        ) : (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
              <div style={{ width: 36, height: 36, borderRadius: 8, background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Lock size={18} color="#22c55e" />
              </div>
              <div>
                <Text strong style={{ color: '#e2e8f0', display: 'block', fontSize: 15 }}>Set New Password</Text>
                <Text type="secondary" style={{ fontSize: 12 }}>Choose a password to secure your account</Text>
              </div>
            </div>

            {/* Show which email account is being activated */}
            {email && (
              <div style={{ background: '#0d1526', border: '1px solid #2d3a55', borderRadius: 8, padding: '10px 14px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 28, height: 28, borderRadius: '50%', background: '#22c55e', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: 12, fontWeight: 700, color: '#fff' }}>
                  {email[0].toUpperCase()}
                </div>
                <div>
                  <Text type="secondary" style={{ fontSize: 10, display: 'block', lineHeight: 1.3 }}>Setting password for</Text>
                  <Text strong style={{ color: '#e2e8f0', fontSize: 12 }}>{email}</Text>
                </div>
              </div>
            )}

            <Form form={form} layout="vertical" requiredMark={false} onFinish={handleSave}>
              <Form.Item
                name="password"
                label={<Text style={{ color: '#8892a4', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>New Password</Text>}
                rules={[{ required: true, message: 'Enter a password' }, { min: 8, message: 'At least 8 characters' }]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="#4b5568" style={{ marginRight: 4 }} />} placeholder="Minimum 8 characters" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Form.Item
                name="confirm"
                label={<Text style={{ color: '#8892a4', fontSize: 11, fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase' }}>Confirm Password</Text>}
                dependencies={['password']}
                rules={[
                  { required: true, message: 'Please confirm your password' },
                  ({ getFieldValue }) => ({
                    validator(_, v) {
                      return !v || getFieldValue('password') === v ? Promise.resolve() : Promise.reject('Passwords do not match');
                    },
                  }),
                ]}
              >
                <Input.Password size="large" prefix={<Lock size={14} color="#4b5568" style={{ marginRight: 4 }} />} placeholder="Re-enter password" style={{ borderRadius: 9, height: 44 }} />
              </Form.Item>
              <Button type="primary" htmlType="submit" size="large" loading={saving}
                style={{ width: '100%', height: 46, borderRadius: 9, background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)', border: 'none', fontWeight: 700, fontSize: 15 }}>
                {saving ? 'Saving…' : 'Save Password & Continue'}
              </Button>
            </Form>
          </>
        )}
      </div>
    </div>
  );
}

function App() {
  const { user, profile, role: authRole, loading: authLoading, signIn, signOut, needsPasswordReset, updatePassword } = useAuth();

  const [activeModule,  setActiveModule]  = useState(null); // null = picker, 'e2e' = dashboard
  const [activeTab,     setActiveTab]     = useState('home');
  const [searchQuery,   setSearchQuery]   = useState('');
  const [editMode,      setEditMode]      = useState(false);
  const [selectedMonth, setSelectedMonth] = useState(currentMonthKey());
  const [collapsed,     setCollapsed]     = useState(false);
  const [viewAsRole,    setViewAsRole]    = useState(null); // admin preview override

  const {
    dspManual, setDspManual,
    dspAuto,   setDspAuto,
    ssaData,   setSsaData,
    teamData,  setTeamData,
    dirtyModules,
    lastSaved,
    saveModule,
    saveAllModules,
    loading: dataLoading,
  } = useMonthData(selectedMonth, user);

  useEffect(() => {
    if (authRole === 'viewer' || authRole === 'tester') setEditMode(false);
    else if (authRole === 'admin' || authRole === 'tl') setEditMode(true);
  }, [authRole]);

  const handleMonthChange = (newMonth) => {
    if (Object.values(dirtyModules).some(Boolean)) {
      Modal.confirm({
        title:     'Unsaved Changes',
        content:   'You have unsaved changes. Save before switching months?',
        okText:    'Save & Switch',
        cancelText:'Discard & Switch',
        onOk:    () => { saveAllModules(); setSelectedMonth(newMonth); setSearchQuery(''); },
        onCancel:() => { setSelectedMonth(newMonth); setSearchQuery(''); },
      });
    } else {
      setSelectedMonth(newMonth);
      setSearchQuery('');
    }
  };

  const handleExportJSON = () => {
    const payload = {
      month: selectedMonth, dspManual, dspAuto, ssaData, teamData,
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = 'e2e-' + selectedMonth + '.json'; a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    const dspCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Env',    dataIndex: 'env'    }, { title: 'SG',     dataIndex: 'sg'     },
      { title: 'Deal',   dataIndex: 'deal'   }, { title: 'Status', dataIndex: 'status' },
    ];
    const ssaCols = [
      { title: 'Tester', dataIndex: 'tester' }, { title: 'Module', dataIndex: 'module' },
      { title: 'Deal',   dataIndex: 'dealId' }, { title: 'Status', dataIndex: 'status' },
    ];
    const map = {
      dsp: { columns: dspCols, data: [...dspManual, ...dspAuto] },
      ssa: { columns: ssaCols, data: ssaData },
    };
    const target = map[activeTab] || map.dsp;
    navigator.clipboard.writeText(toTSV(target.columns, filterData(target.data, searchQuery))).catch(() => {});
  };

  if (authLoading) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0d0f18' }}>
        <Spin size="large" />
      </div>
    );
  }
  if (!user) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <LoginPage onSignIn={signIn} />
      </ConfigProvider>
    );
  }

  // User clicked a password-reset link — show set-password modal before anything else
  if (needsPasswordReset) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <SetPasswordScreen updatePassword={updatePassword} signOut={signOut} setActiveModule={setActiveModule} email={user?.email} />
      </ConfigProvider>
    );
  }

  if (activeModule === null) {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <ModulePicker
          user={user}
          profile={profile}
          role={(viewAsRole ?? authRole) ?? 'viewer'}
          actualRole={authRole ?? 'viewer'}
          viewAsRole={viewAsRole}
          onRoleSwitch={(r) => {
            if (r === null) { setViewAsRole(null); setEditMode(authRole === 'admin' || authRole === 'tl'); }
            else { setViewAsRole(r); setEditMode(false); }
          }}
          onSelect={(mod) => setActiveModule(mod)}
          onSignOut={() => { signOut(); setActiveModule(null); }}
        />
      </ConfigProvider>
    );
  }

  if (activeModule === 'kt') {
    return (
      <ConfigProvider theme={DARK_THEME}>
        <KTSessionsPage onBack={() => setActiveModule(null)} />
      </ConfigProvider>
    );
  }

  // ── Standalone: Roles & Access + MyISP Module Roles (tabbed) ──
  if (activeModule === 'rolesaccess') {
    const _role = viewAsRole ?? authRole ?? 'viewer';
    if (!(ROLES[_role]?.canViewRolesAccess)) { setActiveModule(null); return null; }
    return (
      <ConfigProvider theme={DARK_THEME}>
        <div style={{ minHeight: '100vh', background: '#0d0f18' }}>
          <div style={{
            height: 52, background: '#0f1117', borderBottom: '1px solid #1e2332',
            display: 'flex', alignItems: 'center', padding: '0 16px', gap: 12,
            position: 'sticky', top: 0, zIndex: 100,
          }}>
            <Button
              size="small" type="text"
              icon={React.createElement(ShieldCheck, { size: 14, color: '#22c55e' })}
              onClick={() => setActiveModule(null)}
              style={{ color: '#8892a4', fontSize: 12 }}
            >
              ← Back to Modules
            </Button>
          </div>
          <AccessSheet currentUser={user.email} role={_role} />
        </div>
      </ConfigProvider>
    );
  }

  const currentUser = user.email;
  const actualRole  = authRole ?? 'viewer';
  const role        = viewAsRole ?? actualRole;
  const anyDirty    = Object.values(dirtyModules).some(Boolean);
  const roleConfig  = ROLES[role] || ROLES.viewer;
  const RoleIcon    = roleConfig.icon;
  const displayName = profile && profile.display_name ? profile.display_name : user.email;

  const DotDirty = ({ dirty }) => dirty
    ? <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#f59e0b', display: 'inline-block', marginLeft: 4, verticalAlign: 'middle' }} />
    : null;

  const navItems = [
    { key: 'home',   icon: React.createElement(Home,    { size: 15 }), label: 'Home' },
    {
      key: 'dsp',
      icon: React.createElement(Monitor, { size: 15 }),
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'DSP',
        React.createElement(Badge, { count: dspManual.length + dspAuto.length, style: { background: 'rgba(34,197,94,0.15)', color: '#22c55e', border: '1px solid rgba(34,197,94,0.3)', fontSize: 9, boxShadow: 'none' } }),
        React.createElement(DotDirty, { dirty: dirtyModules.dsp })
      ),
    },
    {
      key: 'ssa',
      icon: React.createElement(Shield, { size: 15 }),
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'SSA',
        React.createElement(Badge, { count: ssaData.length, style: { background: 'rgba(139,92,246,0.15)', color: '#8b5cf6', border: '1px solid rgba(139,92,246,0.3)', fontSize: 9, boxShadow: 'none' } }),
        React.createElement(DotDirty, { dirty: dirtyModules.ssa })
      ),
    },
    {
      key: 'team',
      icon: React.createElement(Users, { size: 15 }),
      label: React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 4 } },
        'Team',
        React.createElement(Badge, { count: teamData.length, style: { background: 'rgba(6,182,212,0.15)', color: '#06b6d4', border: '1px solid rgba(6,182,212,0.3)', fontSize: 9, boxShadow: 'none' } }),
        React.createElement(DotDirty, { dirty: dirtyModules.team })
      ),
    },
  ]
   .concat(roleConfig.canViewReport  ? [{ key: 'report', icon: React.createElement(FileText, { size: 15 }), label: 'Report' }] : [])
   .concat(roleConfig.canViewLogs    ? [{ key: 'logs',   icon: React.createElement(Activity, { size: 15 }), label: 'Logs'   }] : [])
   .concat(roleConfig.canManageUsers ? [{ key: 'users',  icon: React.createElement(UserCog,  { size: 15 }), label: 'Users'  }] : []);

  const renderSheet = () => {
    switch (activeTab) {
      case 'home':
        return (
          <HomePage
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} setActiveTab={setActiveTab}
            currentUser={currentUser} role={role} profile={profile}
          />
        );
      case 'dsp':
        return (
          <DSPSheet
            searchQuery={searchQuery}
            dspManual={dspManual} setDspManual={setDspManual}
            dspAuto={dspAuto}     setDspAuto={setDspAuto}
            editMode={editMode}   currentUser={currentUser} role={role}
            onSave={() => saveModule('dsp')} isDirty={dirtyModules.dsp} lastSaved={lastSaved.dsp}
            loading={dataLoading}
          />
        );
      case 'ssa':
        return (
          <SSASheet
            searchQuery={searchQuery} ssaData={ssaData} setSsaData={setSsaData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('ssa')} isDirty={dirtyModules.ssa} lastSaved={lastSaved.ssa}
            loading={dataLoading}
          />
        );
      case 'team':
        return (
          <TeamSheet
            searchQuery={searchQuery} teamData={teamData} setTeamData={setTeamData}
            editMode={editMode}       currentUser={currentUser} role={role}
            onSave={() => saveModule('team')} isDirty={dirtyModules.team} lastSaved={lastSaved.team}
            loading={dataLoading}
          />
        );
      case 'report':
        if (!roleConfig.canViewReport) return null;
        return (
          <ReportSheet
            dspManual={dspManual} dspAuto={dspAuto} ssaData={ssaData} teamData={teamData}
            selectedMonth={selectedMonth} role={role}
          />
        );
      case 'logs':
        if (!roleConfig.canViewLogs) return null;
        return React.createElement(ActivityLogSheet, { currentUser, role, dspManual, dspAuto, ssaData, selectedMonth });
      case 'users':
        if (!roleConfig.canManageUsers) return null;
        return React.createElement(UsersSheet, { currentUserId: user.id, role, currentUserEmail: currentUser });
      default:
        return null;
    }
  };

  return (
    <ConfigProvider theme={DARK_THEME}>
      <Layout style={{ minHeight: '100vh', background: '#0d0f18' }}>

        <Sider
          collapsible
          collapsed={collapsed}
          onCollapse={setCollapsed}
          width={210}
          collapsedWidth={60}
          style={{ background: '#0f1117', borderRight: '1px solid #1e2332' }}
        >
          <div style={{
            padding: collapsed ? '16px 13px' : '14px 16px',
            borderBottom: '1px solid #1e2332',
            display: 'flex', alignItems: 'center', gap: 10,
            minHeight: 60,
          }}>
            <Tooltip title="Back to Modules">
              <div
                onClick={() => setActiveModule(null)}
                style={{
                  width: 34, height: 34, borderRadius: 9, flexShrink: 0,
                  background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 14px rgba(34,197,94,0.25)',
                  cursor: 'pointer',
                }}
              >
                <LayoutDashboard size={18} color="#fff" />
              </div>
            </Tooltip>
            {!collapsed && (
              <div style={{ overflow: 'hidden', cursor: 'pointer' }} onClick={() => setActiveModule(null)}>
                <span style={{ color: '#e2e8f0', fontSize: 13, fontWeight: 700, display: 'block', lineHeight: 1.3, whiteSpace: 'nowrap' }}>MyISP</span>
                <span style={{ color: '#4b5568', fontSize: 10 }}>◀ Modules</span>
              </div>
            )}
          </div>

          <Menu
            mode="inline"
            theme="dark"
            selectedKeys={[activeTab]}
            items={navItems}
            onClick={({ key }) => { setActiveTab(key); setSearchQuery(''); }}
            inlineCollapsed={collapsed}
            style={{ background: 'transparent', border: 'none', marginTop: 6 }}
          />

        </Sider>

        <Layout style={{ background: '#0d0f18' }}>
          <Header style={{
            background: '#131720',
            borderBottom: '1px solid #1e2332',
            height: 52,
            padding: '0 14px',
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            lineHeight: 'normal',
            position: 'sticky',
            top: 0,
            zIndex: 100,
          }}>
            <Select
              size="small"
              value={selectedMonth}
              onChange={handleMonthChange}
              options={MONTH_OPTIONS}
              style={{ width: 155, flexShrink: 0 }}
              popupMatchSelectWidth={false}
              suffixIcon={React.createElement(Calendar, { size: 12, color: '#4b5568' })}
            />

            <Input
              placeholder={'Search ' + (activeTab === 'home' ? 'all' : activeTab) + '…'}
              prefix={React.createElement(Search, { size: 12, color: '#4b5568' })}
              value={searchQuery}
              onChange={function(e) { setSearchQuery(e.target.value); }}
              allowClear
              size="small"
              style={{ flex: 1, maxWidth: 360 }}
            />

            {anyDirty && (
              <Tag icon={React.createElement(AlertTriangle, { size: 10 })} color="warning" style={{ margin: 0, flexShrink: 0 }}>
                Unsaved
              </Tag>
            )}

            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6 }}>

              {/* Edit / View toggle */}
              {(role === 'admin' || role === 'tl') && (
                <Segmented
                  size="small"
                  value="edit"
                  options={[
                    { value: 'edit', label: React.createElement(Space, { size: 3 }, React.createElement(PenTool, { size: 11 }), 'Edit') },
                  ]}
                />
              )}
              {role === 'tester' && (
                <Segmented
                  size="small"
                  value={editMode ? 'edit' : 'view'}
                  onChange={function(v) { setEditMode(v === 'edit'); }}
                  options={[
                    { value: 'view', label: React.createElement(Space, { size: 3 }, React.createElement(Eye, { size: 11 }), 'View') },
                    { value: 'edit', label: React.createElement(Space, { size: 3 }, React.createElement(PenTool, { size: 11 }), 'Edit') },
                  ]}
                />
              )}

              {/* Save button — always visible for non-viewers */}
              {role !== 'viewer' && (
                <Tooltip title={anyDirty ? 'Save all unsaved changes' : 'No unsaved changes'}>
                  <Button
                    size="small"
                    icon={React.createElement(Save, { size: 12 })}
                    onClick={saveAllModules}
                    disabled={!anyDirty}
                    type={anyDirty ? 'primary' : 'default'}
                    style={anyDirty ? { background: '#22c55e', borderColor: '#22c55e', color: '#fff', fontWeight: 600 } : {}}
                  >
                    Save
                  </Button>
                </Tooltip>
              )}

              <Tooltip title="Copy current sheet as TSV (Excel-ready)">
                <Button size="small" icon={React.createElement(Copy, { size: 12 })} onClick={handleCopy}>
                  Copy
                </Button>
              </Tooltip>

              {/* Divider */}
              <div style={{ width: 1, height: 20, background: '#1e2332', margin: '0 4px' }} />

              {/* Profile dropdown */}
              {React.createElement(Dropdown, {
                trigger: ['click'],
                menu: {
                  items: [
                    { type: 'group', label: displayName },
                    {
                      key: 'role-info',
                      label: React.createElement('div', { style: { padding: '4px 0', pointerEvents: 'none' } },
                        React.createElement('div', { style: { fontSize: 10, color: '#8892a4', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 } }, 'Your Role'),
                        React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 } },
                          React.createElement(RoleIcon, { size: 13, color: roleConfig.color }),
                          React.createElement('span', { style: { color: roleConfig.color, fontWeight: 700, fontSize: 12 } }, roleConfig.label),
                          viewAsRole && React.createElement(Tag, { color: 'orange', style: { margin: 0, fontSize: 10 } }, 'Previewing')
                        ),
                        React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 3 } },
                          ...[
                            ['Edit data',    roleConfig.canEdit],
                            ['Delete rows',  roleConfig.canDelete],
                            ['Add rows',     roleConfig.canAddRow],
                            ['Own rows only',roleConfig.onlyOwnRows],
                          ].map(([perm, allowed]) =>
                            React.createElement('div', { key: perm, style: { display: 'flex', alignItems: 'center', gap: 5, fontSize: 11 } },
                              React.createElement('span', { style: { color: allowed ? '#22c55e' : '#6b7280', fontSize: 13, lineHeight: 1 } }, allowed ? '✓' : '✗'),
                              React.createElement('span', { style: { color: allowed ? '#e2e8f0' : '#6b7280' } }, perm)
                            )
                          )
                        )
                      ),
                    },
                    { type: 'divider' },
                    // Switch Role View — only shown to admin (preview mode)
                    ...(actualRole === 'admin' ? [
                      { type: 'group', label: 'Switch Role View' },
                      ...['admin','tl','tester','viewer'].map((r) => {
                        const rc = ROLES[r];
                        const RIcon = rc.icon;
                        const isCurrentActual = r === actualRole && !viewAsRole;
                        const isActive = viewAsRole === r || isCurrentActual;
                        return {
                          key: 'preview-' + r,
                          label: React.createElement('div', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 } },
                            React.createElement('span', { style: { display: 'flex', alignItems: 'center', gap: 6, color: rc.color, fontWeight: isActive ? 700 : 400 } },
                              React.createElement(RIcon, { size: 12 }),
                              rc.label
                            ),
                            isCurrentActual
                              ? React.createElement(Tag, { color: 'green', style: { margin: 0, fontSize: 10 } }, 'Current')
                              : isActive
                                ? React.createElement(Tag, { color: 'orange', style: { margin: 0, fontSize: 10 } }, 'Active')
                                : null
                          ),
                          onClick: () => {
                            if (isCurrentActual) return;
                            if (viewAsRole === r) { setViewAsRole(null); setEditMode(actualRole === 'admin' || actualRole === 'tl'); }
                            else { setViewAsRole(r); setEditMode(false); }
                            setActiveTab('home');
                          },
                        };
                      }),
                      { type: 'divider' },
                    ] : []),
                    { key: 'signout', label: React.createElement('span', { style: { color: '#f87171' } }, 'Sign out'), onClick: () => { signOut(); setActiveModule(null); } },
                  ],
                },
                children: React.createElement('div', {
                  style: { display: 'flex', alignItems: 'center', gap: 6, padding: '3px 8px', borderRadius: 8, background: '#1a2035', border: '1px solid #1e2332', cursor: 'pointer' }
                },
                  React.createElement('div', { style: { width: 22, height: 22, borderRadius: '50%', background: 'linear-gradient(135deg, #22c55e, #16a34a)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 } },
                    React.createElement(RoleIcon, { size: 11, color: '#fff' })
                  ),
                  React.createElement('div', { style: { lineHeight: 1.2, maxWidth: 160 } },
                    React.createElement('div', { style: { color: '#e2e8f0', fontSize: 11, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }, title: displayName }, displayName),
                    React.createElement('div', { style: { color: roleConfig.color, fontSize: 10, fontWeight: 700 } }, roleConfig.label)
                  )
                )
              })}



              <Tooltip title="Export month data as JSON">
                <Button size="small" icon={React.createElement(Download, { size: 12 })} onClick={handleExportJSON}>
                  Export
                </Button>
              </Tooltip>
            </div>
          </Header>

          <Content style={{ background: '#0d0f18', overflow: 'auto' }}>
            {viewAsRole && (
              <div style={{ background: '#92400e', color: '#fef3c7', padding: '6px 16px', fontSize: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span>Previewing as <strong>{ROLES[viewAsRole].label}</strong> — changes are disabled in preview mode</span>
                <Button size="small" onClick={() => { setViewAsRole(null); setEditMode(false); }} style={{ fontSize: 11 }}>Exit Preview</Button>
              </div>
            )}
            {dirtyModules[activeTab] && (
              <div style={{
                position: 'sticky', top: 0, zIndex: 90,
                background: 'rgba(245,158,11,0.12)',
                borderBottom: '1px solid rgba(245,158,11,0.3)',
                padding: '6px 16px',
                display: 'flex', alignItems: 'center', gap: 10,
              }}>
                {React.createElement(AlertTriangle, { size: 13, color: '#f59e0b' })}
                <span style={{ color: '#fbbf24', fontSize: 12, flex: 1 }}>
                  You have unsaved changes on this sheet.
                </span>
                <Button
                  size="small"
                  onClick={() => saveModule(activeTab)}
                  style={{ background: '#f59e0b', borderColor: '#f59e0b', color: '#fff', fontWeight: 600 }}
                >
                  Save Now
                </Button>
              </div>
            )}
            {renderSheet()}
          </Content>
        </Layout>
      </Layout>

      <FloatButton.BackTop style={{ right: 24, bottom: 24 }} />
    </ConfigProvider>
  );
}

export default App;
