// Generated by GitHub Copilot
import { Tabs, Space } from 'antd';
import { ShieldCheck, KeyRound, SlidersHorizontal } from 'lucide-react';
import RolesAccessSheet          from './RolesAccessSheet.jsx';
import MyIspModuleRolesSheet     from './MyIspModuleRolesSheet.jsx';
import PermissionDesignerSheet   from './PermissionDesignerSheet.jsx';

/**
 * AccessSheet — tabbed container combining Roles & Access and MyISP Module Roles.
 * Both sub-sheets are admin/tl-only; access is guarded at the App level before render.
 * @param {{ currentUser: string, role: string }} props
 */
export default function AccessSheet({ currentUser, role }) {
  return (
    <Tabs
      defaultActiveKey="roles"
      size="small"
      style={{ padding: '0 20px' }}
      items={[
        {
          key: 'roles',
          label: (
            <Space size={6}>
              <ShieldCheck size={13} />
              Roles &amp; Access
            </Space>
          ),
          children: <RolesAccessSheet currentUser={currentUser} role={role} />,
        },
        {
          key: 'myisp',
          label: (
            <Space size={6}>
              <KeyRound size={13} />
              MyISP Module Roles
            </Space>
          ),
          children: <MyIspModuleRolesSheet currentUser={currentUser} role={role} />,
        },
        {
          key: 'permissions',
          label: (
            <Space size={6}>
              <SlidersHorizontal size={13} />
              Permission Designer
            </Space>
          ),
          children: <PermissionDesignerSheet role={role} />,
        },
      ]}
    />
  );
}
