// Generated by GitHub Copilot
import { Tabs, Space } from 'antd';
import { ShieldCheck, KeyRound, SlidersHorizontal, Users } from 'lucide-react';
import RolesAccessSheet          from './RolesAccessSheet.jsx';
import ProdRolesSheet            from './ProdRolesSheet.jsx';
import MyIspModuleRolesSheet     from './MyIspModuleRolesSheet.jsx';
import PermissionDesignerSheet   from './PermissionDesignerSheet.jsx';
import UsersSheet                from './UsersSheet.jsx';

/**
 * AccessSheet — tabbed container for all user/role management.
 * Access is guarded at the App level before render.
 * @param {{ currentUser: string, currentUserId: string, role: string }} props
 */
export default function AccessSheet({ currentUser, currentUserId, role }) {
  return (
    <Tabs
      defaultActiveKey="users"
      size="small"
      style={{ padding: '0 20px' }}
      items={[
        {
          key: 'users',
          label: (
            <Space size={6}>
              <Users size={13} />
              Users
            </Space>
          ),
          children: <UsersSheet currentUserId={currentUserId} role={role} currentUserEmail={currentUser} />,
        },
        {
          key: 'roles',
          label: (
            <Space size={6}>
              <ShieldCheck size={13} />
              Prod Roles
            </Space>
          ),
          children: <RolesAccessSheet currentUser={currentUser} role={role} />,
        },
        {
          key: 'prod-roles',
          label: (
            <Space size={6}>
              <Users size={13} />
              Team Roles
            </Space>
          ),
          children: <ProdRolesSheet currentUser={currentUser} role={role} />,
        },
        {
          key: 'myisp',
          label: (
            <Space size={6}>
              <KeyRound size={13} />
              MyISP Module Roles
            </Space>
          ),
          children: <MyIspModuleRolesSheet currentUser={currentUser} role={role} />,
        },
        {
          key: 'permissions',
          label: (
            <Space size={6}>
              <SlidersHorizontal size={13} />
              Permission Designer
            </Space>
          ),
          children: <PermissionDesignerSheet role={role} />,
        },
      ]}
    />
  );
}
