// Generated by GitHub Copilot
import { useEffect, useState } from 'react';
import {
  Table, Tag, Typography, Card, message, Skeleton, Modal, Form, Input,
  Button, Space, Select, Tooltip, Switch,
} from 'antd';
import { KeyRound, RefreshCw, Plus, Trash2, Edit3, X, User } from 'lucide-react';
import { fetchMyIspModuleRoles, upsertMyIspRow, deleteMyIspRow } from '../../services/api.js';

const { Text } = Typography;

/** Roles available in the DS Domain / MyISP context */
const DS_ROLE_OPTIONS = [
  'Lead SA Technology',
  'Lead SA migrate tech',
  'Support SA Technology',
  'Advisory Song SA',
  'Configurator V2V',
  'Overall Song Delivery Approver',
  'Super User',
  'Operation User',
  'Central PMO',
  'Business Group PMO',
  'Service Level PMO',
  'APG/APD User',
  'PCAT PMO',
  'Lead SA Data Tech',
  'Support SA Song',
  'Mobilization SME',
  'Reviewer/Approver - Overall Song Delivery Approver',
  'Reviewer/Approver - CDAT Reviewer',
  'Lead SA S&C',
  'Lead SA Security',
  'Lead SA Song',
  'Lead SA Operations',
  'SA Operations',
  'Lead SA Tech for Ops',
  'Support SA Tech for Ops',
  'Market Maker ESA',
  'CXTA User',
  'Transformation Solution Architect',
  'Lead SA BPMS',
  'PCAT Lead',
  'Market Delivery Lead',
  'SA Team Manager',
  'CDAT Lead',
].map((v) => ({ value: v, label: v }));

/** Colour for role tags */
const roleTagColor = (r) => {
  if (r.includes('Lead SA')) return 'blue';
  if (r.includes('Support SA')) return 'cyan';
  if (r.includes('Operation User') || r.includes('Super User')) return 'red';
  if (r.includes('PMO') || r === 'SA Team Manager') return 'orange';
  if (r.includes('Configurator')) return 'geekblue';
  if (r.includes('Advisory')) return 'purple';
  if (r.includes('Reviewer')) return 'volcano';
  if (r === 'CDAT Lead') return 'lime';
  return 'default';
};

/**
 * MyIspModuleRolesSheet — DS Domain test account registry.
 * One row per module entry with DS Domain IDs, assignees, roles, and MMS IDs.
 * Card title and icon are unchanged per product spec.
 * Only accessible by admin and tl. Backed by myisp_module_roles Supabase table.
 * @param {{ currentUser: string, role: string }} props
 */
export default function MyIspModuleRolesSheet({ currentUser, role }) {
  const [rows,      setRows]      = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [search,    setSearch]    = useState('');
  const [editRow,   setEditRow]   = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [saving,    setSaving]    = useState(false);
  const [deleting,  setDeleting]  = useState(null);
  const [form]      = Form.useForm();

  const canEdit   = role === 'admin' || role === 'tl';
  const canDelete = role === 'admin';

  // ── Load ──────────────────────────────────────────────────
  const load = () => {
    setLoading(true);
    fetchMyIspModuleRoles()
      .then(setRows)
      .catch((e) => message.error('Failed to load: ' + e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  // ── Access guard ──────────────────────────────────────────
  if (role !== 'admin' && role !== 'tl') {
    return (
      <div style={{ padding: 24 }}>
        <Card><Text type="secondary">Access restricted. Admins and Super Users only.</Text></Card>
      </div>
    );
  }

  // ── Search filter ─────────────────────────────────────────
  const filtered = rows.filter((r) => {
    if (!search) return true;
    const q = search.toLowerCase();
    return (
      r.module?.toLowerCase().includes(q) ||
      (r.assignees ?? []).join(' ').toLowerCase().includes(q) ||
      (r.ds_domain_ids ?? []).join(' ').toLowerCase().includes(q) ||
      r.ds_domain_id?.toLowerCase().includes(q)
    );
  });

  // ── Modal helpers ─────────────────────────────────────────
  const openAdd = () => {
    setEditRow(null);
    form.resetFields();
    setModalOpen(true);
  };

  const openEdit = (rec) => {
    setEditRow(rec);
    form.setFieldsValue({
      sno:              rec.sno ?? '',
      module:           rec.module ?? '',
      assignees_raw:    (rec.assignees ?? []).join('\n'),
      ds_domain_ids_raw:(rec.ds_domain_ids ?? []).join('\n'),
      roles:            rec.roles ?? [],
      mms_ids_raw:      (rec.mms_ids ?? []).join('\n'),
      create_interim:   rec.create_interim ?? false,
    });
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setEditRow(null);
    form.resetFields();
  };

  // ── Save ──────────────────────────────────────────────────
  const handleSave = async (values) => {
    setSaving(true);
    try {
      const mms_ids = (values.mms_ids_raw ?? '').trim()
        ? (values.mms_ids_raw).trim().split('\n').map((s) => s.trim()).filter(Boolean)
        : [];
      const ds_domain_ids = (values.ds_domain_ids_raw ?? '').trim()
        ? (values.ds_domain_ids_raw).trim().split('\n').map((s) => s.trim()).filter(Boolean)
        : [];
      const assignees = (values.assignees_raw ?? '').trim()
        ? (values.assignees_raw).trim().split('\n').map((s) => s.trim()).filter(Boolean)
        : [];

      const row = {
        ...(editRow?.id ? { id: editRow.id } : {}),
        sno:            values.sno ? Number(values.sno) : null,
        module:         values.module?.trim() ?? '',
        assignees,
        ds_domain_ids,
        ds_domain_id:   ds_domain_ids[0] ?? '',
        roles:          values.roles ?? [],
        mms_ids,
        create_interim: values.create_interim ?? false,
        last_edited_by: currentUser,
        last_edited_at: new Date().toISOString(),
      };
      await upsertMyIspRow(row);
      message.success(editRow ? 'Row updated' : 'Row added');
      closeModal();
      load();
    } catch (e) {
      message.error('Save failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────
  const handleDelete = (rec) => {
    Modal.confirm({
      title:   'Delete Row',
      content: `Remove ${rec.module} (SNO ${rec.sno ?? '—'})?`,
      okText:  'Delete',
      okType:  'danger',
      onOk: async () => {
        setDeleting(rec.id);
        try {
          await deleteMyIspRow(rec.id);
          setRows((prev) => prev.filter((r) => r.id !== rec.id));
          message.success('Row deleted');
        } catch (e) {
          message.error('Delete failed: ' + e.message);
        } finally {
          setDeleting(null);
        }
      },
    });
  };

  // ── Columns ───────────────────────────────────────────────
  const cols = [
    {
      title: 'S.No', dataIndex: 'sno', key: 'sno', width: 55,
      sorter: (a, b) => (a.sno ?? 999) - (b.sno ?? 999),
      render: (v) => <Text type="secondary" style={{ fontSize: 11 }}>{v ?? '—'}</Text>,
    },
    {
      title: 'Module', dataIndex: 'module', key: 'module', width: 140,
      render: (v) => <Text strong style={{ fontSize: 12 }}>{v}</Text>,
    },
    {
      title: 'Assignees', dataIndex: 'assignees', key: 'assignees', width: 200,
      render: (assignees) => (
        <Space size={[4, 4]} wrap>
          {(assignees ?? []).map((a) => (
            <Tag key={a} icon={<User size={10} />} color="blue" style={{ fontSize: 10, marginBottom: 2 }}>{a}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'DS Domain IDs', dataIndex: 'ds_domain_ids', key: 'ds_domain_ids', width: 260,
      render: (ids) => (
        <Space size={[4, 4]} wrap>
          {(ids ?? []).map((id) => (
            <Text key={id} code style={{ fontSize: 10, display: 'inline-block', marginBottom: 2 }}>{id}</Text>
          ))}
        </Space>
      ),
    },
    {
      title: 'Roles', dataIndex: 'roles', key: 'roles',
      render: (roles) => (
        <Space size={[4, 4]} wrap>
          {(roles ?? []).map((r) => (
            <Tag key={r} color={roleTagColor(r)} style={{ fontSize: 10, marginBottom: 2 }}>{r}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'MMS IDs', dataIndex: 'mms_ids', key: 'mms_ids', width: 220,
      render: (ids) => (
        <Space size={[4, 4]} wrap>
          {(ids ?? []).map((id) => (
            <Tag key={id} color="default" style={{ fontSize: 10, fontFamily: 'monospace', marginBottom: 2 }}>{id}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'Create Interim', dataIndex: 'create_interim', key: 'create_interim', width: 110,
      filters: [{ text: 'Yes', value: true }, { text: 'No', value: false }],
      onFilter: (value, record) => record.create_interim === value,
      render: (v) => (
        <Tag color={v ? 'green' : 'default'} style={{ fontSize: 11 }}>{v ? 'Yes' : 'No'}</Tag>
      ),
    },
    {
      title: 'Last Edited', dataIndex: 'last_edited_at', key: 'last_edited_at', width: 130,
      render: (v) => v
        ? <Text type="secondary" style={{ fontSize: 11 }}>{new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</Text>
        : '—',
    },
    {
      title: 'Actions', key: 'actions', width: 80, fixed: 'right',
      render: (_, rec) => (
        <Space size={4}>
          {canEdit && (
            <Tooltip title="Edit">
              <Button
                size="small" type="text"
                icon={<Edit3 size={13} color="#8892a4" />}
                onClick={() => openEdit(rec)}
              />
            </Tooltip>
          )}
          {canDelete && (
            <Tooltip title="Delete">
              <Button
                size="small" type="text"
                loading={deleting === rec.id}
                icon={<Trash2 size={13} color="#f87171" />}
                onClick={() => handleDelete(rec)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    },
  ];

  // ── Stats ─────────────────────────────────────────────────
  const withInterim    = rows.filter((r) => r.create_interim).length;
  const withoutInterim = rows.length - withInterim;

  // ── Render ─────────────────────────────────────────────────
  return (
    <div style={{ padding: 20 }}>

      {/* Summary cards */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
        {[
          { label: 'Total Entries',  value: rows.length,     color: 'var(--accent)' },
          { label: 'Create Interim', value: withInterim,     color: '#f59e0b' },
          { label: 'No Interim',     value: withoutInterim,  color: '#8892a4' },
        ].map(({ label, value, color }) => (
          <Card key={label} size="small" style={{ flex: '1 1 120px', borderTop: `3px solid ${color}`, background: 'var(--bg-card)' }}>
            <Text type="secondary" style={{ fontSize: 11, display: 'block' }}>{label}</Text>
            <div style={{ fontSize: 24, fontWeight: 700, color, lineHeight: 1.3 }}>{value}</div>
          </Card>
        ))}
      </div>

      {/* Main table */}
      <Card
        title={
          <Space>
            <KeyRound size={15} />
            <span>MyISP Module Roles</span>
            <Tag style={{ fontSize: 10 }}>{rows.length} entries</Tag>
          </Space>
        }
        styles={{ header: { borderBottom: '1px solid #252d42' } }}
        extra={
          <Space size={6}>
            <Input.Search
              size="small" placeholder="Search module or assignee…"
              value={search} onChange={(e) => setSearch(e.target.value)}
              style={{ width: 240 }} allowClear
            />
            <Tooltip title="Refresh">
              <Button size="small" icon={<RefreshCw size={13} />} onClick={load} loading={loading} />
            </Tooltip>
            {canEdit && (
              <Button
                type="primary" size="small" icon={<Plus size={13} />}
                onClick={openAdd}
                style={{ background: 'var(--accent)', borderColor: 'var(--accent-dim)' }}
              >
                Add Row
              </Button>
            )}
          </Space>
        }
      >
        {loading ? (
          <Skeleton active paragraph={{ rows: 8 }} />
        ) : (
          <Table
            dataSource={filtered}
            columns={cols}
            rowKey="id"
            size="small"
            scroll={{ x: 1200 }}
            pagination={{ pageSize: 20, showSizeChanger: false, showTotal: (t) => `${t} entries` }}
          />
        )}
      </Card>

      {/* Add / Edit modal */}
      <Modal
        title={
          <Space>
            {editRow ? <Edit3 size={14} /> : <Plus size={14} />}
            {editRow ? 'Edit Module Row' : 'Add Module Row'}
          </Space>
        }
        open={modalOpen}
        onCancel={closeModal}
        footer={null}
        width={580}
        destroyOnClose
      >
        <Form form={form} layout="vertical" onFinish={handleSave} style={{ marginTop: 8 }}>

          <Space style={{ width: '100%' }} size={12}>
            <Form.Item name="sno" label="S.No" style={{ width: 80, marginBottom: 12 }}>
              <Input type="number" placeholder="1" size="middle" min={1} />
            </Form.Item>
            <Form.Item
              name="module" label="Module"
              rules={[{ required: true, message: 'Required' }]}
              style={{ flex: 1, marginBottom: 12 }}
            >
              <Input placeholder="e.g. NextGen" size="middle" />
            </Form.Item>
          </Space>

          <Form.Item name="assignees_raw" label="Assignees (one per line)">
            <Input.TextArea
              rows={3}
              placeholder={'saranya.datla\nn.selvakumar'}
              style={{ fontSize: 12 }}
            />
          </Form.Item>

          <Form.Item
            name="ds_domain_ids_raw" label="DS Domain IDs (one per line)"
            tooltip="Enter each DS Domain ID on a separate line"
          >
            <Input.TextArea
              rows={4}
              placeholder={'T5364.9044@ds.dev.accenture.com\nT5364.9042@ds.dev.accenture.com'}
              style={{ fontFamily: 'monospace', fontSize: 12 }}
            />
          </Form.Item>

          <Form.Item name="roles" label="Roles">
            <Select
              mode="multiple" size="middle"
              options={DS_ROLE_OPTIONS}
              placeholder="Select one or more roles…"
              allowClear
              maxTagCount="responsive"
            />
          </Form.Item>

          <Form.Item
            name="mms_ids_raw" label="MMS IDs (one per line)"
            tooltip="Enter each MMS ID on a separate line"
          >
            <Input.TextArea
              rows={3}
              placeholder={'0012465874\n0012466013\nTECH-8000001233'}
              style={{ fontFamily: 'monospace', fontSize: 12 }}
            />
          </Form.Item>

          <Form.Item name="create_interim" label="Create Interim" valuePropName="checked">
            <Switch checkedChildren="Yes" unCheckedChildren="No" />
          </Form.Item>

          <Form.Item style={{ marginBottom: 0 }}>
            <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
              <Button icon={<X size={13} />} onClick={closeModal}>Cancel</Button>
              <Button
                type="primary" htmlType="submit" loading={saving}
                style={{ background: 'var(--accent)', borderColor: 'var(--accent-dim)' }}
              >
                {editRow ? 'Save Changes' : 'Add Row'}
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}

