// Generated by GitHub Copilot
import { useEffect, useState } from 'react';
import {
  Table, Tag, Typography, Card, message, Spin, Modal, Form, Input,
  Button, Space, Select, Tooltip, Switch,
} from 'antd';
import { KeyRound, RefreshCw, Plus, Trash2, Edit3, X } from 'lucide-react';
import { fetchMyIspModuleRoles, upsertMyIspRow, deleteMyIspRow } from '../../services/api.js';

const { Text } = Typography;

/** Roles available in the DS Domain / MyISP context */
const DS_ROLE_OPTIONS = [
  'Lead SA Technology',
  'Lead SA migrate tech',
  'Support SA Technology',
  'Advisory Song SA',
  'Configurator V2V',
  'Overall Song Delivery Approver',
  'Super User',
  'Operation User',
  'Central PMO',
  'Business Group PMO',
  'Service Level PMO',
  'APG/APD User',
  'PCAT PMO',
  'Lead SA Data Tech',
  'Support SA Song',
  'Mobilization SME',
  'Reviewer/Approver - Overall Song Delivery Approver',
  'Reviewer/Approver - CDAT Reviewer',
  'Lead SA S&C',
  'Lead SA Security',
  'Lead SA Song',
  'Lead SA Operations',
  'SA Operations',
  'Lead SA Tech for Ops',
  'Support SA Tech for Ops',
  'Market Maker ESA',
  'CXTA User',
  'Transformation Solution Architect',
  'Lead SA BPMS',
  'PCAT Lead',
  'Market Delivery Lead',
].map((v) => ({ value: v, label: v }));

/** Colour for role tags */
const roleTagColor = (r) => {
  if (r.includes('Lead SA')) return 'blue';
  if (r.includes('Support SA')) return 'cyan';
  if (r.includes('Operation User') || r.includes('Super User')) return 'red';
  if (r.includes('PMO')) return 'orange';
  if (r.includes('Configurator')) return 'geekblue';
  if (r.includes('Advisory')) return 'purple';
  if (r.includes('Reviewer')) return 'volcano';
  return 'default';
};

/**
 * MyIspModuleRolesSheet — DS Domain test account registry.
 * Displays one row per DS Domain email ID with roles, MMS IDs, and interim flag.
 * Only accessible by admin and tl. Backed by myisp_module_roles Supabase table.
 * @param {{ currentUser: string, role: string }} props
 */
export default function MyIspModuleRolesSheet({ currentUser, role }) {
  const [rows,     setRows]      = useState([]);
  const [loading,  setLoading]   = useState(true);
  const [search,   setSearch]    = useState('');
  const [editRow,  setEditRow]   = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [saving,   setSaving]    = useState(false);
  const [deleting, setDeleting]  = useState(null);
  const [form]     = Form.useForm();

  const canEdit   = role === 'admin' || role === 'tl';
  const canDelete = role === 'admin';

  // ── Load ──────────────────────────────────────────────────
  const load = () => {
    setLoading(true);
    fetchMyIspModuleRoles()
      .then(setRows)
      .catch((e) => message.error('Failed to load: ' + e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  // ── Access guard ──────────────────────────────────────────
  if (role !== 'admin' && role !== 'tl') {
    return (
      <div style={{ padding: 24 }}>
        <Card><Text type="secondary">Access restricted. Admins and Super Users only.</Text></Card>
      </div>
    );
  }

  // ── Search filter ─────────────────────────────────────────
  const filtered = rows.filter((r) => {
    if (!search) return true;
    const q = search.toLowerCase();
    return r.ds_domain_id?.toLowerCase().includes(q);
  });

  // ── Modal helpers ─────────────────────────────────────────
  const openAdd = () => {
    setEditRow(null);
    form.resetFields();
    setModalOpen(true);
  };

  const openEdit = (rec) => {
    setEditRow(rec);
    form.setFieldsValue({
      ds_domain_id:   rec.ds_domain_id,
      roles:          rec.roles ?? [],
      mms_ids_raw:    (rec.mms_ids ?? []).join('\n'),
      create_interim: rec.create_interim ?? false,
    });
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setEditRow(null);
    form.resetFields();
  };

  // ── Save ──────────────────────────────────────────────────
  const handleSave = async (values) => {
    setSaving(true);
    try {
      // mms_ids stored as text[] — user enters one per line
      const mmsRaw = (values.mms_ids_raw ?? '').trim();
      const mms_ids = mmsRaw
        ? mmsRaw.split('\n').map((s) => s.trim()).filter(Boolean)
        : [];

      const row = {
        ...(editRow?.id ? { id: editRow.id } : {}),
        ds_domain_id:   values.ds_domain_id?.trim() ?? '',
        roles:          values.roles ?? [],
        mms_ids,
        create_interim: values.create_interim ?? false,
        last_edited_by: currentUser,
        last_edited_at: new Date().toISOString(),
      };
      await upsertMyIspRow(row);
      message.success(editRow ? 'Row updated' : 'Row added');
      closeModal();
      load();
    } catch (e) {
      message.error('Save failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────
  const handleDelete = (rec) => {
    Modal.confirm({
      title:   'Delete Row',
      content: `Remove ${rec.ds_domain_id}?`,
      okText:  'Delete',
      okType:  'danger',
      onOk: async () => {
        setDeleting(rec.id);
        try {
          await deleteMyIspRow(rec.id);
          setRows((prev) => prev.filter((r) => r.id !== rec.id));
          message.success('Row deleted');
        } catch (e) {
          message.error('Delete failed: ' + e.message);
        } finally {
          setDeleting(null);
        }
      },
    });
  };

  // ── Columns ───────────────────────────────────────────────
  const cols = [
    {
      title: 'DS Domain ID', dataIndex: 'ds_domain_id', key: 'ds_domain_id', width: 260,
      render: (v) => <Text code style={{ fontSize: 11 }}>{v}</Text>,
    },
    {
      title: 'Roles', dataIndex: 'roles', key: 'roles',
      render: (roles) => (
        <Space size={[4, 4]} wrap>
          {(roles ?? []).map((r) => (
            <Tag key={r} color={roleTagColor(r)} style={{ fontSize: 10, marginBottom: 2 }}>{r}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'MMS IDs', dataIndex: 'mms_ids', key: 'mms_ids', width: 220,
      render: (ids) => (
        <Space size={[4, 4]} wrap>
          {(ids ?? []).map((id) => (
            <Tag key={id} color="default" style={{ fontSize: 10, fontFamily: 'monospace', marginBottom: 2 }}>{id}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'Create Interim', dataIndex: 'create_interim', key: 'create_interim', width: 110,
      filters: [{ text: 'Yes', value: true }, { text: 'No', value: false }],
      onFilter: (value, record) => record.create_interim === value,
      render: (v) => (
        <Tag color={v ? 'green' : 'default'} style={{ fontSize: 11 }}>{v ? 'Yes' : 'No'}</Tag>
      ),
    },
    {
      title: 'Last Edited', dataIndex: 'last_edited_at', key: 'last_edited_at', width: 130,
      render: (v) => v
        ? <Text type="secondary" style={{ fontSize: 11 }}>{new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</Text>
        : '—',
    },
    {
      title: 'Actions', key: 'actions', width: 80, fixed: 'right',
      render: (_, rec) => (
        <Space size={4}>
          {canEdit && (
            <Tooltip title="Edit">
              <Button
                size="small" type="text"
                icon={<Edit3 size={13} color="#8892a4" />}
                onClick={() => openEdit(rec)}
              />
            </Tooltip>
          )}
          {canDelete && (
            <Tooltip title="Delete">
              <Button
                size="small" type="text"
                loading={deleting === rec.id}
                icon={<Trash2 size={13} color="#f87171" />}
                onClick={() => handleDelete(rec)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    },
  ];

  // ── Stats ─────────────────────────────────────────────────
  const withInterim  = rows.filter((r) => r.create_interim).length;
  const withoutInterim = rows.length - withInterim;

  // ── Render ─────────────────────────────────────────────────
  return (
    <div style={{ padding: 20 }}>

      {/* Summary cards */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
        {[
          { label: 'Total IDs',        value: rows.length,     color: '#22c55e' },
          { label: 'Create Interim',   value: withInterim,     color: '#f59e0b' },
          { label: 'No Interim',       value: withoutInterim,  color: '#8892a4' },
        ].map(({ label, value, color }) => (
          <Card key={label} size="small" style={{ flex: '1 1 120px', borderTop: `3px solid ${color}`, background: 'var(--bg-card)' }}>
            <Text type="secondary" style={{ fontSize: 11, display: 'block' }}>{label}</Text>
            <div style={{ fontSize: 24, fontWeight: 700, color, lineHeight: 1.3 }}>{value}</div>
          </Card>
        ))}
      </div>

      {/* Main table */}
      <Card
        title={
          <Space>
            <KeyRound size={15} />
            <span>MyISP Module Roles</span>
            <Tag style={{ fontSize: 10 }}>{rows.length} IDs</Tag>
          </Space>
        }
        styles={{ header: { borderBottom: '1px solid #252d42' } }}
        extra={
          <Space size={6}>
            <Input.Search
              size="small" placeholder="Search DS Domain ID…"
              value={search} onChange={(e) => setSearch(e.target.value)}
              style={{ width: 240 }} allowClear
            />
            <Tooltip title="Refresh">
              <Button size="small" icon={<RefreshCw size={13} />} onClick={load} loading={loading} />
            </Tooltip>
            {canEdit && (
              <Button
                type="primary" size="small" icon={<Plus size={13} />}
                onClick={openAdd}
                style={{ background: '#217346', borderColor: '#217346' }}
              >
                Add Row
              </Button>
            )}
          </Space>
        }
      >
        {loading ? (
          <div style={{ textAlign: 'center', padding: 40 }}><Spin /></div>
        ) : (
          <Table
            dataSource={filtered}
            columns={cols}
            rowKey="id"
            size="small"
            scroll={{ x: 900 }}
            pagination={{ pageSize: 20, showSizeChanger: false, showTotal: (t) => `${t} rows` }}
          />
        )}
      </Card>

      {/* Add / Edit modal */}
      <Modal
        title={
          <Space>
            {editRow ? <Edit3 size={14} /> : <Plus size={14} />}
            {editRow ? 'Edit DS Domain Row' : 'Add DS Domain Row'}
          </Space>
        }
        open={modalOpen}
        onCancel={closeModal}
        footer={null}
        width={540}
        destroyOnClose
      >
        <Form form={form} layout="vertical" onFinish={handleSave} style={{ marginTop: 8 }}>

          <Form.Item
            name="ds_domain_id" label="DS Domain ID"
            rules={[{ required: true, message: 'Required' }]}
          >
            <Input placeholder="e.g. T5364.9013@ds.dev.accenture.com" size="middle" />
          </Form.Item>

          <Form.Item name="roles" label="Roles">
            <Select
              mode="multiple" size="middle"
              options={DS_ROLE_OPTIONS}
              placeholder="Select one or more roles…"
              allowClear
              maxTagCount="responsive"
            />
          </Form.Item>

          <Form.Item
            name="mms_ids_raw" label="MMS IDs (one per line)"
            tooltip="Enter each MMS ID on a separate line"
          >
            <Input.TextArea
              rows={4}
              placeholder={'0012465874\n0012466013\nTECH-8000001233'}
              style={{ fontFamily: 'monospace', fontSize: 12 }}
            />
          </Form.Item>

          <Form.Item name="create_interim" label="Create Interim" valuePropName="checked">
            <Switch checkedChildren="Yes" unCheckedChildren="No" />
          </Form.Item>

          <Form.Item style={{ marginBottom: 0 }}>
            <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
              <Button icon={<X size={13} />} onClick={closeModal}>Cancel</Button>
              <Button
                type="primary" htmlType="submit" loading={saving}
                style={{ background: '#217346', borderColor: '#217346' }}
              >
                {editRow ? 'Save Changes' : 'Add Row'}
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
