// Generated by GitHub Copilot
import { useEffect, useState } from 'react';
import {
  Table, Typography, Card, message, Skeleton, Modal, Form, Input,
  Button, Space, Tooltip,
} from 'antd';
import { Users, RefreshCw, Plus, Trash2, Edit3 } from 'lucide-react';
import { fetchProdRoles, upsertProdRolesRow, deleteProdRolesRow } from '../../services/api.js';

const { Text } = Typography;

/**
 * ProdRolesSheet — displays and edits the production team roles roster.
 * Columns: Team Lead | Module | Resource EID | Role Details.
 * Only accessible by admin and tl. Backed by the prod_roles Supabase table.
 * @param {{ currentUser: string, role: string }} props
 */
export default function ProdRolesSheet({ currentUser, role }) {
  const [rows,      setRows]      = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [search,    setSearch]    = useState('');
  const [editRow,   setEditRow]   = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [saving,    setSaving]    = useState(false);
  const [deleting,  setDeleting]  = useState(null);
  const [form]      = Form.useForm();

  const canEdit   = role === 'admin' || role === 'tl';
  const canDelete = role === 'admin';

  // ── Load ──────────────────────────────────────────────────
  const load = () => {
    setLoading(true);
    fetchProdRoles()
      .then(setRows)
      .catch((e) => message.error('Failed to load: ' + e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  // ── Open modal ────────────────────────────────────────────
  const openAdd = () => {
    setEditRow(null);
    form.resetFields();
    setModalOpen(true);
  };

  const openEdit = (row) => {
    setEditRow(row);
    form.setFieldsValue(row);
    setModalOpen(true);
  };

  // ── Save ──────────────────────────────────────────────────
  const handleSave = async () => {
    let values;
    try { values = await form.validateFields(); } catch { return; }
    setSaving(true);
    try {
      const payload = {
        ...(editRow ? { id: editRow.id } : {}),
        team_lead:    values.team_lead?.trim()    ?? '',
        module:       values.module?.trim()       ?? '',
        resource_eid: values.resource_eid?.trim() ?? '',
        role_details: values.role_details?.trim() ?? '',
        updated_by:   currentUser,
      };
      await upsertProdRolesRow(payload);
      message.success(editRow ? 'Row updated' : 'Row added');
      setModalOpen(false);
      load();
    } catch (e) {
      message.error('Save failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────
  const handleDelete = (id) => {
    Modal.confirm({
      title: 'Delete this entry?',
      okText: 'Delete', okType: 'danger',
      onOk: async () => {
        setDeleting(id);
        try {
          await deleteProdRolesRow(id);
          message.success('Deleted');
          load();
        } catch (e) {
          message.error('Delete failed: ' + e.message);
        } finally {
          setDeleting(null);
        }
      },
    });
  };

  // ── Filter ────────────────────────────────────────────────
  const filtered = rows.filter((r) => {
    const q = search.toLowerCase();
    return !q
      || r.team_lead?.toLowerCase().includes(q)
      || r.module?.toLowerCase().includes(q)
      || r.resource_eid?.toLowerCase().includes(q)
      || r.role_details?.toLowerCase().includes(q);
  });

  // ── Columns ───────────────────────────────────────────────
  const columns = [
    {
      title: 'Team Lead',
      dataIndex: 'team_lead',
      key: 'team_lead',
      width: 180,
      render: (v) => <Text strong style={{ color: '#e2e8f0' }}>{v}</Text>,
    },
    {
      title: 'Module',
      dataIndex: 'module',
      key: 'module',
      width: 160,
      render: (v) => <Text style={{ color: '#94a3b8' }}>{v}</Text>,
    },
    {
      title: 'Resource EID',
      dataIndex: 'resource_eid',
      key: 'resource_eid',
      width: 200,
      render: (v) => (
        <Text copyable style={{ color: '#38bdf8', fontFamily: 'monospace', fontSize: 12 }}>{v}</Text>
      ),
    },
    {
      title: 'Role Details',
      dataIndex: 'role_details',
      key: 'role_details',
      render: (v) => <Text style={{ color: '#cbd5e1' }}>{v}</Text>,
    },
    ...(canEdit ? [{
      title: 'Actions',
      key: 'actions',
      width: 80,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          <Tooltip title="Edit">
            <Button
              type="text" size="small"
              icon={<Edit3 size={13} />}
              onClick={() => openEdit(record)}
              style={{ color: '#60a5fa' }}
            />
          </Tooltip>
          {canDelete && (
            <Tooltip title="Delete">
              <Button
                type="text" size="small" danger
                icon={<Trash2 size={13} />}
                loading={deleting === record.id}
                onClick={() => handleDelete(record.id)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    }] : []),
  ];

  return (
    <>
      <Card
        size="small"
        style={{ margin: '16px 0', background: 'var(--bg-card)', border: '1px solid var(--border-subtle)' }}
        title={
          <Space>
            <Users size={14} color="#22c55e" />
            <Text strong style={{ color: '#e2e8f0' }}>Prod Roles</Text>
            <Text style={{ color: '#64748b', fontSize: 11 }}>{filtered.length} entries</Text>
          </Space>
        }
        extra={
          <Space>
            <Input
              placeholder="Search..."
              size="small"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              allowClear
              style={{ width: 180 }}
            />
            <Tooltip title="Refresh">
              <Button size="small" type="text" icon={<RefreshCw size={13} />} onClick={load} style={{ color: '#8892a4' }} />
            </Tooltip>
            {canEdit && (
              <Button size="small" type="primary" icon={<Plus size={13} />} onClick={openAdd}>
                + Add Entry
              </Button>
            )}
          </Space>
        }
      >
        {loading ? <Skeleton active /> : (
          <Table
            size="small"
            dataSource={filtered}
            columns={columns}
            rowKey="id"
            pagination={{ pageSize: 20, showSizeChanger: false }}
            scroll={{ x: 700 }}
          />
        )}
      </Card>

      <Modal
        open={modalOpen}
        title={editRow ? 'Edit Entry' : 'Add Entry'}
        onCancel={() => setModalOpen(false)}
        onOk={handleSave}
        confirmLoading={saving}
        okText="Save"
        destroyOnClose
      >
        <Form form={form} layout="vertical" size="small" style={{ marginTop: 12 }}>
          <Form.Item name="team_lead" label="Team Lead" rules={[{ required: true, message: 'Required' }]}>
            <Input placeholder="e.g. John Smith" />
          </Form.Item>
          <Form.Item name="module" label="Module" rules={[{ required: true, message: 'Required' }]}>
            <Input placeholder="e.g. DSP / SSA / BPMS" />
          </Form.Item>
          <Form.Item name="resource_eid" label="Resource EID" rules={[{ required: true, message: 'Required' }]}>
            <Input placeholder="e.g. john.smith" />
          </Form.Item>
          <Form.Item name="role_details" label="Role Details" rules={[{ required: true, message: 'Required' }]}>
            <Input.TextArea rows={3} placeholder="Describe the role or responsibilities" />
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
}
