// Generated by GitHub Copilot
import { useEffect, useState } from 'react';
import {
  Table, Typography, Card, message, Skeleton, Modal, Form, Input,
  Button, Space, Tooltip, Select, Row, Col,
} from 'antd';
import { Users, RefreshCw, Plus, Trash2, Edit3, Download } from 'lucide-react';
import * as XLSX from 'xlsx';
import { fetchProdRoles, upsertProdRolesRow, deleteProdRolesRow } from '../../services/api.js';
import { LEAD_NAME_OPTIONS } from '../../utils/leadNames.js';
import { MONTH_OPTIONS, currentMonthKey } from '../../utils/constants.js';

const { Text } = Typography;

const MODULE_OPTIONS = ['DSP', 'SSA', 'GenAI', 'BPMS', 'AMS', 'IMS', 'SI', 'Other']
  .map((v) => ({ value: v, label: v }));

/**
 * ProdRolesSheet — displays and edits the production team roles roster.
 * Columns: Team Lead | Module | Resource EID | Role Details.
 * Only accessible by admin and tl. Backed by the prod_roles Supabase table.
 * @param {{ currentUser: string, role: string }} props
 */
export default function ProdRolesSheet({ currentUser, role }) {
  const [rows,        setRows]        = useState([]);
  const [loading,     setLoading]     = useState(true);
  const [search,      setSearch]      = useState('');
  const [monthFilter, setMonthFilter] = useState('');
  const [editRow,     setEditRow]     = useState(null);
  const [modalOpen,   setModalOpen]   = useState(false);
  const [saving,      setSaving]      = useState(false);
  const [deleting,    setDeleting]    = useState(null);
  const [form]        = Form.useForm();

  const canEdit   = role === 'admin' || role === 'tl';
  const canDelete = role === 'admin';

  // ── Load ──────────────────────────────────────────────────
  const load = () => {
    setLoading(true);
    fetchProdRoles()
      .then(setRows)
      .catch((e) => message.error('Failed to load: ' + e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  // ── Open modal ────────────────────────────────────────────
  const openAdd = () => {
    setEditRow(null);
    form.resetFields();
    form.setFieldsValue({ month: currentMonthKey() });
    setModalOpen(true);
  };

  const openEdit = (row) => {
    setEditRow(row);
    form.setFieldsValue(row);
    setModalOpen(true);
  };

  // ── Save ──────────────────────────────────────────────────
  const handleSave = async () => {
    let values;
    try { values = await form.validateFields(); } catch { return; }
    setSaving(true);
    try {
      const payload = {
        ...(editRow ? { id: editRow.id } : {}),
        month:        values.month        ?? currentMonthKey(),
        team_lead:    values.team_lead?.trim()    ?? '',
        module:       values.module?.trim()       ?? '',
        resource_eid: values.resource_eid?.trim() ?? '',
        role_details: values.role_details?.trim() ?? '',
        updated_by:   currentUser,
      };
      await upsertProdRolesRow(payload);
      message.success(editRow ? 'Row updated' : 'Row added');
      setModalOpen(false);
      load();
    } catch (e) {
      message.error('Save failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────
  const handleDelete = (id) => {
    Modal.confirm({
      title: 'Delete this entry?',
      okText: 'Delete', okType: 'danger',
      onOk: async () => {
        setDeleting(id);
        try {
          await deleteProdRolesRow(id);
          message.success('Deleted');
          load();
        } catch (e) {
          message.error('Delete failed: ' + e.message);
        } finally {
          setDeleting(null);
        }
      },
    });
  };

  // ── Excel export ──────────────────────────────────────────
  const exportExcel = () => {
    const data = filtered.map((r) => ({
      Month:          MONTH_OPTIONS.find((m) => m.value === r.month)?.label ?? r.month ?? '',
      'Team Lead':    r.team_lead    ?? '',
      Module:         r.module       ?? '',
      'Resource EID': r.resource_eid ?? '',
      'Role Details': r.role_details ?? '',
    }));
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Team Roles');
    XLSX.writeFile(wb, `Team_Roles_${monthFilter || 'All'}.xlsx`);
  };

  // ── Filter ────────────────────────────────────────────────
  const filtered = rows.filter((r) => {
    const q = search.toLowerCase();
    const matchMonth  = !monthFilter || r.month === monthFilter;
    const matchSearch = !q
      || r.team_lead?.toLowerCase().includes(q)
      || r.module?.toLowerCase().includes(q)
      || r.resource_eid?.toLowerCase().includes(q)
      || r.role_details?.toLowerCase().includes(q);
    return matchMonth && matchSearch;
  });

  // ── Columns ───────────────────────────────────────────────
  const columns = [
    {
      title: 'Month',
      dataIndex: 'month',
      key: 'month',
      width: 130,
      render: (v) => {
        const lbl = MONTH_OPTIONS.find((m) => m.value === v)?.label ?? v ?? '—';
        return <Text style={{ color: '#a78bfa', fontSize: 12 }}>{lbl}</Text>;
      },
    },
    {
      title: 'Team Lead',
      dataIndex: 'team_lead',
      key: 'team_lead',
      width: 180,
      render: (v) => <Text strong style={{ color: '#e2e8f0' }}>{v}</Text>,
    },
    {
      title: 'Module',
      dataIndex: 'module',
      key: 'module',
      width: 160,
      render: (v) => <Text style={{ color: '#94a3b8' }}>{v}</Text>,
    },
    {
      title: 'Resource EID',
      dataIndex: 'resource_eid',
      key: 'resource_eid',
      width: 200,
      render: (v) => (
        <Text copyable style={{ color: '#38bdf8', fontFamily: 'monospace', fontSize: 12 }}>{v}</Text>
      ),
    },
    {
      title: 'Role Details',
      dataIndex: 'role_details',
      key: 'role_details',
      render: (v) => <Text style={{ color: '#cbd5e1' }}>{v}</Text>,
    },
    ...(canEdit ? [{
      title: 'Actions',
      key: 'actions',
      width: 80,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          <Tooltip title="Edit">
            <Button
              type="text" size="small"
              icon={<Edit3 size={13} />}
              onClick={() => openEdit(record)}
              style={{ color: '#60a5fa' }}
            />
          </Tooltip>
          {canDelete && (
            <Tooltip title="Delete">
              <Button
                type="text" size="small" danger
                icon={<Trash2 size={13} />}
                loading={deleting === record.id}
                onClick={() => handleDelete(record.id)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    }] : []),
  ];

  return (
    <>
      <Card
        size="small"
        style={{ margin: '16px 0', background: 'var(--bg-card)', border: '1px solid var(--border-subtle)' }}
        title={
          <Space>
            <Users size={14} color="var(--accent)" />
            <Text strong style={{ color: '#e2e8f0' }}>Prod Roles</Text>
            <Text style={{ color: '#64748b', fontSize: 11 }}>{filtered.length} entries</Text>
          </Space>
        }
        extra={
          <Space>
            <Select
              size="small"
              allowClear
              placeholder="All Months"
              options={MONTH_OPTIONS}
              value={monthFilter || undefined}
              onChange={(v) => setMonthFilter(v ?? '')}
              style={{ width: 140 }}
            />
            <Input
              placeholder="Search..."
              size="small"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              allowClear
              style={{ width: 150 }}
            />
            <Tooltip title="Refresh">
              <Button size="small" type="text" icon={<RefreshCw size={13} />} onClick={load} style={{ color: '#8892a4' }} />
            </Tooltip>
            <Tooltip title="Export to Excel">
              <Button size="small" type="text" icon={<Download size={13} />} onClick={exportExcel} style={{ color: 'var(--accent)' }} />
            </Tooltip>
            {canEdit && (
              <Button size="small" type="primary" icon={<Plus size={13} />} onClick={openAdd}>
                + Add Entry
              </Button>
            )}
          </Space>
        }
      >
        {loading ? <Skeleton active /> : (
          <Table
            size="small"
            dataSource={filtered}
            columns={columns}
            rowKey="id"
            pagination={{ pageSize: 20, showSizeChanger: false }}
            scroll={{ x: 700 }}
          />
        )}
      </Card>

      <Modal
        open={modalOpen}
        title={editRow ? 'Edit Entry' : 'Add Entry'}
        onCancel={() => setModalOpen(false)}
        onOk={handleSave}
        confirmLoading={saving}
        okText="Save"
        destroyOnClose
      >
        <Form form={form} layout="vertical" size="small" style={{ marginTop: 12 }}>
          <Row gutter={12}>
            <Col span={12}>
              <Form.Item name="month" label="Month" rules={[{ required: true, message: 'Required' }]}>
                <Select options={MONTH_OPTIONS} placeholder="Select month" allowClear />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="module" label="Module" rules={[{ required: true, message: 'Required' }]}>
                <Select options={MODULE_OPTIONS} placeholder="Select module" allowClear showSearch />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item name="team_lead" label="Team Lead" rules={[{ required: true, message: 'Required' }]}>
            <Select
              showSearch
              allowClear
              placeholder="Select or type a name"
              options={LEAD_NAME_OPTIONS}
              filterOption={(input, opt) => opt.label.toLowerCase().includes(input.toLowerCase())}
            />
          </Form.Item>
          <Form.Item name="resource_eid" label="Resource EID" rules={[{ required: true, message: 'Required' }]}>
            <Input placeholder="e.g. john.smith" />
          </Form.Item>
          <Form.Item name="role_details" label="Role Details" rules={[{ required: true, message: 'Required' }]}>
            <Input.TextArea rows={3} placeholder="Describe the role or responsibilities" />
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
}
