// Generated by GitHub Copilot
import { useEffect, useState, useRef } from 'react';
import {
  Table, Tag, Typography, Card, message, Skeleton, Modal, Form, Input,
  Button, Space, Select, Tooltip, Row, Col, Divider,
} from 'antd';
import { ShieldCheck, RefreshCw, Plus, Trash2, Edit3, X } from 'lucide-react';
import { fetchRolesAccess, upsertRolesAccessRow, deleteRolesAccessRow } from '../../services/api.js';
import { LEAD_NAME_OPTIONS } from '../../utils/leadNames.js';

const { Text } = Typography;

const ROLE_CATEGORY_OPTIONS = [
  'SA', 'SME', 'PMO', 'Internal', 'RA', 'PLD',
].map((v) => ({ value: v, label: v }));

const ROLES_OPTIONS = [
  'Configurator V2V',
  'Advisory Song SA',
  'Enterprise SA',
  'Lead SA Technology',
  'Lead SA (S&C)',
  'Support SA Technology',
  'Overall Song Delivery Approver',
  'Mobilization SME',
  'Central PMO',
  'SA Team Manager',
  'PCAT PMO',
  'APG/APD User',
  'Super User',
  'Operation User',
  'Market Delivery Lead',
  'PCAT Lead',
  'Reviewer/Approver',
  'Portfolio Lead',
  'Pilot user',
  'Pilot user access',
  'Lead SA Data Tech',
  'Advisory Song SA',
  'Support SA Song',
].filter((v, i, a) => a.indexOf(v) === i)
  .map((v) => ({ value: v, label: v }));

const SERVICE_OPTIONS = ['ALL', 'NA', 'Song', 'Technology', 'Cross Service', 'Operations', 'Security'].map((v) => ({ value: v, label: v }));

const DASHBOARD_OPTIONS = ['Assigned', 'NA'].map((v) => ({ value: v, label: v }));

/** Returns a colour for a given role category tag */
const categoryColor = (cat) => ({
  SA: 'blue', SME: 'purple', PMO: 'orange', Internal: 'green', RA: 'cyan', PLD: 'gold',
}[cat] ?? 'default');

/**
 * RolesAccessSheet — displays and edits the enterprise user roster.
 * Only accessible by admin and tl. Backed by the roles_access Supabase table.
 * @param {{ currentUser: string, role: string }} props
 */
export default function RolesAccessSheet({ currentUser, role }) {
const [rows,       setRows]       = useState([]);
  const [loading,    setLoading]    = useState(true);
  const [search,     setSearch]     = useState('');
  const [editRow,    setEditRow]    = useState(null);
  const [modalOpen,  setModalOpen]  = useState(false);
  const [saving,     setSaving]     = useState(false);
  const [deleting,   setDeleting]   = useState(null);
  const [rolesOptions, setRolesOptions] = useState(ROLES_OPTIONS);
  const [newRoleInput, setNewRoleInput] = useState('');
  const newRoleRef = useRef(null);
  const [form]      = Form.useForm();

  const canEdit   = role === 'admin' || role === 'tl';
  const canDelete = role === 'admin';

  // ── Load ──────────────────────────────────────────────────
  const load = () => {
    setLoading(true);
    fetchRolesAccess()
      .then(setRows)
      .catch((e) => message.error('Failed to load: ' + e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  // ── Access guard ──────────────────────────────────────────
  if (role !== 'admin' && role !== 'tl' && role !== 'tester') {
    return (
      <div style={{ padding: 24 }}>
        <Card><Text type="secondary">Access restricted. Admins and Super Users only.</Text></Card>
      </div>
    );
  }

  // ── Filtered rows ─────────────────────────────────────────
  const filtered = rows.filter((r) => {
    if (!search) return true;
    const q = search.toLowerCase();
    return (
      r.first_name?.toLowerCase().includes(q) ||
      r.enterprise_id?.toLowerCase().includes(q)
    );
  });

  // ── Open modal ────────────────────────────────────────────
  const openAdd = () => {
    setEditRow(null);
    form.resetFields();
    setModalOpen(true);
  };

  const openEdit = (rec) => {
    setEditRow(rec);
    form.setFieldsValue({
      first_name:     rec.first_name,
      enterprise_id:  rec.enterprise_id,
      role_category:  rec.role_category,
      roles:          rec.roles ?? [],
      service:        rec.service,
      market_mu:      rec.market_mu,
      dashboard:      rec.dashboard,
    });
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setEditRow(null);
    form.resetFields();
  };

  // ── Save ──────────────────────────────────────────────────
  const handleSave = async (values) => {
    setSaving(true);
    try {
      const row = {
        ...(editRow?.id ? { id: editRow.id } : {}),
        first_name:    values.first_name?.trim() ?? '',
        enterprise_id: values.enterprise_id?.trim() ?? '',
        role_category: values.role_category ?? '',
        roles:         values.roles ?? [],
        service:       values.service ?? '',
        market_mu:     values.market_mu?.trim() ?? '',
        dashboard:     values.dashboard ?? '',
        last_edited_by: currentUser,
        last_edited_at: new Date().toISOString(),
      };
      await upsertRolesAccessRow(row);
      message.success(editRow ? 'Entry updated' : 'Entry added');
      closeModal();
      load();
    } catch (e) {
      message.error('Save failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────
  const handleDelete = (rec) => {
    Modal.confirm({
      title:   'Delete Entry',
      content: `Remove ${rec.first_name} (${rec.enterprise_id})?`,
      okText:  'Delete',
      okType:  'danger',
      onOk: async () => {
        setDeleting(rec.id);
        try {
          await deleteRolesAccessRow(rec.id);
          setRows((prev) => prev.filter((r) => r.id !== rec.id));
          message.success('Entry deleted');
        } catch (e) {
          message.error('Delete failed: ' + e.message);
        } finally {
          setDeleting(null);
        }
      },
    });
  };

  // ── Columns ───────────────────────────────────────────────
  const cols = [
    {
      title: 'Lead Name', dataIndex: 'first_name', key: 'first_name', width: 110,
      render: (v) => <Text style={{ fontSize: 12 }}>{v}</Text>,
    },
    {
      title: 'Enterprise ID', dataIndex: 'enterprise_id', key: 'enterprise_id', width: 170,
      render: (v) => <Text code style={{ fontSize: 11 }}>{v}</Text>,
    },
    {
      title: 'Role Category', dataIndex: 'role_category', key: 'role_category', width: 120,
      filters: ROLE_CATEGORY_OPTIONS.map(({ value }) => ({ text: value, value })),
      onFilter: (value, record) => record.role_category === value,
      render: (v) => v ? <Tag color={categoryColor(v)} style={{ fontSize: 11 }}>{v}</Tag> : '—',
    },
    {
      title: 'Roles', dataIndex: 'roles', key: 'roles',
      render: (roles) => (
        <Space size={[4, 4]} wrap>
          {(roles ?? []).map((r) => (
            <Tag key={r} color="geekblue" style={{ fontSize: 10, marginBottom: 2 }}>{r}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'Service', dataIndex: 'service', key: 'service', width: 100,
      render: (v) => <Text type="secondary" style={{ fontSize: 11 }}>{v || '—'}</Text>,
    },
    {
      title: 'Market & MU', dataIndex: 'market_mu', key: 'market_mu', width: 120,
      render: (v) => <Text type="secondary" style={{ fontSize: 11 }}>{v || '—'}</Text>,
    },
    {
      title: 'Dashboard', dataIndex: 'dashboard', key: 'dashboard', width: 100,
      render: (v) => v
        ? <Tag color={v === 'Assigned' ? 'green' : 'default'} style={{ fontSize: 11 }}>{v}</Tag>
        : '—',
    },
    {
      title: 'Actions', key: 'actions', width: 80, fixed: 'right',
      render: (_, rec) => (
        <Space size={4}>
          {canEdit && (
            <Tooltip title="Edit">
              <Button
                size="small" type="text"
                icon={<Edit3 size={13} color="#8892a4" />}
                onClick={() => openEdit(rec)}
              />
            </Tooltip>
          )}
          {canDelete && (
            <Tooltip title="Delete">
              <Button
                size="small" type="text"
                loading={deleting === rec.id}
                icon={<Trash2 size={13} color="#f87171" />}
                onClick={() => handleDelete(rec)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    },
  ];

  // ── Render ─────────────────────────────────────────────────
  return (
    <div style={{ padding: 20 }}>

      {/* Stats row */}
      <Row gutter={[12, 12]} style={{ marginBottom: 20 }}>
        {ROLE_CATEGORY_OPTIONS.map(({ value }) => {
          const count = rows.filter((r) => r.role_category === value).length;
          return (
            <Col key={value} xs={12} sm={8} md={4}>
              <Card size="small" style={{ borderTop: `3px solid var(--accent, #22c55e)`, background: 'var(--bg-card)' }}>
                <Text type="secondary" style={{ fontSize: 11, display: 'block' }}>{value}</Text>
                <div style={{ fontSize: 22, fontWeight: 700, color: '#22c55e', lineHeight: 1.3 }}>{count}</div>
              </Card>
            </Col>
          );
        })}
      </Row>

      {/* Main table */}
      <Card
        title={
          <Space>
            <ShieldCheck size={15} />
            <span>Roles &amp; Access</span>
            <Tag style={{ fontSize: 10 }}>{rows.length} entries</Tag>
          </Space>
        }
        styles={{ header: { borderBottom: '1px solid #252d42' } }}
        extra={
          <Space size={6}>
            <Input.Search
              size="small" placeholder="Search name or Enterprise ID…"
              value={search} onChange={(e) => setSearch(e.target.value)}
              style={{ width: 220 }} allowClear
            />
            <Tooltip title="Refresh">
              <Button size="small" icon={<RefreshCw size={13} />} onClick={load} loading={loading} />
            </Tooltip>
            {canEdit && (
              <Button
                type="primary" size="small" icon={<Plus size={13} />}
                onClick={openAdd}
                style={{ background: '#217346', borderColor: '#217346' }}
              >
                Add Entry
              </Button>
            )}
          </Space>
        }
      >
        {loading ? (
          <Skeleton active paragraph={{ rows: 8 }} />
        ) : (
          <Table
            dataSource={filtered}
            columns={cols}
            rowKey="id"
            size="small"
            scroll={{ x: 1100 }}
            pagination={{ pageSize: 20, showSizeChanger: false, showTotal: (t) => `${t} entries` }}
          />
        )}
      </Card>

      {/* Add / Edit modal */}
      <Modal
        title={
          <Space>
            {editRow ? <Edit3 size={14} /> : <Plus size={14} />}
            {editRow ? 'Edit Entry' : 'Add Entry'}
          </Space>
        }
        open={modalOpen}
        onCancel={closeModal}
        footer={null}
        width={560}
        destroyOnClose
      >
        <Form form={form} layout="vertical" onFinish={handleSave} style={{ marginTop: 8 }}>
          <Row gutter={12}>
            <Col span={24}>
              <Form.Item name="first_name" label="Lead Name" rules={[{ required: true, message: 'Required' }]}>
                <Select
                  size="middle"
                  showSearch
                  allowClear
                  placeholder="Select or type a name"
                  options={LEAD_NAME_OPTIONS}
                  filterOption={(input, opt) => opt.label.toLowerCase().includes(input.toLowerCase())}
                />
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={12}>
            <Col span={12}>
              <Form.Item name="enterprise_id" label="Enterprise ID" rules={[{ required: true, message: 'Required' }]}>
                <Input placeholder="e.g. reshmi.doddi" size="middle" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="role_category" label="Role Category">
                <Select size="middle" options={ROLE_CATEGORY_OPTIONS} placeholder="Select…" allowClear />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item name="roles" label="Roles">
            <Select
              mode="multiple" size="middle"
              options={rolesOptions}
              placeholder="Select one or more roles…"
              allowClear
              maxTagCount="responsive"
              dropdownRender={(menu) => (
                <>
                  {menu}
                  <Divider style={{ margin: '6px 0' }} />
                  <Space style={{ padding: '4px 8px 8px' }}>
                    <Input
                      ref={newRoleRef}
                      size="small"
                      placeholder="New role name…"
                      value={newRoleInput}
                      onChange={(e) => setNewRoleInput(e.target.value)}
                      onKeyDown={(e) => e.stopPropagation()}
                      style={{ width: 200 }}
                    />
                    <Button
                      size="small"
                      type="primary"
                      icon={<Plus size={12} />}
                      onClick={() => {
                        const v = newRoleInput.trim();
                        if (!v) return;
                        if (!rolesOptions.find((o) => o.value === v)) {
                          setRolesOptions((prev) => [...prev, { value: v, label: v }]);
                        }
                        const cur = form.getFieldValue('roles') ?? [];
                        if (!cur.includes(v)) form.setFieldValue('roles', [...cur, v]);
                        setNewRoleInput('');
                        setTimeout(() => newRoleRef.current?.focus(), 0);
                      }}
                    >
                      Add
                    </Button>
                  </Space>
                </>
              )}
            />
          </Form.Item>

          <Row gutter={12}>
            <Col span={8}>
              <Form.Item name="service" label="Service">
                <Select size="middle" options={SERVICE_OPTIONS} placeholder="Select…" allowClear />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="market_mu" label="Market &amp; MU">
                <Input placeholder="e.g. NA" size="middle" />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="dashboard" label="Dashboard">
                <Select size="middle" options={DASHBOARD_OPTIONS} placeholder="Select…" allowClear />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item style={{ marginBottom: 0 }}>
            <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
              <Button icon={<X size={13} />} onClick={closeModal}>Cancel</Button>
              <Button
                type="primary" htmlType="submit" loading={saving}
                style={{ background: '#217346', borderColor: '#217346' }}
              >
                {editRow ? 'Save Changes' : 'Add Entry'}
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
