import { useState } from 'react';
import { Card, Table, Tag, Space, Badge, Button, Typography, Alert, Popconfirm, message, Skeleton, Empty } from 'antd';
import { Shield, Trash2, Plus, Zap } from 'lucide-react';
import EditableCell  from '../shared/EditableCell.jsx';
import StatusSelect  from '../shared/StatusSelect.jsx';
import ModuleSaveBar from '../shared/ModuleSaveBar.jsx';
import { ROLES }                                      from '../../utils/constants.js';
import { filterData, fmtDate, nextKey, isHighPriority } from '../../utils/helpers.jsx';

const { Text } = Typography;

// Generated by GitHub Copilot
/** Returns onRow props that let users drag-resize row height by pulling the bottom edge. */
const makeResizableRow = () => () => ({
  className: 'resizable-row',
  style: { position: 'relative' },
  onMouseDown: (e) => {
    const row = e.currentTarget;
    const rect = row.getBoundingClientRect();
    if (e.clientY < rect.bottom - 6) return;
    e.preventDefault();
    const startY = e.clientY;
    const startH = row.offsetHeight;
    row.style.height = startH + 'px';
    const onMove = (me) => { row.style.height = Math.max(32, startH + me.clientY - startY) + 'px'; };
    const onUp   = () => { document.removeEventListener('mousemove', onMove); document.removeEventListener('mouseup', onUp); };
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
  },
});

export default function SSASheet({
  searchQuery, ssaData, setSsaData,
  editMode, currentUser, role,
  isDirty, lastSaved, loading,
}) {
  const roleConfig = ROLES[role] ?? ROLES.viewer;
  const [quickFilter, setQuickFilter] = useState('all');

  const applyQuickFilter = (data) => {
    switch (quickFilter) {
      case 'progress': return data.filter((r) => /progress/i.test(r.status || ''));
      case 'failed':   return data.filter((r) => /fail/i.test(r.status || ''));
      case 'blocked':  return data.filter((r) => isHighPriority(r.status));
      case 'mine':     return data.filter((r) => r.tester?.toLowerCase() === (currentUser || '').toLowerCase());
      default:         return data;
    }
  };

  const canEditRow = (record) => {
    if (!roleConfig.canEdit) return false;
    if (roleConfig.onlyOwnRows)
      return record.tester && record.tester.toLowerCase() === (currentUser || '').toLowerCase();
    return true;
  };

  const handleSave = (key, field, value) => {
    setSsaData((prev) =>
      prev.map((r) =>
        r.key === key
          ? { ...r, [field]: value, lastEditedBy: currentUser || 'Unknown', lastEditedAt: new Date().toISOString() }
          : r
      )
    );
  };

  const addRow = (env) => {
    setSsaData((prev) => [
      ...prev,
      {
        key: nextKey(ssaData), id: crypto.randomUUID(), tester: '', module: '', dealId: '',
        dealId2: '', dealId3: '', dealId4: '', status: '',
        comments: '', versionId: 1, env: env ?? 'PT',
        lastEditedBy: currentUser || 'Unknown', lastEditedAt: new Date().toISOString(),
      },
    ]);
    message.success(`New SSA ${env ?? 'PT'} row added`);
  };

  const deleteRow = (key) => {
    setSsaData((prev) => prev.filter((r) => r.key !== key));
    message.info('Row deleted');
  };

  // Column order: Tester → Module → Ver. → Deal IDs → Status → Last Edited Date → Comments
  const cols = [
    {
      title: 'Tester', dataIndex: 'tester', key: 'tester', width: 160,
      render: (v, rec) =>
        editMode && canEditRow(rec)
          ? <EditableCell value={v} record={rec} dataIndex="tester" onSave={handleSave} />
          : <Text strong style={{ fontSize: 12 }}>{v}</Text>,
    },
    {
      title: 'Module', dataIndex: 'module', key: 'module', width: 170,
      render: (v, rec) =>
        editMode && canEditRow(rec)
          ? <EditableCell value={v} record={rec} dataIndex="module" onSave={handleSave} />
          : v,
    },
    {
      title: 'Ver.', dataIndex: 'versionId', key: 'versionId', width: 55,
      render: (v, rec) =>
        editMode && canEditRow(rec)
          ? <EditableCell value={String(v ?? 1)} record={rec} dataIndex="versionId"
              onSave={(key, field, val) => handleSave(key, field, Number(val) || 1)} />
          : <Text type="secondary" style={{ fontSize: 11 }}>{v ?? 1}</Text>,
    },
    ...['dealId', 'dealId2', 'dealId3', 'dealId4'].map((field, i) => ({
      title: i === 0 ? 'Deal ID' : `Deal ID ${i + 1}`,
      dataIndex: field, key: field, width: 105,
      render: (v, rec) =>
        editMode && canEditRow(rec)
          ? <EditableCell value={v} record={rec} dataIndex={field} onSave={handleSave} />
          : (v ? <Text copyable style={{ fontFamily: 'monospace', fontSize: 11 }}>{v}</Text> : <Text type="secondary">—</Text>),
    })),
    {
      title: 'Status', dataIndex: 'status', key: 'status', width: 190,
      render: (v, rec) => (
        <StatusSelect value={v} record={rec} onSave={handleSave} readOnly={!editMode || !canEditRow(rec)} />
      ),
    },
    {
      title: 'Last Edited Date', dataIndex: 'lastEditedAt', key: 'lastEditedAt', width: 130,
      render: (v, rec) => !v ? <Text type="secondary">—</Text> : (
        <Text type="secondary" style={{ fontSize: 11 }} title={rec.lastEditedBy || ''}>{fmtDate(v)}</Text>
      ),
    },
    {
      title: 'Comments', dataIndex: 'comments', key: 'comments', width: 180,
      render: (v, rec) =>
        editMode && canEditRow(rec)
          ? <EditableCell value={v ?? ''} record={rec} dataIndex="comments" onSave={handleSave} />
          : (v ? <Text style={{ fontSize: 12 }}>{v}</Text> : <Text type="secondary">—</Text>),
    },
  ];

  if (editMode && roleConfig.canDelete) {
    cols.push({
      title: '', key: 'actions', width: 50, fixed: 'right',
      render: (_, rec) => (
        <Popconfirm title="Delete?" onConfirm={() => deleteRow(rec.key)} okText="Yes" cancelText="No" placement="left">
          <Button type="text" danger size="small" icon={<Trash2 size={14} />} />
        </Popconfirm>
      ),
    });
  }

  return (
    <div style={{ padding: 20 }}>
      <ModuleSaveBar moduleName="SSA" isDirty={isDirty} lastSaved={lastSaved} />
      <Alert
        message={<Space><Zap size={14} /> GenAI — SSA Module Testing</Space>}
        description="Ensure configuration is applied to all deals before proceeding."
        type="info" showIcon style={{ marginBottom: 16, borderRadius: 10 }}
      />
      {loading ? (
        <Skeleton active paragraph={{ rows: 10 }} />
      ) : (
        <>
          {/* Quick-filter chips */}
          <div role="group" aria-label="Filter rows" style={{ display: 'flex', gap: 6, marginBottom: 14, flexWrap: 'wrap' }}>
            {[{key:'all',label:'All'},{key:'progress',label:'In Progress'},{key:'failed',label:'Failed'},{key:'blocked',label:'Blocked'},{key:'mine',label:'Mine'}].map((f) => (
              <button
                key={f.key}
                aria-pressed={quickFilter === f.key}
                onClick={() => setQuickFilter(f.key)}
                style={quickFilter === f.key ? {
                  padding: '3px 12px', borderRadius: 20, cursor: 'pointer',
                  border: '1.5px solid #8b5cf6', background: 'rgba(139,92,246,0.12)',
                  color: '#8b5cf6', fontSize: 12, fontFamily: 'inherit', transition: 'all 0.15s',
                } : {
                  padding: '3px 12px', borderRadius: 20, cursor: 'pointer',
                  border: '1px solid #252d42', background: 'transparent',
                  color: '#8892a4', fontSize: 12, fontFamily: 'inherit', transition: 'all 0.15s',
                }}
              >
                {f.label}
              </button>
            ))}
          </div>

          {(() => {
            const base    = applyQuickFilter(ssaData);
            const ptData  = filterData(base.filter((r) => (r.env ?? 'PT') === 'PT'),  searchQuery);
            const uatData = filterData(base.filter((r) => r.env === 'UAT'), searchQuery);
            return (
              <Card
                title={<Space><Shield size={16} /> SSA / GenAI Testing <Badge count={ssaData.length} style={{ background: '#722ed1' }} /></Space>}
                size="small" className="glass-card"
                styles={{ header: { background: 'linear-gradient(90deg, #1a1035, #1a1f2e)', borderBottom: '2px solid #6d28d9' } }}
                extra={editMode && roleConfig.canAddRow && (
                  <Space size={4}>
                    <Button type="dashed" size="small" icon={<Plus size={13} />} onClick={() => addRow('PT')}>+ PT</Button>
                    <Button type="dashed" size="small" icon={<Plus size={13} />} onClick={() => addRow('UAT')}>+ UAT</Button>
                  </Space>
                )}
              >
                <div style={{ display: 'flex', gap: 0, alignItems: 'flex-start' }}>
                  <div style={{ flex: '1 1 0', minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                      <Tag color="green" style={{ fontWeight: 700, fontSize: 12 }}>PT</Tag>
                      <Text type="secondary" style={{ fontSize: 11 }}>{ptData.length} row{ptData.length !== 1 ? 's' : ''}</Text>
                    </div>
                    <section aria-label="PT SSA Rows">
                      <Table dataSource={ptData} columns={cols} rowKey="key"
                        pagination={false} size="small" bordered scroll={{ x: 'max-content' }}
                        onRow={makeResizableRow()}
                        rowClassName={(r) => isHighPriority(r.status) ? 'row-error' : ''}
                        locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No PT rows" /> }}
                      />
                    </section>
                  </div>
                  <div style={{ width: 1, alignSelf: 'stretch', background: 'var(--border)', margin: '0 12px', flexShrink: 0 }} aria-hidden="true" />
                  <div style={{ flex: '1 1 0', minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                      <Tag color="orange" style={{ fontWeight: 700, fontSize: 12 }}>UAT</Tag>
                      <Text type="secondary" style={{ fontSize: 11 }}>{uatData.length} row{uatData.length !== 1 ? 's' : ''}</Text>
                    </div>
                    <section aria-label="UAT SSA Rows">
                      <Table dataSource={uatData} columns={cols} rowKey="key"
                        pagination={false} size="small" bordered scroll={{ x: 'max-content' }}
                        onRow={makeResizableRow()}
                        rowClassName={(r) => isHighPriority(r.status) ? 'row-error' : ''}
                        locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No UAT rows" /> }}
                      />
                    </section>
                  </div>
                </div>
              </Card>
            );
          })()}
        </>
      )}
    </div>
  );
}
