// Generated by GitHub Copilot
import { useState } from 'react';
import { Form, Input, Button, Alert, Result } from 'antd';
import {
  LayoutDashboard, Mail, Lock, LogIn, ShieldCheck,
  FileSpreadsheet, KeyRound, Activity, Users, BarChart2,
} from 'lucide-react';
import { supabase } from '../../services/supabase.js';

/* ─── Inline styles shared across the component ─── */
const S = {
  page: {
    minHeight: '100vh',
    background: '#0a0c14',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    fontFamily: "'Plus Jakarta Sans','Inter','Segoe UI',sans-serif",
  },
  card: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    width: '100%',
    maxWidth: 880,
    minHeight: 540,
    borderRadius: 24,
    overflow: 'hidden',
    boxShadow: '0 40px 100px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.06)',
  },
  left: {
    flex: 1,
    background: 'linear-gradient(145deg, #0f2318 0%, #0b1a12 50%, #091611 100%)',
    borderRight: '1px solid rgba(34,197,94,0.12)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: '44px 40px',
    position: 'relative',
    overflow: 'hidden',
  },
  right: {
    width: 420,
    background: '#0d0f18',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '48px 40px',
  },
  label: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    display: 'block',
    marginBottom: 6,
  },
  inputStyle: { borderRadius: 10, height: 46, background: '#141824', borderColor: '#252d42', color: '#e2e8f0' },
  submitBtn: {
    width: '100%', height: 48, borderRadius: 10,
    background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
    border: 'none', fontWeight: 700, fontSize: 15,
    boxShadow: '0 4px 20px rgba(34,197,94,0.35)',
    letterSpacing: 0.2,
  },
};

const features = [
  { Icon: ShieldCheck,    label: 'Role-based access control',       sub: 'Admin · TL · Tester · Viewer' },
  { Icon: FileSpreadsheet, label: 'Real-time data sync',            sub: 'Powered by Supabase' },
  { Icon: Activity,       label: 'Live test coverage tracking',      sub: 'DSP Manual & Automation' },
];

const stats = [
  { Icon: Users,     value: 'Team',    label: 'Members' },
  { Icon: BarChart2, value: 'DSP',     label: 'Testing' },
  { Icon: ShieldCheck, value: 'SSA',   label: 'GenAI' },
];

/**
 * LoginPage — premium dark redesign.
 * Left panel: animated branding with feature highlights.
 * Right panel: sign-in / forgot-password forms.
 */
export default function LoginPage({ onSignIn }) {
  const [loading,      setLoading]      = useState(false);
  const [error,        setError]        = useState('');
  const [forgotMode,   setForgotMode]   = useState(false);
  const [resetEmail,   setResetEmail]   = useState('');
  const [resetSent,    setResetSent]    = useState(false);
  const [resetLoading, setResetLoading] = useState(false);
  const [resetError,   setResetError]   = useState('');
  const [msLoading,    setMsLoading]    = useState(false);
  const [loginTab,     setLoginTab]     = useState('password'); // 'password' | 'magic'
  const [magicEmail,   setMagicEmail]   = useState('');
  const [magicLoading, setMagicLoading] = useState(false);
  const [magicSent,    setMagicSent]    = useState(false);
  const [magicError,   setMagicError]   = useState('');

  const handleMagicLink = async () => {
    if (!magicEmail.trim()) { setMagicError('Please enter your email.'); return; }
    setMagicError('');
    setMagicLoading(true);
    const base = window.location.pathname.includes('/DSP_E2E') ? '/DSP_E2E/' : '/';
    const { error: err } = await supabase.auth.signInWithOtp({
      email: magicEmail.trim().toLowerCase(),
      options: { emailRedirectTo: window.location.origin + base },
    });
    setMagicLoading(false);
    if (err) { setMagicError(err.message || 'Failed to send link.'); return; }
    setMagicSent(true);
  };

  const handleMicrosoft = async () => {
    setMsLoading(true);
    const base = window.location.pathname.includes('/DSP_E2E') ? '/DSP_E2E/' : '/';
    const { error: err } = await supabase.auth.signInWithOAuth({
      provider: 'azure',
      options: { redirectTo: window.location.origin + base },
    });
    if (err) { setError(err.message || 'Microsoft sign-in failed.'); setMsLoading(false); }
  };

  const handleFinish = async ({ email, password }) => {
    setError('');
    setLoading(true);
    const { error: err } = await onSignIn(email, password);
    if (err) setError(err.message || 'Login failed.');
    setLoading(false);
  };

  const handleForgot = async () => {
    if (!resetEmail.trim()) { setResetError('Please enter your email.'); return; }
    setResetError('');
    setResetLoading(true);
    const { error: err } = await supabase.auth.resetPasswordForEmail(resetEmail.trim().toLowerCase(), {
      redirectTo: window.location.origin + (window.location.pathname.includes('/DSP_E2E') ? '/DSP_E2E/' : '/'),
    });
    setResetLoading(false);
    if (err) { setResetError(err.message); return; }
    setResetSent(true);
  };

  return (
    <div style={S.page}>
      {/* ── Ambient orbs ── */}
      <div style={{ position:'fixed', top:'-10%', left:'-5%',  width:520, height:520, borderRadius:'50%', background:'radial-gradient(circle, rgba(34,197,94,0.10) 0%, transparent 65%)',  pointerEvents:'none', filter:'blur(10px)' }} />
      <div style={{ position:'fixed', bottom:'-8%', right:'-5%', width:460, height:460, borderRadius:'50%', background:'radial-gradient(circle, rgba(99,102,241,0.09) 0%, transparent 65%)', pointerEvents:'none', filter:'blur(10px)' }} />
      <div style={{ position:'fixed', top:'40%', left:'30%', width:300, height:300, borderRadius:'50%', background:'radial-gradient(circle, rgba(14,165,233,0.06) 0%, transparent 70%)', pointerEvents:'none', filter:'blur(16px)' }} />

      <div style={S.card}>

        {/* ════ LEFT PANEL ════ */}
        <div style={S.left}>
          {/* Decorative grid overlay */}
          <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(34,197,94,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(34,197,94,0.03) 1px, transparent 1px)', backgroundSize:'40px 40px', pointerEvents:'none' }} />
          {/* Corner glow */}
          <div style={{ position:'absolute', top:-80, right:-80, width:280, height:280, borderRadius:'50%', background:'radial-gradient(circle, rgba(34,197,94,0.18) 0%, transparent 65%)', pointerEvents:'none' }} />

          {/* Logo */}
          <div style={{ position:'relative', zIndex:1 }}>
            <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:40 }}>
              <div style={{ width:44, height:44, borderRadius:13, background:'linear-gradient(135deg,#22c55e,#16a34a)', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 0 28px rgba(34,197,94,0.45), 0 0 0 1px rgba(34,197,94,0.3)' }}>
                <LayoutDashboard size={22} color="#fff" />
              </div>
              <div>
                <div style={{ color:'#e2e8f0', fontWeight:800, fontSize:18, lineHeight:1.2 }}>MyISP</div>
                <div style={{ color:'#4b5568', fontSize:11, fontWeight:500 }}>Insight &amp; Status Platform</div>
              </div>
            </div>

            <div style={{ marginBottom:10 }}>
              <span style={{ display:'inline-block', padding:'3px 12px', borderRadius:20, background:'rgba(34,197,94,0.12)', border:'1px solid rgba(34,197,94,0.25)', color:'#4ade80', fontSize:11, fontWeight:700, letterSpacing:0.5 }}>
                ● LIVE
              </span>
            </div>
            <h1 style={{ color:'#e2e8f0', fontSize:30, fontWeight:800, lineHeight:1.2, margin:'0 0 12px', letterSpacing:'-0.5px' }}>
              Welcome back
            </h1>
            <p style={{ color:'#64748b', fontSize:13, lineHeight:1.8, margin:'0 0 36px', maxWidth:300 }}>
              Your central hub for DSP, SSA, team testing data and attendance insights.
            </p>

            {/* Feature list */}
            <div style={{ display:'flex', flexDirection:'column', gap:12 }}>
              {features.map(({ Icon, label, sub }) => (
                <div key={label} style={{ display:'flex', alignItems:'center', gap:12 }}>
                  <div style={{ width:34, height:34, borderRadius:9, flexShrink:0, background:'rgba(34,197,94,0.1)', border:'1px solid rgba(34,197,94,0.18)', display:'flex', alignItems:'center', justifyContent:'center' }}>
                    <Icon size={15} color="#22c55e" />
                  </div>
                  <div>
                    <div style={{ color:'#cbd5e1', fontSize:13, fontWeight:600, lineHeight:1.3 }}>{label}</div>
                    <div style={{ color:'#475569', fontSize:11 }}>{sub}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Bottom stat pills */}
          <div style={{ position:'relative', zIndex:1, display:'flex', gap:8, flexWrap:'wrap' }}>
            {stats.map(({ Icon, value, label }) => (
              <div key={label} style={{ display:'flex', alignItems:'center', gap:6, padding:'6px 12px', borderRadius:10, background:'rgba(255,255,255,0.04)', border:'1px solid rgba(255,255,255,0.07)' }}>
                <Icon size={12} color="#4ade80" />
                <span style={{ color:'#94a3b8', fontSize:11, fontWeight:600 }}>{value}</span>
                <span style={{ color:'#475569', fontSize:11 }}>{label}</span>
              </div>
            ))}
          </div>
        </div>

        {/* ════ RIGHT PANEL ════ */}
        <div style={S.right}>

          {forgotMode ? (
            /* ── Forgot password ── */
            resetSent ? (
              <div style={{ textAlign:'center' }}>
                <div style={{ width:64, height:64, borderRadius:18, background:'rgba(34,197,94,0.12)', border:'1px solid rgba(34,197,94,0.25)', display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 20px' }}>
                  <Mail size={28} color="#22c55e" />
                </div>
                <div style={{ color:'#e2e8f0', fontSize:22, fontWeight:800, marginBottom:8 }}>Check your email</div>
                <div style={{ color:'#64748b', fontSize:13, lineHeight:1.7, marginBottom:28 }}>
                  We sent a reset link to <strong style={{ color:'#e2e8f0' }}>{resetEmail}</strong>
                </div>
                <Button size="large" onClick={() => { setForgotMode(false); setResetSent(false); setResetEmail(''); }}
                  style={{ borderRadius:10, height:46, width:'100%', background:'rgba(255,255,255,0.05)', border:'1px solid #252d42', color:'#e2e8f0', fontWeight:600 }}>
                  ← Back to Sign in
                </Button>
              </div>
            ) : (
              <>
                <div style={{ marginBottom:28 }}>
                  <div style={{ color:'#e2e8f0', fontSize:22, fontWeight:800, marginBottom:4 }}>Reset password</div>
                  <div style={{ color:'#64748b', fontSize:13 }}>We'll send a link to your inbox</div>
                </div>
                {resetError && <Alert message={resetError} type="error" showIcon closable onClose={() => setResetError('')} style={{ marginBottom:18, borderRadius:8 }} />}
                <div style={{ marginBottom:20 }}>
                  <span style={S.label}>Email address</span>
                  <Input size="large" prefix={<Mail size={14} color="#4b5568" style={{ marginRight:4 }} />}
                    placeholder="you@accenture.com" value={resetEmail}
                    onChange={(e) => setResetEmail(e.target.value)} onPressEnter={handleForgot}
                    style={S.inputStyle} />
                </div>
                <Button type="primary" size="large" loading={resetLoading} icon={<KeyRound size={15} />}
                  onClick={handleForgot} style={{ ...S.submitBtn, marginBottom:16 }}>
                  {resetLoading ? 'Sending…' : 'Send Reset Link'}
                </Button>
                <Button type="link" onClick={() => { setForgotMode(false); setResetError(''); }}
                  style={{ color:'#64748b', fontSize:13, padding:0 }}>
                  ← Back to Sign in
                </Button>
              </>
            )
          ) : (
            /* ── Sign in ── */
            <>
              {/* Login method tabs */}
              <div style={{ display:'flex', gap:4, marginBottom:28, background:'#0d1117', borderRadius:10, padding:4 }}>
                {[{key:'password',label:'Password'},{key:'magic',label:'Magic Link'}].map((t) => (
                  <button key={t.key} onClick={() => { setLoginTab(t.key); setError(''); setMagicError(''); setMagicSent(false); }}
                    style={{
                      flex:1, height:36, borderRadius:8, border:'none', cursor:'pointer',
                      background: loginTab === t.key ? '#1a1f2e' : 'transparent',
                      color: loginTab === t.key ? '#e2e8f0' : '#4b5568',
                      fontWeight: loginTab === t.key ? 700 : 500,
                      fontSize:13,
                      fontFamily:"'Plus Jakarta Sans','Inter','Segoe UI',sans-serif",
                      boxShadow: loginTab === t.key ? '0 1px 4px rgba(0,0,0,0.4)' : 'none',
                      transition:'all 0.15s',
                    }}
                  >{t.label}</button>
                ))}
              </div>

              {loginTab === 'magic' ? (
                /* ── Magic Link panel ── */
                magicSent ? (
                  <div style={{ textAlign:'center', paddingTop:12 }}>
                    <div style={{ width:56, height:56, borderRadius:16, background:'rgba(34,197,94,0.12)', border:'1px solid rgba(34,197,94,0.25)', display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 16px' }}>
                      <Mail size={24} color="#22c55e" />
                    </div>
                    <div style={{ color:'#e2e8f0', fontSize:20, fontWeight:800, marginBottom:8 }}>Check your email</div>
                    <div style={{ color:'#64748b', fontSize:13, lineHeight:1.7, marginBottom:24 }}>
                      We sent a login link to <strong style={{ color:'#e2e8f0' }}>{magicEmail}</strong>.<br/>Click it to sign in instantly.
                    </div>
                    <Button size="large" onClick={() => { setMagicSent(false); setMagicEmail(''); }}
                      style={{ borderRadius:10, height:44, width:'100%', background:'rgba(255,255,255,0.05)', border:'1px solid #252d42', color:'#e2e8f0', fontWeight:600 }}>
                      ← Use a different email
                    </Button>
                  </div>
                ) : (
                  <>
                    <div style={{ marginBottom:20 }}>
                      <div style={{ color:'#e2e8f0', fontSize:22, fontWeight:800, marginBottom:4 }}>Sign in instantly</div>
                      <div style={{ color:'#64748b', fontSize:13 }}>No password needed — we'll email you a link</div>
                    </div>
                    {magicError && <Alert message={magicError} type="error" showIcon closable onClose={() => setMagicError('')} style={{ marginBottom:16, borderRadius:8 }} />}
                    <div style={{ marginBottom:20 }}>
                      <span style={S.label}>Email address</span>
                      <Input size="large"
                        prefix={<Mail size={14} color="#4b5568" style={{ marginRight:4 }} />}
                        placeholder="you@accenture.com" value={magicEmail}
                        onChange={(e) => setMagicEmail(e.target.value)}
                        onPressEnter={handleMagicLink}
                        style={S.inputStyle} />
                    </div>
                    <Button type="primary" size="large" loading={magicLoading}
                      onClick={handleMagicLink}
                      style={S.submitBtn}>
                      {magicLoading ? 'Sending…' : 'Send Login Link'}
                    </Button>
                  </>
                )
              ) : (
                /* ── Password panel ── */
                <>
              {error && <Alert message={error} type="error" showIcon closable onClose={() => setError('')} style={{ marginBottom:20, borderRadius:10 }} />}

              <Form layout="vertical" onFinish={handleFinish} requiredMark={false}>
                <Form.Item
                  label={<span style={S.label}>Email address</span>}
                  name="email"
                  rules={[{ required:true, message:'Please enter your email' }, { type:'email', message:'Enter a valid email' }]}
                  style={{ marginBottom:18 }}
                >
                  <Input size="large"
                    prefix={<Mail size={14} color="#4b5568" style={{ marginRight:4 }} />}
                    placeholder="you@accenture.com" autoComplete="email"
                    style={S.inputStyle} />
                </Form.Item>

                <Form.Item
                  label={
                    <div style={{ display:'flex', justifyContent:'space-between', width:'100%', alignItems:'center' }}>
                      <span style={S.label}>Password</span>
                      <Button type="link" size="small"
                        onClick={() => { setForgotMode(true); setError(''); }}
                        style={{ color:'#22c55e', fontSize:11, padding:0, height:'auto', lineHeight:1 }}>
                        Forgot password?
                      </Button>
                    </div>
                  }
                  name="password"
                  rules={[{ required:true, message:'Please enter your password' }]}
                  style={{ marginBottom:28 }}
                >
                  <Input.Password size="large"
                    prefix={<Lock size={14} color="#4b5568" style={{ marginRight:4 }} />}
                    placeholder="Enter your password" autoComplete="current-password"
                    style={S.inputStyle} />
                </Form.Item>

                <Form.Item style={{ marginBottom:0 }}>
                  <Button type="primary" htmlType="submit" size="large"
                    loading={loading} icon={<LogIn size={15} />}
                    style={S.submitBtn}>
                    {loading ? 'Signing in…' : 'Sign in'}
                  </Button>
                </Form.Item>
              </Form>

              {/* OR divider */}
              <div style={{ display:'flex', alignItems:'center', gap:12, margin:'20px 0 16px' }}>
                <div style={{ flex:1, height:1, background:'#1e2332' }} />
                <span style={{ color:'#374151', fontSize:11 }}>or</span>
                <div style={{ flex:1, height:1, background:'#1e2332' }} />
              </div>

              {/* Microsoft OAuth button */}
              <button
                onClick={handleMicrosoft}
                disabled={msLoading}
                style={{
                  width:'100%', height:46, borderRadius:10, cursor:'pointer',
                  background:'#141824', border:'1px solid #252d42',
                  display:'flex', alignItems:'center', justifyContent:'center', gap:10,
                  color:'#e2e8f0', fontSize:14, fontWeight:600,
                  fontFamily:"'Plus Jakarta Sans','Inter','Segoe UI',sans-serif",
                  transition:'border-color 0.2s, background 0.2s',
                  opacity: msLoading ? 0.7 : 1,
                }}
                onMouseEnter={(e) => { e.currentTarget.style.borderColor = '#0078d4'; e.currentTarget.style.background = '#161b2e'; }}
                onMouseLeave={(e) => { e.currentTarget.style.borderColor = '#252d42'; e.currentTarget.style.background = '#141824'; }}
              >
                {/* Official Microsoft logo SVG */}
                <svg width="18" height="18" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect x="1"  y="1"  width="9" height="9" fill="#F25022"/>
                  <rect x="11" y="1"  width="9" height="9" fill="#7FBA00"/>
                  <rect x="1"  y="11" width="9" height="9" fill="#00A4EF"/>
                  <rect x="11" y="11" width="9" height="9" fill="#FFB900"/>
                </svg>
                {msLoading ? 'Redirecting…' : 'Sign in with Microsoft'}
              </button>

              {/* Bottom divider */}
              <div style={{ display:'flex', alignItems:'center', gap:12, margin:'20px 0 0' }}>
                <div style={{ flex:1, height:1, background:'#1e2332' }} />
                <span style={{ color:'#374151', fontSize:11 }}>secured by Supabase</span>
                <div style={{ flex:1, height:1, background:'#1e2332' }} />
              </div>

              <div style={{ color:'#374151', fontSize:11, textAlign:'center', marginTop:10 }}>
                Contact your admin to create or reset your account.
              </div>
              </>
              )}
            </>
          )}
        </div>

      </div>
    </div>
  );
}
